:- module(facts_monthly_climate, []).

monthly_climate(1, afg, rain).
monthly_climate(1, alb, rain).
monthly_climate(1, dza, rain).
monthly_climate(1, and, snow).
monthly_climate(1, ago, warm).
monthly_climate(1, arg, warm).
monthly_climate(1, arm, snow).
monthly_climate(1, aut, snow).
monthly_climate(1, aze, rain).
monthly_climate(1, bhr, rain).
monthly_climate(1, bgd, rain).
monthly_climate(1, blr, snow).
monthly_climate(1, bel, rain).
monthly_climate(1, blz, warm).
monthly_climate(1, ben, warm).
monthly_climate(1, bmu, rain).
monthly_climate(1, btn, rain).
monthly_climate(1, bol, rain).
monthly_climate(1, bih, rain).
monthly_climate(1, bwa, warm).
monthly_climate(1, bra, warm).
monthly_climate(1, brn, warm).
monthly_climate(1, bgr, snow).
monthly_climate(1, bfa, warm).
monthly_climate(1, bdi, warm).
monthly_climate(1, cpv, warm).
monthly_climate(1, khm, warm).
monthly_climate(1, cmr, warm).
monthly_climate(1, can, snow).
monthly_climate(1, caf, warm).
monthly_climate(1, tcd, warm).
monthly_climate(1, chl, rain).
monthly_climate(1, chn, snow).
monthly_climate(1, col, warm).
monthly_climate(1, com, warm).
monthly_climate(1, cog, warm).
monthly_climate(1, cri, rain).
monthly_climate(1, civ, warm).
monthly_climate(1, hrv, rain).
monthly_climate(1, cyp, rain).
monthly_climate(1, cze, snow).
monthly_climate(1, cod, warm).
monthly_climate(1, dnk, rain).
monthly_climate(1, dji, warm).
monthly_climate(1, ecu, warm).
monthly_climate(1, egy, rain).
monthly_climate(1, slv, warm).
monthly_climate(1, gnq, warm).
monthly_climate(1, eri, rain).
monthly_climate(1, est, snow).
monthly_climate(1, eth, rain).
monthly_climate(1, fin, snow).
monthly_climate(1, fra, rain).
monthly_climate(1, gab, warm).
monthly_climate(1, gmb, warm).
monthly_climate(1, geo, rain).
monthly_climate(1, deu, snow).
monthly_climate(1, gha, warm).
monthly_climate(1, gib, rain).
monthly_climate(1, grc, rain).
monthly_climate(1, grl, rain).
monthly_climate(1, gtm, rain).
monthly_climate(1, ggy, warm).
monthly_climate(1, gnb, warm).
monthly_climate(1, gin, warm).
monthly_climate(1, guy, warm).
monthly_climate(1, hnd, warm).
monthly_climate(1, hun, snow).
monthly_climate(1, isl, snow).
monthly_climate(1, ind, rain).
monthly_climate(1, idn, warm).
monthly_climate(1, irn, rain).
monthly_climate(1, irq, rain).
monthly_climate(1, irl, rain).
monthly_climate(1, isr, rain).
monthly_climate(1, ita, rain).
monthly_climate(1, jpn, rain).
monthly_climate(1, jey, warm).
monthly_climate(1, jor, rain).
monthly_climate(1, kaz, snow).
monthly_climate(1, ken, warm).
monthly_climate(1, kwt, rain).
monthly_climate(1, kgz, snow).
monthly_climate(1, lao, warm).
monthly_climate(1, lva, snow).
monthly_climate(1, lbn, rain).
monthly_climate(1, lso, rain).
monthly_climate(1, lbr, warm).
monthly_climate(1, lby, rain).
monthly_climate(1, lie, rain).
monthly_climate(1, ltu, snow).
monthly_climate(1, lux, rain).
monthly_climate(1, mkd, rain).
monthly_climate(1, mdg, warm).
monthly_climate(1, mwi, warm).
monthly_climate(1, mys, warm).
monthly_climate(1, mdv, warm).
monthly_climate(1, mli, warm).
monthly_climate(1, mlt, rain).
monthly_climate(1, mrt, warm).
monthly_climate(1, mus, warm).
monthly_climate(1, myt, warm).
monthly_climate(1, mex, rain).
monthly_climate(1, mda, snow).
monthly_climate(1, mco, rain).
monthly_climate(1, mng, snow).
monthly_climate(1, mne, rain).
monthly_climate(1, mar, rain).
monthly_climate(1, moz, warm).
monthly_climate(1, mmr, warm).
monthly_climate(1, nam, warm).
monthly_climate(1, npl, rain).
monthly_climate(1, nld, rain).
monthly_climate(1, nic, warm).
monthly_climate(1, ner, warm).
monthly_climate(1, nga, warm).
monthly_climate(1, prk, snow).
monthly_climate(1, nor, snow).
monthly_climate(1, omn, rain).
monthly_climate(1, pak, rain).
monthly_climate(1, pse, warm).
monthly_climate(1, pan, warm).
monthly_climate(1, pry, warm).
monthly_climate(1, per, rain).
monthly_climate(1, phl, warm).
monthly_climate(1, pol, snow).
monthly_climate(1, prt, rain).
monthly_climate(1, qat, rain).
monthly_climate(1, rou, snow).
monthly_climate(1, rus, snow).
monthly_climate(1, rwa, rain).
monthly_climate(1, shn, rain).
monthly_climate(1, smr, rain).
monthly_climate(1, wsm, warm).
monthly_climate(1, stp, warm).
monthly_climate(1, sau, rain).
monthly_climate(1, sen, warm).
monthly_climate(1, srb, snow).
monthly_climate(1, syc, warm).
monthly_climate(1, sle, warm).
monthly_climate(1, sgp, warm).
monthly_climate(1, svk, snow).
monthly_climate(1, svn, snow).
monthly_climate(1, som, warm).
monthly_climate(1, zaf, warm).
monthly_climate(1, kor, snow).
monthly_climate(1, ssd, warm).
monthly_climate(1, esp, rain).
monthly_climate(1, lka, warm).
monthly_climate(1, sdn, warm).
monthly_climate(1, sur, warm).
monthly_climate(1, swz, warm).
monthly_climate(1, swe, snow).
monthly_climate(1, che, snow).
monthly_climate(1, syr, rain).
monthly_climate(1, tjk, snow).
monthly_climate(1, tha, warm).
monthly_climate(1, tls, warm).
monthly_climate(1, tgo, warm).
monthly_climate(1, tun, rain).
monthly_climate(1, tur, rain).
monthly_climate(1, tkm, rain).
monthly_climate(1, uga, warm).
monthly_climate(1, ukr, snow).
monthly_climate(1, are, rain).
monthly_climate(1, gbr, rain).
monthly_climate(1, tza, warm).
monthly_climate(1, usa, rain).
monthly_climate(1, ury, warm).
monthly_climate(1, uzb, snow).
monthly_climate(1, ven, warm).
monthly_climate(1, vnm, warm).
monthly_climate(1, esh, rain).
monthly_climate(1, yem, warm).
monthly_climate(1, zmb, warm).
monthly_climate(1, zwe, warm).
monthly_climate(2, afg, rain).
monthly_climate(2, alb, rain).
monthly_climate(2, dza, rain).
monthly_climate(2, and, snow).
monthly_climate(2, ago, warm).
monthly_climate(2, arg, warm).
monthly_climate(2, arm, snow).
monthly_climate(2, aut, snow).
monthly_climate(2, aze, rain).
monthly_climate(2, bhr, rain).
monthly_climate(2, bgd, warm).
monthly_climate(2, blr, snow).
monthly_climate(2, bel, rain).
monthly_climate(2, blz, warm).
monthly_climate(2, ben, warm).
monthly_climate(2, bmu, rain).
monthly_climate(2, btn, rain).
monthly_climate(2, bol, rain).
monthly_climate(2, bih, rain).
monthly_climate(2, bwa, warm).
monthly_climate(2, bra, warm).
monthly_climate(2, brn, warm).
monthly_climate(2, bgr, rain).
monthly_climate(2, bfa, warm).
monthly_climate(2, bdi, warm).
monthly_climate(2, cpv, warm).
monthly_climate(2, khm, warm).
monthly_climate(2, cmr, warm).
monthly_climate(2, can, snow).
monthly_climate(2, caf, warm).
monthly_climate(2, tcd, warm).
monthly_climate(2, chl, rain).
monthly_climate(2, chn, rain).
monthly_climate(2, col, warm).
monthly_climate(2, com, warm).
monthly_climate(2, cog, warm).
monthly_climate(2, cri, rain).
monthly_climate(2, civ, warm).
monthly_climate(2, hrv, rain).
monthly_climate(2, cyp, rain).
monthly_climate(2, cze, snow).
monthly_climate(2, cod, warm).
monthly_climate(2, dnk, rain).
monthly_climate(2, dji, warm).
monthly_climate(2, ecu, warm).
monthly_climate(2, egy, rain).
monthly_climate(2, slv, warm).
monthly_climate(2, gnq, warm).
monthly_climate(2, eri, warm).
monthly_climate(2, est, snow).
monthly_climate(2, eth, rain).
monthly_climate(2, fin, snow).
monthly_climate(2, fra, rain).
monthly_climate(2, gab, warm).
monthly_climate(2, gmb, warm).
monthly_climate(2, geo, rain).
monthly_climate(2, deu, rain).
monthly_climate(2, gha, warm).
monthly_climate(2, gib, rain).
monthly_climate(2, grc, rain).
monthly_climate(2, grl, rain).
monthly_climate(2, gtm, rain).
monthly_climate(2, ggy, warm).
monthly_climate(2, gnb, warm).
monthly_climate(2, gin, warm).
monthly_climate(2, guy, warm).
monthly_climate(2, hnd, warm).
monthly_climate(2, hun, rain).
monthly_climate(2, isl, snow).
monthly_climate(2, ind, rain).
monthly_climate(2, idn, warm).
monthly_climate(2, irn, rain).
monthly_climate(2, irq, rain).
monthly_climate(2, irl, rain).
monthly_climate(2, isr, rain).
monthly_climate(2, ita, rain).
monthly_climate(2, jpn, rain).
monthly_climate(2, jey, warm).
monthly_climate(2, jor, rain).
monthly_climate(2, kaz, snow).
monthly_climate(2, ken, warm).
monthly_climate(2, kwt, rain).
monthly_climate(2, kgz, snow).
monthly_climate(2, lao, warm).
monthly_climate(2, lva, snow).
monthly_climate(2, lbn, rain).
monthly_climate(2, lso, rain).
monthly_climate(2, lbr, warm).
monthly_climate(2, lby, rain).
monthly_climate(2, lie, rain).
monthly_climate(2, ltu, snow).
monthly_climate(2, lux, rain).
monthly_climate(2, mkd, rain).
monthly_climate(2, mdg, warm).
monthly_climate(2, mwi, warm).
monthly_climate(2, mys, warm).
monthly_climate(2, mdv, warm).
monthly_climate(2, mli, warm).
monthly_climate(2, mlt, rain).
monthly_climate(2, mrt, warm).
monthly_climate(2, mus, warm).
monthly_climate(2, myt, warm).
monthly_climate(2, mex, rain).
monthly_climate(2, mda, snow).
monthly_climate(2, mco, rain).
monthly_climate(2, mng, snow).
monthly_climate(2, mne, rain).
monthly_climate(2, mar, rain).
monthly_climate(2, moz, warm).
monthly_climate(2, mmr, warm).
monthly_climate(2, nam, warm).
monthly_climate(2, npl, rain).
monthly_climate(2, nld, rain).
monthly_climate(2, nic, warm).
monthly_climate(2, ner, warm).
monthly_climate(2, nga, warm).
monthly_climate(2, prk, snow).
monthly_climate(2, nor, snow).
monthly_climate(2, omn, warm).
monthly_climate(2, pak, rain).
monthly_climate(2, pse, warm).
monthly_climate(2, pan, warm).
monthly_climate(2, pry, warm).
monthly_climate(2, per, rain).
monthly_climate(2, phl, warm).
monthly_climate(2, pol, snow).
monthly_climate(2, prt, rain).
monthly_climate(2, qat, rain).
monthly_climate(2, rou, snow).
monthly_climate(2, rus, snow).
monthly_climate(2, rwa, rain).
monthly_climate(2, shn, rain).
monthly_climate(2, smr, rain).
monthly_climate(2, wsm, warm).
monthly_climate(2, stp, warm).
monthly_climate(2, sau, rain).
monthly_climate(2, sen, warm).
monthly_climate(2, srb, rain).
monthly_climate(2, syc, warm).
monthly_climate(2, sle, warm).
monthly_climate(2, sgp, warm).
monthly_climate(2, svk, snow).
monthly_climate(2, svn, snow).
monthly_climate(2, som, warm).
monthly_climate(2, zaf, warm).
monthly_climate(2, kor, rain).
monthly_climate(2, ssd, warm).
monthly_climate(2, esp, rain).
monthly_climate(2, lka, warm).
monthly_climate(2, sdn, warm).
monthly_climate(2, sur, warm).
monthly_climate(2, swz, warm).
monthly_climate(2, swe, snow).
monthly_climate(2, che, snow).
monthly_climate(2, syr, rain).
monthly_climate(2, tjk, snow).
monthly_climate(2, tha, warm).
monthly_climate(2, tls, warm).
monthly_climate(2, tgo, warm).
monthly_climate(2, tun, rain).
monthly_climate(2, tur, rain).
monthly_climate(2, tkm, rain).
monthly_climate(2, uga, warm).
monthly_climate(2, ukr, snow).
monthly_climate(2, are, rain).
monthly_climate(2, gbr, rain).
monthly_climate(2, tza, warm).
monthly_climate(2, usa, rain).
monthly_climate(2, ury, warm).
monthly_climate(2, uzb, rain).
monthly_climate(2, ven, warm).
monthly_climate(2, vnm, warm).
monthly_climate(2, esh, rain).
monthly_climate(2, yem, warm).
monthly_climate(2, zmb, warm).
monthly_climate(2, zwe, warm).
monthly_climate(3, afg, rain).
monthly_climate(3, alb, rain).
monthly_climate(3, dza, rain).
monthly_climate(3, and, rain).
monthly_climate(3, ago, warm).
monthly_climate(3, arg, warm).
monthly_climate(3, arm, rain).
monthly_climate(3, aut, rain).
monthly_climate(3, aze, rain).
monthly_climate(3, bhr, warm).
monthly_climate(3, bgd, warm).
monthly_climate(3, blr, snow).
monthly_climate(3, bel, rain).
monthly_climate(3, blz, warm).
monthly_climate(3, ben, warm).
monthly_climate(3, bmu, rain).
monthly_climate(3, btn, rain).
monthly_climate(3, bol, rain).
monthly_climate(3, bih, rain).
monthly_climate(3, bwa, warm).
monthly_climate(3, bra, warm).
monthly_climate(3, brn, warm).
monthly_climate(3, bgr, rain).
monthly_climate(3, bfa, warm).
monthly_climate(3, bdi, warm).
monthly_climate(3, cpv, warm).
monthly_climate(3, khm, warm).
monthly_climate(3, cmr, warm).
monthly_climate(3, can, snow).
monthly_climate(3, caf, warm).
monthly_climate(3, tcd, warm).
monthly_climate(3, chl, rain).
monthly_climate(3, chn, rain).
monthly_climate(3, col, warm).
monthly_climate(3, com, warm).
monthly_climate(3, cog, warm).
monthly_climate(3, cri, rain).
monthly_climate(3, civ, warm).
monthly_climate(3, hrv, rain).
monthly_climate(3, cyp, rain).
monthly_climate(3, cze, rain).
monthly_climate(3, cod, warm).
monthly_climate(3, dnk, rain).
monthly_climate(3, dji, warm).
monthly_climate(3, ecu, warm).
monthly_climate(3, egy, rain).
monthly_climate(3, slv, warm).
monthly_climate(3, gnq, warm).
monthly_climate(3, eri, warm).
monthly_climate(3, est, snow).
monthly_climate(3, eth, warm).
monthly_climate(3, fin, snow).
monthly_climate(3, fra, rain).
monthly_climate(3, gab, warm).
monthly_climate(3, gmb, warm).
monthly_climate(3, geo, rain).
monthly_climate(3, deu, rain).
monthly_climate(3, gha, warm).
monthly_climate(3, gib, rain).
monthly_climate(3, grc, rain).
monthly_climate(3, grl, warm).
monthly_climate(3, gtm, warm).
monthly_climate(3, ggy, warm).
monthly_climate(3, gnb, warm).
monthly_climate(3, gin, warm).
monthly_climate(3, guy, warm).
monthly_climate(3, hnd, warm).
monthly_climate(3, hun, rain).
monthly_climate(3, isl, snow).
monthly_climate(3, ind, warm).
monthly_climate(3, idn, warm).
monthly_climate(3, irn, rain).
monthly_climate(3, irq, rain).
monthly_climate(3, irl, rain).
monthly_climate(3, isr, rain).
monthly_climate(3, ita, rain).
monthly_climate(3, jpn, rain).
monthly_climate(3, jey, warm).
monthly_climate(3, jor, rain).
monthly_climate(3, kaz, snow).
monthly_climate(3, ken, warm).
monthly_climate(3, kwt, rain).
monthly_climate(3, kgz, rain).
monthly_climate(3, lao, warm).
monthly_climate(3, lva, snow).
monthly_climate(3, lbn, rain).
monthly_climate(3, lso, rain).
monthly_climate(3, lbr, warm).
monthly_climate(3, lby, rain).
monthly_climate(3, lie, rain).
monthly_climate(3, ltu, snow).
monthly_climate(3, lux, rain).
monthly_climate(3, mkd, rain).
monthly_climate(3, mdg, warm).
monthly_climate(3, mwi, warm).
monthly_climate(3, mys, warm).
monthly_climate(3, mdv, warm).
monthly_climate(3, mli, warm).
monthly_climate(3, mlt, rain).
monthly_climate(3, mrt, warm).
monthly_climate(3, mus, warm).
monthly_climate(3, myt, warm).
monthly_climate(3, mex, rain).
monthly_climate(3, mda, rain).
monthly_climate(3, mco, rain).
monthly_climate(3, mng, snow).
monthly_climate(3, mne, rain).
monthly_climate(3, mar, rain).
monthly_climate(3, moz, warm).
monthly_climate(3, mmr, warm).
monthly_climate(3, nam, warm).
monthly_climate(3, npl, rain).
monthly_climate(3, nld, rain).
monthly_climate(3, nic, warm).
monthly_climate(3, ner, warm).
monthly_climate(3, nga, warm).
monthly_climate(3, prk, rain).
monthly_climate(3, nor, snow).
monthly_climate(3, omn, warm).
monthly_climate(3, pak, rain).
monthly_climate(3, pse, warm).
monthly_climate(3, pan, warm).
monthly_climate(3, pry, warm).
monthly_climate(3, per, rain).
monthly_climate(3, phl, warm).
monthly_climate(3, pol, rain).
monthly_climate(3, prt, rain).
monthly_climate(3, qat, warm).
monthly_climate(3, rou, rain).
monthly_climate(3, rus, snow).
monthly_climate(3, rwa, rain).
monthly_climate(3, shn, rain).
monthly_climate(3, smr, rain).
monthly_climate(3, wsm, warm).
monthly_climate(3, stp, warm).
monthly_climate(3, sau, warm).
monthly_climate(3, sen, warm).
monthly_climate(3, srb, rain).
monthly_climate(3, syc, warm).
monthly_climate(3, sle, warm).
monthly_climate(3, sgp, warm).
monthly_climate(3, svk, rain).
monthly_climate(3, svn, rain).
monthly_climate(3, som, warm).
monthly_climate(3, zaf, warm).
monthly_climate(3, kor, rain).
monthly_climate(3, ssd, warm).
monthly_climate(3, esp, rain).
monthly_climate(3, lka, warm).
monthly_climate(3, sdn, warm).
monthly_climate(3, sur, warm).
monthly_climate(3, swz, warm).
monthly_climate(3, swe, snow).
monthly_climate(3, che, rain).
monthly_climate(3, syr, rain).
monthly_climate(3, tjk, rain).
monthly_climate(3, tha, warm).
monthly_climate(3, tls, warm).
monthly_climate(3, tgo, warm).
monthly_climate(3, tun, rain).
monthly_climate(3, tur, rain).
monthly_climate(3, tkm, rain).
monthly_climate(3, uga, warm).
monthly_climate(3, ukr, rain).
monthly_climate(3, are, warm).
monthly_climate(3, gbr, rain).
monthly_climate(3, tza, warm).
monthly_climate(3, usa, rain).
monthly_climate(3, ury, warm).
monthly_climate(3, uzb, rain).
monthly_climate(3, ven, warm).
monthly_climate(3, vnm, warm).
monthly_climate(3, esh, rain).
monthly_climate(3, yem, warm).
monthly_climate(3, zmb, warm).
monthly_climate(3, zwe, warm).
monthly_climate(4, afg, rain).
monthly_climate(4, alb, rain).
monthly_climate(4, dza, rain).
monthly_climate(4, and, rain).
monthly_climate(4, ago, warm).
monthly_climate(4, arg, rain).
monthly_climate(4, arm, rain).
monthly_climate(4, aut, rain).
monthly_climate(4, aze, rain).
monthly_climate(4, bhr, warm).
monthly_climate(4, bgd, warm).
monthly_climate(4, blr, rain).
monthly_climate(4, bel, rain).
monthly_climate(4, blz, warm).
monthly_climate(4, ben, warm).
monthly_climate(4, bmu, rain).
monthly_climate(4, btn, rain).
monthly_climate(4, bol, rain).
monthly_climate(4, bih, rain).
monthly_climate(4, bwa, warm).
monthly_climate(4, bra, warm).
monthly_climate(4, brn, warm).
monthly_climate(4, bgr, rain).
monthly_climate(4, bfa, warm).
monthly_climate(4, bdi, warm).
monthly_climate(4, cpv, warm).
monthly_climate(4, khm, warm).
monthly_climate(4, cmr, warm).
monthly_climate(4, can, rain).
monthly_climate(4, caf, warm).
monthly_climate(4, tcd, warm).
monthly_climate(4, chl, rain).
monthly_climate(4, chn, rain).
monthly_climate(4, col, warm).
monthly_climate(4, com, warm).
monthly_climate(4, cog, warm).
monthly_climate(4, cri, rain).
monthly_climate(4, civ, warm).
monthly_climate(4, hrv, rain).
monthly_climate(4, cyp, rain).
monthly_climate(4, cze, rain).
monthly_climate(4, cod, warm).
monthly_climate(4, dnk, rain).
monthly_climate(4, dji, warm).
monthly_climate(4, ecu, warm).
monthly_climate(4, egy, warm).
monthly_climate(4, slv, warm).
monthly_climate(4, gnq, warm).
monthly_climate(4, eri, warm).
monthly_climate(4, est, rain).
monthly_climate(4, eth, warm).
monthly_climate(4, fin, rain).
monthly_climate(4, fra, rain).
monthly_climate(4, gab, warm).
monthly_climate(4, gmb, warm).
monthly_climate(4, geo, rain).
monthly_climate(4, deu, rain).
monthly_climate(4, gha, warm).
monthly_climate(4, gib, rain).
monthly_climate(4, grc, rain).
monthly_climate(4, grl, warm).
monthly_climate(4, gtm, warm).
monthly_climate(4, ggy, warm).
monthly_climate(4, gnb, warm).
monthly_climate(4, gin, warm).
monthly_climate(4, guy, warm).
monthly_climate(4, hnd, warm).
monthly_climate(4, hun, rain).
monthly_climate(4, isl, rain).
monthly_climate(4, ind, warm).
monthly_climate(4, idn, warm).
monthly_climate(4, irn, rain).
monthly_climate(4, irq, warm).
monthly_climate(4, irl, rain).
monthly_climate(4, isr, rain).
monthly_climate(4, ita, rain).
monthly_climate(4, jpn, rain).
monthly_climate(4, jey, warm).
monthly_climate(4, jor, rain).
monthly_climate(4, kaz, rain).
monthly_climate(4, ken, warm).
monthly_climate(4, kwt, warm).
monthly_climate(4, kgz, rain).
monthly_climate(4, lao, warm).
monthly_climate(4, lva, rain).
monthly_climate(4, lbn, rain).
monthly_climate(4, lso, rain).
monthly_climate(4, lbr, warm).
monthly_climate(4, lby, rain).
monthly_climate(4, lie, rain).
monthly_climate(4, ltu, rain).
monthly_climate(4, lux, rain).
monthly_climate(4, mkd, rain).
monthly_climate(4, mdg, warm).
monthly_climate(4, mwi, warm).
monthly_climate(4, mys, warm).
monthly_climate(4, mdv, warm).
monthly_climate(4, mli, warm).
monthly_climate(4, mlt, rain).
monthly_climate(4, mrt, warm).
monthly_climate(4, mus, warm).
monthly_climate(4, myt, warm).
monthly_climate(4, mex, warm).
monthly_climate(4, mda, rain).
monthly_climate(4, mco, rain).
monthly_climate(4, mng, rain).
monthly_climate(4, mne, rain).
monthly_climate(4, mar, rain).
monthly_climate(4, moz, warm).
monthly_climate(4, mmr, warm).
monthly_climate(4, nam, warm).
monthly_climate(4, npl, warm).
monthly_climate(4, nld, rain).
monthly_climate(4, nic, warm).
monthly_climate(4, ner, warm).
monthly_climate(4, nga, warm).
monthly_climate(4, prk, rain).
monthly_climate(4, nor, rain).
monthly_climate(4, omn, warm).
monthly_climate(4, pak, warm).
monthly_climate(4, pse, warm).
monthly_climate(4, pan, warm).
monthly_climate(4, pry, warm).
monthly_climate(4, per, rain).
monthly_climate(4, phl, warm).
monthly_climate(4, pol, rain).
monthly_climate(4, prt, rain).
monthly_climate(4, qat, warm).
monthly_climate(4, rou, rain).
monthly_climate(4, rus, snow).
monthly_climate(4, rwa, rain).
monthly_climate(4, shn, rain).
monthly_climate(4, smr, rain).
monthly_climate(4, wsm, warm).
monthly_climate(4, stp, warm).
monthly_climate(4, sau, warm).
monthly_climate(4, sen, warm).
monthly_climate(4, srb, rain).
monthly_climate(4, syc, warm).
monthly_climate(4, sle, warm).
monthly_climate(4, sgp, warm).
monthly_climate(4, svk, rain).
monthly_climate(4, svn, rain).
monthly_climate(4, som, warm).
monthly_climate(4, zaf, rain).
monthly_climate(4, kor, rain).
monthly_climate(4, ssd, warm).
monthly_climate(4, esp, rain).
monthly_climate(4, lka, warm).
monthly_climate(4, sdn, warm).
monthly_climate(4, sur, warm).
monthly_climate(4, swz, rain).
monthly_climate(4, swe, rain).
monthly_climate(4, che, rain).
monthly_climate(4, syr, rain).
monthly_climate(4, tjk, rain).
monthly_climate(4, tha, warm).
monthly_climate(4, tls, warm).
monthly_climate(4, tgo, warm).
monthly_climate(4, tun, rain).
monthly_climate(4, tur, rain).
monthly_climate(4, tkm, rain).
monthly_climate(4, uga, warm).
monthly_climate(4, ukr, rain).
monthly_climate(4, are, warm).
monthly_climate(4, gbr, rain).
monthly_climate(4, tza, rain).
monthly_climate(4, usa, rain).
monthly_climate(4, ury, rain).
monthly_climate(4, uzb, rain).
monthly_climate(4, ven, warm).
monthly_climate(4, vnm, warm).
monthly_climate(4, esh, rain).
monthly_climate(4, yem, warm).
monthly_climate(4, zmb, warm).
monthly_climate(4, zwe, rain).
monthly_climate(5, afg, rain).
monthly_climate(5, alb, rain).
monthly_climate(5, dza, rain).
monthly_climate(5, and, rain).
monthly_climate(5, ago, warm).
monthly_climate(5, arg, rain).
monthly_climate(5, arm, rain).
monthly_climate(5, aut, rain).
monthly_climate(5, aze, rain).
monthly_climate(5, bhr, warm).
monthly_climate(5, bgd, warm).
monthly_climate(5, blr, rain).
monthly_climate(5, bel, rain).
monthly_climate(5, blz, warm).
monthly_climate(5, ben, warm).
monthly_climate(5, bmu, warm).
monthly_climate(5, btn, rain).
monthly_climate(5, bol, rain).
monthly_climate(5, bih, rain).
monthly_climate(5, bwa, rain).
monthly_climate(5, bra, warm).
monthly_climate(5, brn, warm).
monthly_climate(5, bgr, rain).
monthly_climate(5, bfa, warm).
monthly_climate(5, bdi, rain).
monthly_climate(5, cpv, warm).
monthly_climate(5, khm, warm).
monthly_climate(5, cmr, warm).
monthly_climate(5, can, rain).
monthly_climate(5, caf, warm).
monthly_climate(5, tcd, warm).
monthly_climate(5, chl, rain).
monthly_climate(5, chn, rain).
monthly_climate(5, col, warm).
monthly_climate(5, com, warm).
monthly_climate(5, cog, warm).
monthly_climate(5, cri, rain).
monthly_climate(5, civ, warm).
monthly_climate(5, hrv, rain).
monthly_climate(5, cyp, warm).
monthly_climate(5, cze, rain).
monthly_climate(5, cod, warm).
monthly_climate(5, dnk, rain).
monthly_climate(5, dji, warm).
monthly_climate(5, ecu, warm).
monthly_climate(5, egy, warm).
monthly_climate(5, slv, warm).
monthly_climate(5, gnq, warm).
monthly_climate(5, eri, warm).
monthly_climate(5, est, rain).
monthly_climate(5, eth, warm).
monthly_climate(5, fin, rain).
monthly_climate(5, fra, rain).
monthly_climate(5, gab, warm).
monthly_climate(5, gmb, warm).
monthly_climate(5, geo, rain).
monthly_climate(5, deu, rain).
monthly_climate(5, gha, warm).
monthly_climate(5, gib, rain).
monthly_climate(5, grc, rain).
monthly_climate(5, grl, warm).
monthly_climate(5, gtm, warm).
monthly_climate(5, ggy, warm).
monthly_climate(5, gnb, warm).
monthly_climate(5, gin, warm).
monthly_climate(5, guy, warm).
monthly_climate(5, hnd, warm).
monthly_climate(5, hun, rain).
monthly_climate(5, isl, rain).
monthly_climate(5, ind, warm).
monthly_climate(5, idn, warm).
monthly_climate(5, irn, warm).
monthly_climate(5, irq, warm).
monthly_climate(5, irl, rain).
monthly_climate(5, isr, warm).
monthly_climate(5, ita, rain).
monthly_climate(5, jpn, rain).
monthly_climate(5, jey, warm).
monthly_climate(5, jor, warm).
monthly_climate(5, kaz, rain).
monthly_climate(5, ken, warm).
monthly_climate(5, kwt, warm).
monthly_climate(5, kgz, rain).
monthly_climate(5, lao, warm).
monthly_climate(5, lva, rain).
monthly_climate(5, lbn, rain).
monthly_climate(5, lso, rain).
monthly_climate(5, lbr, warm).
monthly_climate(5, lby, warm).
monthly_climate(5, lie, rain).
monthly_climate(5, ltu, rain).
monthly_climate(5, lux, rain).
monthly_climate(5, mkd, rain).
monthly_climate(5, mdg, warm).
monthly_climate(5, mwi, rain).
monthly_climate(5, mys, warm).
monthly_climate(5, mdv, warm).
monthly_climate(5, mli, warm).
monthly_climate(5, mlt, rain).
monthly_climate(5, mrt, warm).
monthly_climate(5, mus, warm).
monthly_climate(5, myt, warm).
monthly_climate(5, mex, warm).
monthly_climate(5, mda, rain).
monthly_climate(5, mco, rain).
monthly_climate(5, mng, rain).
monthly_climate(5, mne, rain).
monthly_climate(5, mar, rain).
monthly_climate(5, moz, warm).
monthly_climate(5, mmr, warm).
monthly_climate(5, nam, rain).
monthly_climate(5, npl, warm).
monthly_climate(5, nld, rain).
monthly_climate(5, nic, warm).
monthly_climate(5, ner, warm).
monthly_climate(5, nga, warm).
monthly_climate(5, prk, rain).
monthly_climate(5, nor, rain).
monthly_climate(5, omn, warm).
monthly_climate(5, pak, warm).
monthly_climate(5, pse, warm).
monthly_climate(5, pan, warm).
monthly_climate(5, pry, rain).
monthly_climate(5, per, rain).
monthly_climate(5, phl, warm).
monthly_climate(5, pol, rain).
monthly_climate(5, prt, rain).
monthly_climate(5, qat, warm).
monthly_climate(5, rou, rain).
monthly_climate(5, rus, rain).
monthly_climate(5, rwa, rain).
monthly_climate(5, shn, rain).
monthly_climate(5, smr, rain).
monthly_climate(5, wsm, warm).
monthly_climate(5, stp, warm).
monthly_climate(5, sau, warm).
monthly_climate(5, sen, warm).
monthly_climate(5, srb, rain).
monthly_climate(5, syc, warm).
monthly_climate(5, sle, warm).
monthly_climate(5, sgp, warm).
monthly_climate(5, svk, rain).
monthly_climate(5, svn, rain).
monthly_climate(5, som, warm).
monthly_climate(5, zaf, rain).
monthly_climate(5, kor, rain).
monthly_climate(5, ssd, warm).
monthly_climate(5, esp, rain).
monthly_climate(5, lka, warm).
monthly_climate(5, sdn, warm).
monthly_climate(5, sur, warm).
monthly_climate(5, swz, rain).
monthly_climate(5, swe, rain).
monthly_climate(5, che, rain).
monthly_climate(5, syr, warm).
monthly_climate(5, tjk, rain).
monthly_climate(5, tha, warm).
monthly_climate(5, tls, warm).
monthly_climate(5, tgo, warm).
monthly_climate(5, tun, rain).
monthly_climate(5, tur, rain).
monthly_climate(5, tkm, warm).
monthly_climate(5, uga, warm).
monthly_climate(5, ukr, rain).
monthly_climate(5, are, warm).
monthly_climate(5, gbr, rain).
monthly_climate(5, tza, rain).
monthly_climate(5, usa, rain).
monthly_climate(5, ury, rain).
monthly_climate(5, uzb, warm).
monthly_climate(5, ven, warm).
monthly_climate(5, vnm, warm).
monthly_climate(5, esh, warm).
monthly_climate(5, yem, warm).
monthly_climate(5, zmb, rain).
monthly_climate(5, zwe, rain).
monthly_climate(6, afg, warm).
monthly_climate(6, alb, warm).
monthly_climate(6, dza, warm).
monthly_climate(6, and, rain).
monthly_climate(6, ago, rain).
monthly_climate(6, arg, rain).
monthly_climate(6, arm, rain).
monthly_climate(6, aut, rain).
monthly_climate(6, aze, warm).
monthly_climate(6, bhr, warm).
monthly_climate(6, bgd, warm).
monthly_climate(6, blr, rain).
monthly_climate(6, bel, rain).
monthly_climate(6, blz, warm).
monthly_climate(6, ben, warm).
monthly_climate(6, bmu, warm).
monthly_climate(6, btn, warm).
monthly_climate(6, bol, rain).
monthly_climate(6, bih, rain).
monthly_climate(6, bwa, rain).
monthly_climate(6, bra, warm).
monthly_climate(6, brn, warm).
monthly_climate(6, bgr, rain).
monthly_climate(6, bfa, warm).
monthly_climate(6, bdi, rain).
monthly_climate(6, cpv, warm).
monthly_climate(6, khm, warm).
monthly_climate(6, cmr, warm).
monthly_climate(6, can, rain).
monthly_climate(6, caf, warm).
monthly_climate(6, tcd, warm).
monthly_climate(6, chl, rain).
monthly_climate(6, chn, warm).
monthly_climate(6, col, warm).
monthly_climate(6, com, warm).
monthly_climate(6, cog, warm).
monthly_climate(6, cri, rain).
monthly_climate(6, civ, warm).
monthly_climate(6, hrv, rain).
monthly_climate(6, cyp, warm).
monthly_climate(6, cze, rain).
monthly_climate(6, cod, warm).
monthly_climate(6, dnk, rain).
monthly_climate(6, dji, warm).
monthly_climate(6, ecu, rain).
monthly_climate(6, egy, warm).
monthly_climate(6, slv, warm).
monthly_climate(6, gnq, warm).
monthly_climate(6, eri, warm).
monthly_climate(6, est, rain).
monthly_climate(6, eth, warm).
monthly_climate(6, fin, rain).
monthly_climate(6, fra, rain).
monthly_climate(6, gab, warm).
monthly_climate(6, gmb, warm).
monthly_climate(6, geo, warm).
monthly_climate(6, deu, rain).
monthly_climate(6, gha, warm).
monthly_climate(6, gib, warm).
monthly_climate(6, grc, warm).
monthly_climate(6, grl, warm).
monthly_climate(6, gtm, warm).
monthly_climate(6, ggy, warm).
monthly_climate(6, gnb, warm).
monthly_climate(6, gin, warm).
monthly_climate(6, guy, warm).
monthly_climate(6, hnd, warm).
monthly_climate(6, hun, rain).
monthly_climate(6, isl, rain).
monthly_climate(6, ind, warm).
monthly_climate(6, idn, warm).
monthly_climate(6, irn, warm).
monthly_climate(6, irq, warm).
monthly_climate(6, irl, rain).
monthly_climate(6, isr, warm).
monthly_climate(6, ita, rain).
monthly_climate(6, jpn, warm).
monthly_climate(6, jey, warm).
monthly_climate(6, jor, warm).
monthly_climate(6, kaz, warm).
monthly_climate(6, ken, rain).
monthly_climate(6, kwt, warm).
monthly_climate(6, kgz, rain).
monthly_climate(6, lao, warm).
monthly_climate(6, lva, rain).
monthly_climate(6, lbn, warm).
monthly_climate(6, lso, rain).
monthly_climate(6, lbr, warm).
monthly_climate(6, lby, warm).
monthly_climate(6, lie, rain).
monthly_climate(6, ltu, rain).
monthly_climate(6, lux, rain).
monthly_climate(6, mkd, rain).
monthly_climate(6, mdg, rain).
monthly_climate(6, mwi, rain).
monthly_climate(6, mys, warm).
monthly_climate(6, mdv, warm).
monthly_climate(6, mli, warm).
monthly_climate(6, mlt, warm).
monthly_climate(6, mrt, warm).
monthly_climate(6, mus, warm).
monthly_climate(6, myt, warm).
monthly_climate(6, mex, warm).
monthly_climate(6, mda, rain).
monthly_climate(6, mco, rain).
monthly_climate(6, mng, rain).
monthly_climate(6, mne, rain).
monthly_climate(6, mar, warm).
monthly_climate(6, moz, warm).
monthly_climate(6, mmr, warm).
monthly_climate(6, nam, rain).
monthly_climate(6, npl, warm).
monthly_climate(6, nld, rain).
monthly_climate(6, nic, warm).
monthly_climate(6, ner, warm).
monthly_climate(6, nga, warm).
monthly_climate(6, prk, rain).
monthly_climate(6, nor, rain).
monthly_climate(6, omn, warm).
monthly_climate(6, pak, warm).
monthly_climate(6, pse, warm).
monthly_climate(6, pan, warm).
monthly_climate(6, pry, rain).
monthly_climate(6, per, rain).
monthly_climate(6, phl, warm).
monthly_climate(6, pol, rain).
monthly_climate(6, prt, rain).
monthly_climate(6, qat, warm).
monthly_climate(6, rou, rain).
monthly_climate(6, rus, rain).
monthly_climate(6, rwa, rain).
monthly_climate(6, shn, rain).
monthly_climate(6, smr, rain).
monthly_climate(6, wsm, warm).
monthly_climate(6, stp, warm).
monthly_climate(6, sau, warm).
monthly_climate(6, sen, warm).
monthly_climate(6, srb, rain).
monthly_climate(6, syc, warm).
monthly_climate(6, sle, warm).
monthly_climate(6, sgp, warm).
monthly_climate(6, svk, rain).
monthly_climate(6, svn, rain).
monthly_climate(6, som, warm).
monthly_climate(6, zaf, rain).
monthly_climate(6, kor, warm).
monthly_climate(6, ssd, warm).
monthly_climate(6, esp, rain).
monthly_climate(6, lka, warm).
monthly_climate(6, sdn, warm).
monthly_climate(6, sur, warm).
monthly_climate(6, swz, rain).
monthly_climate(6, swe, rain).
monthly_climate(6, che, rain).
monthly_climate(6, syr, warm).
monthly_climate(6, tjk, warm).
monthly_climate(6, tha, warm).
monthly_climate(6, tls, warm).
monthly_climate(6, tgo, warm).
monthly_climate(6, tun, warm).
monthly_climate(6, tur, rain).
monthly_climate(6, tkm, warm).
monthly_climate(6, uga, warm).
monthly_climate(6, ukr, rain).
monthly_climate(6, are, warm).
monthly_climate(6, gbr, rain).
monthly_climate(6, tza, rain).
monthly_climate(6, usa, warm).
monthly_climate(6, ury, rain).
monthly_climate(6, uzb, warm).
monthly_climate(6, ven, warm).
monthly_climate(6, vnm, warm).
monthly_climate(6, esh, warm).
monthly_climate(6, yem, warm).
monthly_climate(6, zmb, rain).
monthly_climate(6, zwe, rain).
monthly_climate(7, afg, warm).
monthly_climate(7, alb, warm).
monthly_climate(7, dza, warm).
monthly_climate(7, and, rain).
monthly_climate(7, ago, rain).
monthly_climate(7, arg, rain).
monthly_climate(7, arm, rain).
monthly_climate(7, aut, rain).
monthly_climate(7, aze, warm).
monthly_climate(7, bhr, warm).
monthly_climate(7, bgd, warm).
monthly_climate(7, blr, rain).
monthly_climate(7, bel, rain).
monthly_climate(7, blz, warm).
monthly_climate(7, ben, warm).
monthly_climate(7, bmu, warm).
monthly_climate(7, btn, rain).
monthly_climate(7, bol, rain).
monthly_climate(7, bih, rain).
monthly_climate(7, bwa, rain).
monthly_climate(7, bra, warm).
monthly_climate(7, brn, warm).
monthly_climate(7, bgr, rain).
monthly_climate(7, bfa, warm).
monthly_climate(7, bdi, rain).
monthly_climate(7, cpv, warm).
monthly_climate(7, khm, warm).
monthly_climate(7, cmr, warm).
monthly_climate(7, can, rain).
monthly_climate(7, caf, warm).
monthly_climate(7, tcd, warm).
monthly_climate(7, chl, rain).
monthly_climate(7, chn, warm).
monthly_climate(7, col, warm).
monthly_climate(7, com, warm).
monthly_climate(7, cog, warm).
monthly_climate(7, cri, warm).
monthly_climate(7, civ, warm).
monthly_climate(7, hrv, warm).
monthly_climate(7, cyp, warm).
monthly_climate(7, cze, rain).
monthly_climate(7, cod, warm).
monthly_climate(7, dnk, rain).
monthly_climate(7, dji, warm).
monthly_climate(7, ecu, rain).
monthly_climate(7, egy, warm).
monthly_climate(7, slv, warm).
monthly_climate(7, gnq, warm).
monthly_climate(7, eri, warm).
monthly_climate(7, est, rain).
monthly_climate(7, eth, rain).
monthly_climate(7, fin, rain).
monthly_climate(7, fra, rain).
monthly_climate(7, gab, warm).
monthly_climate(7, gmb, warm).
monthly_climate(7, geo, warm).
monthly_climate(7, deu, rain).
monthly_climate(7, gha, warm).
monthly_climate(7, gib, warm).
monthly_climate(7, grc, warm).
monthly_climate(7, grl, warm).
monthly_climate(7, gtm, warm).
monthly_climate(7, ggy, warm).
monthly_climate(7, gnb, warm).
monthly_climate(7, gin, warm).
monthly_climate(7, guy, warm).
monthly_climate(7, hnd, warm).
monthly_climate(7, hun, warm).
monthly_climate(7, isl, rain).
monthly_climate(7, ind, warm).
monthly_climate(7, idn, warm).
monthly_climate(7, irn, warm).
monthly_climate(7, irq, warm).
monthly_climate(7, irl, rain).
monthly_climate(7, isr, warm).
monthly_climate(7, ita, warm).
monthly_climate(7, jpn, warm).
monthly_climate(7, jey, warm).
monthly_climate(7, jor, warm).
monthly_climate(7, kaz, warm).
monthly_climate(7, ken, rain).
monthly_climate(7, kwt, warm).
monthly_climate(7, kgz, warm).
monthly_climate(7, lao, warm).
monthly_climate(7, lva, rain).
monthly_climate(7, lbn, warm).
monthly_climate(7, lso, rain).
monthly_climate(7, lbr, warm).
monthly_climate(7, lby, warm).
monthly_climate(7, lie, rain).
monthly_climate(7, ltu, rain).
monthly_climate(7, lux, rain).
monthly_climate(7, mkd, warm).
monthly_climate(7, mdg, rain).
monthly_climate(7, mwi, rain).
monthly_climate(7, mys, warm).
monthly_climate(7, mdv, warm).
monthly_climate(7, mli, warm).
monthly_climate(7, mlt, warm).
monthly_climate(7, mrt, warm).
monthly_climate(7, mus, warm).
monthly_climate(7, myt, warm).
monthly_climate(7, mex, warm).
monthly_climate(7, mda, warm).
monthly_climate(7, mco, rain).
monthly_climate(7, mng, rain).
monthly_climate(7, mne, warm).
monthly_climate(7, mar, warm).
monthly_climate(7, moz, rain).
monthly_climate(7, mmr, warm).
monthly_climate(7, nam, rain).
monthly_climate(7, npl, warm).
monthly_climate(7, nld, rain).
monthly_climate(7, nic, warm).
monthly_climate(7, ner, warm).
monthly_climate(7, nga, warm).
monthly_climate(7, prk, warm).
monthly_climate(7, nor, rain).
monthly_climate(7, omn, warm).
monthly_climate(7, pak, warm).
monthly_climate(7, pse, warm).
monthly_climate(7, pan, warm).
monthly_climate(7, pry, rain).
monthly_climate(7, per, rain).
monthly_climate(7, phl, warm).
monthly_climate(7, pol, rain).
monthly_climate(7, prt, warm).
monthly_climate(7, qat, warm).
monthly_climate(7, rou, rain).
monthly_climate(7, rus, rain).
monthly_climate(7, rwa, rain).
monthly_climate(7, shn, rain).
monthly_climate(7, smr, rain).
monthly_climate(7, wsm, warm).
monthly_climate(7, stp, warm).
monthly_climate(7, sau, warm).
monthly_climate(7, sen, warm).
monthly_climate(7, srb, warm).
monthly_climate(7, syc, warm).
monthly_climate(7, sle, warm).
monthly_climate(7, sgp, warm).
monthly_climate(7, svk, rain).
monthly_climate(7, svn, rain).
monthly_climate(7, som, warm).
monthly_climate(7, zaf, rain).
monthly_climate(7, kor, warm).
monthly_climate(7, ssd, warm).
monthly_climate(7, esp, warm).
monthly_climate(7, lka, warm).
monthly_climate(7, sdn, warm).
monthly_climate(7, sur, warm).
monthly_climate(7, swz, rain).
monthly_climate(7, swe, rain).
monthly_climate(7, che, rain).
monthly_climate(7, syr, warm).
monthly_climate(7, tjk, warm).
monthly_climate(7, tha, warm).
monthly_climate(7, tls, warm).
monthly_climate(7, tgo, warm).
monthly_climate(7, tun, warm).
monthly_climate(7, tur, warm).
monthly_climate(7, tkm, warm).
monthly_climate(7, uga, warm).
monthly_climate(7, ukr, warm).
monthly_climate(7, are, warm).
monthly_climate(7, gbr, rain).
monthly_climate(7, tza, rain).
monthly_climate(7, usa, warm).
monthly_climate(7, ury, rain).
monthly_climate(7, uzb, warm).
monthly_climate(7, ven, warm).
monthly_climate(7, vnm, warm).
monthly_climate(7, esh, warm).
monthly_climate(7, yem, warm).
monthly_climate(7, zmb, rain).
monthly_climate(7, zwe, rain).
monthly_climate(8, afg, warm).
monthly_climate(8, alb, warm).
monthly_climate(8, dza, warm).
monthly_climate(8, and, rain).
monthly_climate(8, ago, rain).
monthly_climate(8, arg, rain).
monthly_climate(8, arm, rain).
monthly_climate(8, aut, rain).
monthly_climate(8, aze, warm).
monthly_climate(8, bhr, warm).
monthly_climate(8, bgd, warm).
monthly_climate(8, blr, rain).
monthly_climate(8, bel, rain).
monthly_climate(8, blz, warm).
monthly_climate(8, ben, warm).
monthly_climate(8, bmu, warm).
monthly_climate(8, btn, warm).
monthly_climate(8, bol, rain).
monthly_climate(8, bih, rain).
monthly_climate(8, bwa, rain).
monthly_climate(8, bra, warm).
monthly_climate(8, brn, warm).
monthly_climate(8, bgr, rain).
monthly_climate(8, bfa, warm).
monthly_climate(8, bdi, warm).
monthly_climate(8, cpv, warm).
monthly_climate(8, khm, warm).
monthly_climate(8, cmr, warm).
monthly_climate(8, can, rain).
monthly_climate(8, caf, warm).
monthly_climate(8, tcd, warm).
monthly_climate(8, chl, rain).
monthly_climate(8, chn, warm).
monthly_climate(8, col, warm).
monthly_climate(8, com, warm).
monthly_climate(8, cog, warm).
monthly_climate(8, cri, warm).
monthly_climate(8, civ, warm).
monthly_climate(8, hrv, warm).
monthly_climate(8, cyp, warm).
monthly_climate(8, cze, rain).
monthly_climate(8, cod, warm).
monthly_climate(8, dnk, rain).
monthly_climate(8, dji, warm).
monthly_climate(8, ecu, rain).
monthly_climate(8, egy, warm).
monthly_climate(8, slv, warm).
monthly_climate(8, gnq, warm).
monthly_climate(8, eri, warm).
monthly_climate(8, est, rain).
monthly_climate(8, eth, rain).
monthly_climate(8, fin, rain).
monthly_climate(8, fra, rain).
monthly_climate(8, gab, warm).
monthly_climate(8, gmb, warm).
monthly_climate(8, geo, warm).
monthly_climate(8, deu, rain).
monthly_climate(8, gha, warm).
monthly_climate(8, gib, warm).
monthly_climate(8, grc, warm).
monthly_climate(8, grl, warm).
monthly_climate(8, gtm, warm).
monthly_climate(8, ggy, warm).
monthly_climate(8, gnb, warm).
monthly_climate(8, gin, warm).
monthly_climate(8, guy, warm).
monthly_climate(8, hnd, warm).
monthly_climate(8, hun, rain).
monthly_climate(8, isl, rain).
monthly_climate(8, ind, warm).
monthly_climate(8, idn, warm).
monthly_climate(8, irn, warm).
monthly_climate(8, irq, warm).
monthly_climate(8, irl, rain).
monthly_climate(8, isr, warm).
monthly_climate(8, ita, warm).
monthly_climate(8, jpn, warm).
monthly_climate(8, jey, warm).
monthly_climate(8, jor, warm).
monthly_climate(8, kaz, warm).
monthly_climate(8, ken, rain).
monthly_climate(8, kwt, warm).
monthly_climate(8, kgz, warm).
monthly_climate(8, lao, warm).
monthly_climate(8, lva, rain).
monthly_climate(8, lbn, warm).
monthly_climate(8, lso, rain).
monthly_climate(8, lbr, warm).
monthly_climate(8, lby, warm).
monthly_climate(8, lie, rain).
monthly_climate(8, ltu, rain).
monthly_climate(8, lux, rain).
monthly_climate(8, mkd, warm).
monthly_climate(8, mdg, rain).
monthly_climate(8, mwi, rain).
monthly_climate(8, mys, warm).
monthly_climate(8, mdv, warm).
monthly_climate(8, mli, warm).
monthly_climate(8, mlt, warm).
monthly_climate(8, mrt, warm).
monthly_climate(8, mus, warm).
monthly_climate(8, myt, warm).
monthly_climate(8, mex, warm).
monthly_climate(8, mda, warm).
monthly_climate(8, mco, warm).
monthly_climate(8, mng, rain).
monthly_climate(8, mne, warm).
monthly_climate(8, mar, warm).
monthly_climate(8, moz, warm).
monthly_climate(8, mmr, warm).
monthly_climate(8, nam, rain).
monthly_climate(8, npl, warm).
monthly_climate(8, nld, rain).
monthly_climate(8, nic, warm).
monthly_climate(8, ner, warm).
monthly_climate(8, nga, warm).
monthly_climate(8, prk, warm).
monthly_climate(8, nor, rain).
monthly_climate(8, omn, warm).
monthly_climate(8, pak, warm).
monthly_climate(8, pse, warm).
monthly_climate(8, pan, warm).
monthly_climate(8, pry, rain).
monthly_climate(8, per, rain).
monthly_climate(8, phl, warm).
monthly_climate(8, pol, rain).
monthly_climate(8, prt, warm).
monthly_climate(8, qat, warm).
monthly_climate(8, rou, rain).
monthly_climate(8, rus, rain).
monthly_climate(8, rwa, rain).
monthly_climate(8, shn, rain).
monthly_climate(8, smr, warm).
monthly_climate(8, wsm, warm).
monthly_climate(8, stp, warm).
monthly_climate(8, sau, warm).
monthly_climate(8, sen, warm).
monthly_climate(8, srb, warm).
monthly_climate(8, syc, warm).
monthly_climate(8, sle, warm).
monthly_climate(8, sgp, warm).
monthly_climate(8, svk, rain).
monthly_climate(8, svn, rain).
monthly_climate(8, som, warm).
monthly_climate(8, zaf, rain).
monthly_climate(8, kor, warm).
monthly_climate(8, ssd, warm).
monthly_climate(8, esp, warm).
monthly_climate(8, lka, warm).
monthly_climate(8, sdn, warm).
monthly_climate(8, sur, warm).
monthly_climate(8, swz, rain).
monthly_climate(8, swe, rain).
monthly_climate(8, che, rain).
monthly_climate(8, syr, warm).
monthly_climate(8, tjk, warm).
monthly_climate(8, tha, warm).
monthly_climate(8, tls, warm).
monthly_climate(8, tgo, warm).
monthly_climate(8, tun, warm).
monthly_climate(8, tur, warm).
monthly_climate(8, tkm, warm).
monthly_climate(8, uga, warm).
monthly_climate(8, ukr, rain).
monthly_climate(8, are, warm).
monthly_climate(8, gbr, rain).
monthly_climate(8, tza, rain).
monthly_climate(8, usa, warm).
monthly_climate(8, ury, rain).
monthly_climate(8, uzb, warm).
monthly_climate(8, ven, warm).
monthly_climate(8, vnm, warm).
monthly_climate(8, esh, warm).
monthly_climate(8, yem, warm).
monthly_climate(8, zmb, rain).
monthly_climate(8, zwe, rain).
monthly_climate(9, afg, warm).
monthly_climate(9, alb, rain).
monthly_climate(9, dza, warm).
monthly_climate(9, and, rain).
monthly_climate(9, ago, warm).
monthly_climate(9, arg, rain).
monthly_climate(9, arm, rain).
monthly_climate(9, aut, rain).
monthly_climate(9, aze, warm).
monthly_climate(9, bhr, warm).
monthly_climate(9, bgd, warm).
monthly_climate(9, blr, rain).
monthly_climate(9, bel, rain).
monthly_climate(9, blz, warm).
monthly_climate(9, ben, warm).
monthly_climate(9, bmu, warm).
monthly_climate(9, btn, warm).
monthly_climate(9, bol, rain).
monthly_climate(9, bih, rain).
monthly_climate(9, bwa, warm).
monthly_climate(9, bra, warm).
monthly_climate(9, brn, warm).
monthly_climate(9, bgr, rain).
monthly_climate(9, bfa, warm).
monthly_climate(9, bdi, warm).
monthly_climate(9, cpv, warm).
monthly_climate(9, khm, warm).
monthly_climate(9, cmr, warm).
monthly_climate(9, can, rain).
monthly_climate(9, caf, warm).
monthly_climate(9, tcd, warm).
monthly_climate(9, chl, rain).
monthly_climate(9, chn, warm).
monthly_climate(9, col, warm).
monthly_climate(9, com, warm).
monthly_climate(9, cog, warm).
monthly_climate(9, cri, rain).
monthly_climate(9, civ, warm).
monthly_climate(9, hrv, rain).
monthly_climate(9, cyp, warm).
monthly_climate(9, cze, rain).
monthly_climate(9, cod, warm).
monthly_climate(9, dnk, rain).
monthly_climate(9, dji, warm).
monthly_climate(9, ecu, rain).
monthly_climate(9, egy, warm).
monthly_climate(9, slv, warm).
monthly_climate(9, gnq, warm).
monthly_climate(9, eri, warm).
monthly_climate(9, est, rain).
monthly_climate(9, eth, rain).
monthly_climate(9, fin, rain).
monthly_climate(9, fra, rain).
monthly_climate(9, gab, warm).
monthly_climate(9, gmb, warm).
monthly_climate(9, geo, rain).
monthly_climate(9, deu, rain).
monthly_climate(9, gha, warm).
monthly_climate(9, gib, warm).
monthly_climate(9, grc, warm).
monthly_climate(9, grl, warm).
monthly_climate(9, gtm, warm).
monthly_climate(9, ggy, warm).
monthly_climate(9, gnb, warm).
monthly_climate(9, gin, warm).
monthly_climate(9, guy, warm).
monthly_climate(9, hnd, warm).
monthly_climate(9, hun, rain).
monthly_climate(9, isl, rain).
monthly_climate(9, ind, warm).
monthly_climate(9, idn, warm).
monthly_climate(9, irn, warm).
monthly_climate(9, irq, warm).
monthly_climate(9, irl, rain).
monthly_climate(9, isr, warm).
monthly_climate(9, ita, rain).
monthly_climate(9, jpn, warm).
monthly_climate(9, jey, warm).
monthly_climate(9, jor, warm).
monthly_climate(9, kaz, rain).
monthly_climate(9, ken, warm).
monthly_climate(9, kwt, warm).
monthly_climate(9, kgz, rain).
monthly_climate(9, lao, warm).
monthly_climate(9, lva, rain).
monthly_climate(9, lbn, warm).
monthly_climate(9, lso, rain).
monthly_climate(9, lbr, warm).
monthly_climate(9, lby, warm).
monthly_climate(9, lie, rain).
monthly_climate(9, ltu, rain).
monthly_climate(9, lux, rain).
monthly_climate(9, mkd, rain).
monthly_climate(9, mdg, warm).
monthly_climate(9, mwi, warm).
monthly_climate(9, mys, warm).
monthly_climate(9, mdv, warm).
monthly_climate(9, mli, warm).
monthly_climate(9, mlt, warm).
monthly_climate(9, mrt, warm).
monthly_climate(9, mus, warm).
monthly_climate(9, myt, warm).
monthly_climate(9, mex, warm).
monthly_climate(9, mda, rain).
monthly_climate(9, mco, warm).
monthly_climate(9, mng, rain).
monthly_climate(9, mne, rain).
monthly_climate(9, mar, warm).
monthly_climate(9, moz, warm).
monthly_climate(9, mmr, warm).
monthly_climate(9, nam, rain).
monthly_climate(9, npl, warm).
monthly_climate(9, nld, rain).
monthly_climate(9, nic, warm).
monthly_climate(9, ner, warm).
monthly_climate(9, nga, warm).
monthly_climate(9, prk, rain).
monthly_climate(9, nor, rain).
monthly_climate(9, omn, warm).
monthly_climate(9, pak, warm).
monthly_climate(9, pse, warm).
monthly_climate(9, pan, warm).
monthly_climate(9, pry, warm).
monthly_climate(9, per, rain).
monthly_climate(9, phl, warm).
monthly_climate(9, pol, rain).
monthly_climate(9, prt, warm).
monthly_climate(9, qat, warm).
monthly_climate(9, rou, rain).
monthly_climate(9, rus, rain).
monthly_climate(9, rwa, rain).
monthly_climate(9, shn, rain).
monthly_climate(9, smr, warm).
monthly_climate(9, wsm, warm).
monthly_climate(9, stp, warm).
monthly_climate(9, sau, warm).
monthly_climate(9, sen, warm).
monthly_climate(9, srb, rain).
monthly_climate(9, syc, warm).
monthly_climate(9, sle, warm).
monthly_climate(9, sgp, warm).
monthly_climate(9, svk, rain).
monthly_climate(9, svn, rain).
monthly_climate(9, som, warm).
monthly_climate(9, zaf, rain).
monthly_climate(9, kor, warm).
monthly_climate(9, ssd, warm).
monthly_climate(9, esp, warm).
monthly_climate(9, lka, warm).
monthly_climate(9, sdn, warm).
monthly_climate(9, sur, warm).
monthly_climate(9, swz, rain).
monthly_climate(9, swe, rain).
monthly_climate(9, che, rain).
monthly_climate(9, syr, warm).
monthly_climate(9, tjk, rain).
monthly_climate(9, tha, warm).
monthly_climate(9, tls, warm).
monthly_climate(9, tgo, warm).
monthly_climate(9, tun, warm).
monthly_climate(9, tur, rain).
monthly_climate(9, tkm, warm).
monthly_climate(9, uga, warm).
monthly_climate(9, ukr, rain).
monthly_climate(9, are, warm).
monthly_climate(9, gbr, rain).
monthly_climate(9, tza, rain).
monthly_climate(9, usa, rain).
monthly_climate(9, ury, rain).
monthly_climate(9, uzb, warm).
monthly_climate(9, ven, warm).
monthly_climate(9, vnm, warm).
monthly_climate(9, esh, warm).
monthly_climate(9, yem, warm).
monthly_climate(9, zmb, warm).
monthly_climate(9, zwe, warm).
monthly_climate(10, afg, rain).
monthly_climate(10, alb, rain).
monthly_climate(10, dza, rain).
monthly_climate(10, and, rain).
monthly_climate(10, ago, warm).
monthly_climate(10, arg, rain).
monthly_climate(10, arm, rain).
monthly_climate(10, aut, rain).
monthly_climate(10, aze, rain).
monthly_climate(10, bhr, warm).
monthly_climate(10, bgd, warm).
monthly_climate(10, blr, rain).
monthly_climate(10, bel, rain).
monthly_climate(10, blz, warm).
monthly_climate(10, ben, warm).
monthly_climate(10, bmu, warm).
monthly_climate(10, btn, rain).
monthly_climate(10, bol, rain).
monthly_climate(10, bih, rain).
monthly_climate(10, bwa, warm).
monthly_climate(10, bra, warm).
monthly_climate(10, brn, warm).
monthly_climate(10, bgr, rain).
monthly_climate(10, bfa, warm).
monthly_climate(10, bdi, warm).
monthly_climate(10, cpv, warm).
monthly_climate(10, khm, warm).
monthly_climate(10, cmr, warm).
monthly_climate(10, can, rain).
monthly_climate(10, caf, warm).
monthly_climate(10, tcd, warm).
monthly_climate(10, chl, rain).
monthly_climate(10, chn, rain).
monthly_climate(10, col, warm).
monthly_climate(10, com, warm).
monthly_climate(10, cog, warm).
monthly_climate(10, cri, rain).
monthly_climate(10, civ, warm).
monthly_climate(10, hrv, rain).
monthly_climate(10, cyp, warm).
monthly_climate(10, cze, rain).
monthly_climate(10, cod, warm).
monthly_climate(10, dnk, rain).
monthly_climate(10, dji, warm).
monthly_climate(10, ecu, rain).
monthly_climate(10, egy, warm).
monthly_climate(10, slv, warm).
monthly_climate(10, gnq, warm).
monthly_climate(10, eri, warm).
monthly_climate(10, est, rain).
monthly_climate(10, eth, rain).
monthly_climate(10, fin, rain).
monthly_climate(10, fra, rain).
monthly_climate(10, gab, warm).
monthly_climate(10, gmb, warm).
monthly_climate(10, geo, rain).
monthly_climate(10, deu, rain).
monthly_climate(10, gha, warm).
monthly_climate(10, gib, rain).
monthly_climate(10, grc, rain).
monthly_climate(10, grl, warm).
monthly_climate(10, gtm, warm).
monthly_climate(10, ggy, warm).
monthly_climate(10, gnb, warm).
monthly_climate(10, gin, warm).
monthly_climate(10, guy, warm).
monthly_climate(10, hnd, warm).
monthly_climate(10, hun, rain).
monthly_climate(10, isl, rain).
monthly_climate(10, ind, warm).
monthly_climate(10, idn, warm).
monthly_climate(10, irn, rain).
monthly_climate(10, irq, warm).
monthly_climate(10, irl, rain).
monthly_climate(10, isr, warm).
monthly_climate(10, ita, rain).
monthly_climate(10, jpn, rain).
monthly_climate(10, jey, warm).
monthly_climate(10, jor, warm).
monthly_climate(10, kaz, rain).
monthly_climate(10, ken, warm).
monthly_climate(10, kwt, warm).
monthly_climate(10, kgz, rain).
monthly_climate(10, lao, warm).
monthly_climate(10, lva, rain).
monthly_climate(10, lbn, rain).
monthly_climate(10, lso, rain).
monthly_climate(10, lbr, warm).
monthly_climate(10, lby, warm).
monthly_climate(10, lie, rain).
monthly_climate(10, ltu, rain).
monthly_climate(10, lux, rain).
monthly_climate(10, mkd, rain).
monthly_climate(10, mdg, warm).
monthly_climate(10, mwi, warm).
monthly_climate(10, mys, warm).
monthly_climate(10, mdv, warm).
monthly_climate(10, mli, warm).
monthly_climate(10, mlt, warm).
monthly_climate(10, mrt, warm).
monthly_climate(10, mus, warm).
monthly_climate(10, myt, warm).
monthly_climate(10, mex, warm).
monthly_climate(10, mda, rain).
monthly_climate(10, mco, warm).
monthly_climate(10, mng, rain).
monthly_climate(10, mne, rain).
monthly_climate(10, mar, rain).
monthly_climate(10, moz, warm).
monthly_climate(10, mmr, warm).
monthly_climate(10, nam, warm).
monthly_climate(10, npl, rain).
monthly_climate(10, nld, rain).
monthly_climate(10, nic, warm).
monthly_climate(10, ner, warm).
monthly_climate(10, nga, warm).
monthly_climate(10, prk, rain).
monthly_climate(10, nor, rain).
monthly_climate(10, omn, warm).
monthly_climate(10, pak, warm).
monthly_climate(10, pse, warm).
monthly_climate(10, pan, warm).
monthly_climate(10, pry, warm).
monthly_climate(10, per, rain).
monthly_climate(10, phl, warm).
monthly_climate(10, pol, rain).
monthly_climate(10, prt, rain).
monthly_climate(10, qat, warm).
monthly_climate(10, rou, rain).
monthly_climate(10, rus, rain).
monthly_climate(10, rwa, rain).
monthly_climate(10, shn, rain).
monthly_climate(10, smr, rain).
monthly_climate(10, wsm, warm).
monthly_climate(10, stp, warm).
monthly_climate(10, sau, warm).
monthly_climate(10, sen, warm).
monthly_climate(10, srb, rain).
monthly_climate(10, syc, warm).
monthly_climate(10, sle, warm).
monthly_climate(10, sgp, warm).
monthly_climate(10, svk, rain).
monthly_climate(10, svn, rain).
monthly_climate(10, som, warm).
monthly_climate(10, zaf, rain).
monthly_climate(10, kor, rain).
monthly_climate(10, ssd, warm).
monthly_climate(10, esp, rain).
monthly_climate(10, lka, warm).
monthly_climate(10, sdn, warm).
monthly_climate(10, sur, warm).
monthly_climate(10, swz, rain).
monthly_climate(10, swe, rain).
monthly_climate(10, che, rain).
monthly_climate(10, syr, warm).
monthly_climate(10, tjk, rain).
monthly_climate(10, tha, warm).
monthly_climate(10, tls, warm).
monthly_climate(10, tgo, warm).
monthly_climate(10, tun, warm).
monthly_climate(10, tur, rain).
monthly_climate(10, tkm, rain).
monthly_climate(10, uga, warm).
monthly_climate(10, ukr, rain).
monthly_climate(10, are, warm).
monthly_climate(10, gbr, rain).
monthly_climate(10, tza, rain).
monthly_climate(10, usa, rain).
monthly_climate(10, ury, rain).
monthly_climate(10, uzb, rain).
monthly_climate(10, ven, warm).
monthly_climate(10, vnm, warm).
monthly_climate(10, esh, warm).
monthly_climate(10, yem, warm).
monthly_climate(10, zmb, warm).
monthly_climate(10, zwe, warm).
monthly_climate(11, afg, rain).
monthly_climate(11, alb, rain).
monthly_climate(11, dza, rain).
monthly_climate(11, and, rain).
monthly_climate(11, ago, warm).
monthly_climate(11, arg, warm).
monthly_climate(11, arm, rain).
monthly_climate(11, aut, rain).
monthly_climate(11, aze, rain).
monthly_climate(11, bhr, warm).
monthly_climate(11, bgd, warm).
monthly_climate(11, blr, rain).
monthly_climate(11, bel, rain).
monthly_climate(11, blz, warm).
monthly_climate(11, ben, warm).
monthly_climate(11, bmu, warm).
monthly_climate(11, btn, rain).
monthly_climate(11, bol, rain).
monthly_climate(11, bih, rain).
monthly_climate(11, bwa, warm).
monthly_climate(11, bra, warm).
monthly_climate(11, brn, warm).
monthly_climate(11, bgr, rain).
monthly_climate(11, bfa, warm).
monthly_climate(11, bdi, rain).
monthly_climate(11, cpv, warm).
monthly_climate(11, khm, warm).
monthly_climate(11, cmr, warm).
monthly_climate(11, can, snow).
monthly_climate(11, caf, warm).
monthly_climate(11, tcd, warm).
monthly_climate(11, chl, rain).
monthly_climate(11, chn, rain).
monthly_climate(11, col, warm).
monthly_climate(11, com, warm).
monthly_climate(11, cog, warm).
monthly_climate(11, cri, rain).
monthly_climate(11, civ, warm).
monthly_climate(11, hrv, rain).
monthly_climate(11, cyp, rain).
monthly_climate(11, cze, rain).
monthly_climate(11, cod, warm).
monthly_climate(11, dnk, rain).
monthly_climate(11, dji, warm).
monthly_climate(11, ecu, rain).
monthly_climate(11, egy, rain).
monthly_climate(11, slv, warm).
monthly_climate(11, gnq, warm).
monthly_climate(11, eri, warm).
monthly_climate(11, est, rain).
monthly_climate(11, eth, rain).
monthly_climate(11, fin, snow).
monthly_climate(11, fra, rain).
monthly_climate(11, gab, warm).
monthly_climate(11, gmb, warm).
monthly_climate(11, geo, rain).
monthly_climate(11, deu, rain).
monthly_climate(11, gha, warm).
monthly_climate(11, gib, rain).
monthly_climate(11, grc, rain).
monthly_climate(11, grl, warm).
monthly_climate(11, gtm, warm).
monthly_climate(11, ggy, warm).
monthly_climate(11, gnb, warm).
monthly_climate(11, gin, warm).
monthly_climate(11, guy, warm).
monthly_climate(11, hnd, warm).
monthly_climate(11, hun, rain).
monthly_climate(11, isl, rain).
monthly_climate(11, ind, warm).
monthly_climate(11, idn, warm).
monthly_climate(11, irn, rain).
monthly_climate(11, irq, rain).
monthly_climate(11, irl, rain).
monthly_climate(11, isr, rain).
monthly_climate(11, ita, rain).
monthly_climate(11, jpn, rain).
monthly_climate(11, jey, warm).
monthly_climate(11, jor, rain).
monthly_climate(11, kaz, snow).
monthly_climate(11, ken, warm).
monthly_climate(11, kwt, warm).
monthly_climate(11, kgz, rain).
monthly_climate(11, lao, warm).
monthly_climate(11, lva, rain).
monthly_climate(11, lbn, rain).
monthly_climate(11, lso, rain).
monthly_climate(11, lbr, warm).
monthly_climate(11, lby, rain).
monthly_climate(11, lie, rain).
monthly_climate(11, ltu, rain).
monthly_climate(11, lux, rain).
monthly_climate(11, mkd, rain).
monthly_climate(11, mdg, warm).
monthly_climate(11, mwi, warm).
monthly_climate(11, mys, warm).
monthly_climate(11, mdv, warm).
monthly_climate(11, mli, warm).
monthly_climate(11, mlt, rain).
monthly_climate(11, mrt, warm).
monthly_climate(11, mus, warm).
monthly_climate(11, myt, warm).
monthly_climate(11, mex, rain).
monthly_climate(11, mda, rain).
monthly_climate(11, mco, rain).
monthly_climate(11, mng, snow).
monthly_climate(11, mne, rain).
monthly_climate(11, mar, rain).
monthly_climate(11, moz, warm).
monthly_climate(11, mmr, warm).
monthly_climate(11, nam, warm).
monthly_climate(11, npl, rain).
monthly_climate(11, nld, rain).
monthly_climate(11, nic, warm).
monthly_climate(11, ner, warm).
monthly_climate(11, nga, warm).
monthly_climate(11, prk, rain).
monthly_climate(11, nor, rain).
monthly_climate(11, omn, warm).
monthly_climate(11, pak, rain).
monthly_climate(11, pse, warm).
monthly_climate(11, pan, warm).
monthly_climate(11, pry, warm).
monthly_climate(11, per, rain).
monthly_climate(11, phl, warm).
monthly_climate(11, pol, rain).
monthly_climate(11, prt, rain).
monthly_climate(11, qat, warm).
monthly_climate(11, rou, rain).
monthly_climate(11, rus, snow).
monthly_climate(11, rwa, rain).
monthly_climate(11, shn, rain).
monthly_climate(11, smr, rain).
monthly_climate(11, wsm, warm).
monthly_climate(11, stp, warm).
monthly_climate(11, sau, warm).
monthly_climate(11, sen, warm).
monthly_climate(11, srb, rain).
monthly_climate(11, syc, warm).
monthly_climate(11, sle, warm).
monthly_climate(11, sgp, warm).
monthly_climate(11, svk, rain).
monthly_climate(11, svn, rain).
monthly_climate(11, som, warm).
monthly_climate(11, zaf, rain).
monthly_climate(11, kor, rain).
monthly_climate(11, ssd, warm).
monthly_climate(11, esp, rain).
monthly_climate(11, lka, warm).
monthly_climate(11, sdn, warm).
monthly_climate(11, sur, warm).
monthly_climate(11, swz, warm).
monthly_climate(11, swe, rain).
monthly_climate(11, che, rain).
monthly_climate(11, syr, rain).
monthly_climate(11, tjk, rain).
monthly_climate(11, tha, warm).
monthly_climate(11, tls, warm).
monthly_climate(11, tgo, warm).
monthly_climate(11, tun, rain).
monthly_climate(11, tur, rain).
monthly_climate(11, tkm, rain).
monthly_climate(11, uga, warm).
monthly_climate(11, ukr, rain).
monthly_climate(11, are, warm).
monthly_climate(11, gbr, rain).
monthly_climate(11, tza, rain).
monthly_climate(11, usa, rain).
monthly_climate(11, ury, rain).
monthly_climate(11, uzb, rain).
monthly_climate(11, ven, warm).
monthly_climate(11, vnm, warm).
monthly_climate(11, esh, warm).
monthly_climate(11, yem, warm).
monthly_climate(11, zmb, warm).
monthly_climate(11, zwe, warm).
monthly_climate(12, afg, rain).
monthly_climate(12, alb, rain).
monthly_climate(12, dza, rain).
monthly_climate(12, and, snow).
monthly_climate(12, ago, warm).
monthly_climate(12, arg, warm).
monthly_climate(12, arm, snow).
monthly_climate(12, aut, snow).
monthly_climate(12, aze, rain).
monthly_climate(12, bhr, rain).
monthly_climate(12, bgd, rain).
monthly_climate(12, blr, snow).
monthly_climate(12, bel, rain).
monthly_climate(12, blz, warm).
monthly_climate(12, ben, warm).
monthly_climate(12, bmu, rain).
monthly_climate(12, btn, rain).
monthly_climate(12, bol, rain).
monthly_climate(12, bih, rain).
monthly_climate(12, bwa, warm).
monthly_climate(12, bra, warm).
monthly_climate(12, brn, warm).
monthly_climate(12, bgr, rain).
monthly_climate(12, bfa, warm).
monthly_climate(12, bdi, rain).
monthly_climate(12, cpv, warm).
monthly_climate(12, khm, warm).
monthly_climate(12, cmr, warm).
monthly_climate(12, can, snow).
monthly_climate(12, caf, warm).
monthly_climate(12, tcd, warm).
monthly_climate(12, chl, rain).
monthly_climate(12, chn, rain).
monthly_climate(12, col, warm).
monthly_climate(12, com, warm).
monthly_climate(12, cog, warm).
monthly_climate(12, cri, rain).
monthly_climate(12, civ, warm).
monthly_climate(12, hrv, rain).
monthly_climate(12, cyp, rain).
monthly_climate(12, cze, snow).
monthly_climate(12, cod, warm).
monthly_climate(12, dnk, rain).
monthly_climate(12, dji, warm).
monthly_climate(12, ecu, warm).
monthly_climate(12, egy, rain).
monthly_climate(12, slv, warm).
monthly_climate(12, gnq, warm).
monthly_climate(12, eri, warm).
monthly_climate(12, est, snow).
monthly_climate(12, eth, rain).
monthly_climate(12, fin, snow).
monthly_climate(12, fra, rain).
monthly_climate(12, gab, warm).
monthly_climate(12, gmb, warm).
monthly_climate(12, geo, rain).
monthly_climate(12, deu, rain).
monthly_climate(12, gha, warm).
monthly_climate(12, gib, rain).
monthly_climate(12, grc, rain).
monthly_climate(12, grl, rain).
monthly_climate(12, gtm, rain).
monthly_climate(12, ggy, warm).
monthly_climate(12, gnb, warm).
monthly_climate(12, gin, warm).
monthly_climate(12, guy, warm).
monthly_climate(12, hnd, warm).
monthly_climate(12, hun, rain).
monthly_climate(12, isl, snow).
monthly_climate(12, ind, rain).
monthly_climate(12, idn, warm).
monthly_climate(12, irn, rain).
monthly_climate(12, irq, rain).
monthly_climate(12, irl, rain).
monthly_climate(12, isr, rain).
monthly_climate(12, ita, rain).
monthly_climate(12, jpn, rain).
monthly_climate(12, jey, warm).
monthly_climate(12, jor, rain).
monthly_climate(12, kaz, snow).
monthly_climate(12, ken, warm).
monthly_climate(12, kwt, rain).
monthly_climate(12, kgz, snow).
monthly_climate(12, lao, warm).
monthly_climate(12, lva, snow).
monthly_climate(12, lbn, rain).
monthly_climate(12, lso, rain).
monthly_climate(12, lbr, warm).
monthly_climate(12, lby, rain).
monthly_climate(12, lie, rain).
monthly_climate(12, ltu, snow).
monthly_climate(12, lux, rain).
monthly_climate(12, mkd, rain).
monthly_climate(12, mdg, warm).
monthly_climate(12, mwi, warm).
monthly_climate(12, mys, warm).
monthly_climate(12, mdv, warm).
monthly_climate(12, mli, warm).
monthly_climate(12, mlt, rain).
monthly_climate(12, mrt, warm).
monthly_climate(12, mus, warm).
monthly_climate(12, myt, warm).
monthly_climate(12, mex, rain).
monthly_climate(12, mda, snow).
monthly_climate(12, mco, rain).
monthly_climate(12, mng, snow).
monthly_climate(12, mne, rain).
monthly_climate(12, mar, rain).
monthly_climate(12, moz, warm).
monthly_climate(12, mmr, warm).
monthly_climate(12, nam, warm).
monthly_climate(12, npl, rain).
monthly_climate(12, nld, rain).
monthly_climate(12, nic, warm).
monthly_climate(12, ner, warm).
monthly_climate(12, nga, warm).
monthly_climate(12, prk, snow).
monthly_climate(12, nor, snow).
monthly_climate(12, omn, warm).
monthly_climate(12, pak, rain).
monthly_climate(12, pse, warm).
monthly_climate(12, pan, warm).
monthly_climate(12, pry, warm).
monthly_climate(12, per, rain).
monthly_climate(12, phl, warm).
monthly_climate(12, pol, snow).
monthly_climate(12, prt, rain).
monthly_climate(12, qat, rain).
monthly_climate(12, rou, snow).
monthly_climate(12, rus, snow).
monthly_climate(12, rwa, rain).
monthly_climate(12, shn, rain).
monthly_climate(12, smr, rain).
monthly_climate(12, wsm, warm).
monthly_climate(12, stp, warm).
monthly_climate(12, sau, rain).
monthly_climate(12, sen, warm).
monthly_climate(12, srb, rain).
monthly_climate(12, syc, warm).
monthly_climate(12, sle, warm).
monthly_climate(12, sgp, warm).
monthly_climate(12, svk, snow).
monthly_climate(12, svn, snow).
monthly_climate(12, som, warm).
monthly_climate(12, zaf, warm).
monthly_climate(12, kor, rain).
monthly_climate(12, ssd, warm).
monthly_climate(12, esp, rain).
monthly_climate(12, lka, warm).
monthly_climate(12, sdn, warm).
monthly_climate(12, sur, warm).
monthly_climate(12, swz, warm).
monthly_climate(12, swe, snow).
monthly_climate(12, che, snow).
monthly_climate(12, syr, rain).
monthly_climate(12, tjk, rain).
monthly_climate(12, tha, warm).
monthly_climate(12, tls, warm).
monthly_climate(12, tgo, warm).
monthly_climate(12, tun, rain).
monthly_climate(12, tur, rain).
monthly_climate(12, tkm, rain).
monthly_climate(12, uga, warm).
monthly_climate(12, ukr, snow).
monthly_climate(12, are, warm).
monthly_climate(12, gbr, rain).
monthly_climate(12, tza, warm).
monthly_climate(12, usa, rain).
monthly_climate(12, ury, warm).
monthly_climate(12, uzb, rain).
monthly_climate(12, ven, warm).
monthly_climate(12, vnm, warm).
monthly_climate(12, esh, rain).
monthly_climate(12, yem, warm).
monthly_climate(12, zmb, warm).
monthly_climate(12, zwe, warm).
