:- module(isin,[]).
isin(zimbabwe,africa).
isin(zambia,africa).
isin(westernsahara,africa).
isin(unitedrepublicoftanzania,africa).
isin(uganda,africa).
isin(tunisia,africa).
isin(togo,africa).
isin(swaziland,africa).
isin(sudan,africa).
isin(southsudan,africa).
isin(southafrica,africa).
isin(somalia,africa).
isin(sierraleone,africa).
isin(seychelles,africa).
isin(senegal,africa).
isin(saotomeandprincipe,africa).
isin(sainthelena,africa).
isin(rwanda,africa).
isin(nigeria,africa).
isin(niger,africa).
isin(namibia,africa).
isin(mozambique,africa).
isin(morocco,africa).
isin(mayotte,africa).
isin(mauritius,africa).
isin(mauritania,africa).
isin(mali,africa).
isin(malawi,africa).
isin(madagascar,africa).
isin(libya,africa).
isin(liberia,africa).
isin(lesotho,africa).
isin(kenya,africa).
isin(guinea-bissau,africa).
isin(guinea,africa).
isin(ghana,africa).
isin(gambia,africa).
isin(gabon,africa).
isin(ethiopia,africa).
isin(eritrea,africa).
isin(equatorialguinea,africa).
isin(egypt,africa).
isin(djibouti,africa).
isin(democraticrepublicofthecongo,africa).
isin(cotedivoire,africa).
isin(congo,africa).
isin(comoros,africa).
isin(chad,africa).
isin(centralafricanrepublic,africa).
isin(cameroon,africa).
isin(caboverde,africa).
isin(burundi,africa).
isin(burkinafaso,africa).
isin(botswana,africa).
isin(benin,africa).
isin(angola,africa).
isin(algeria,africa).
isin(afghanistan,asia).
isin(armenia,asia).
isin(azerbaijan,asia).
isin(bahrain,asia).
isin(bangladesh,asia).
isin(bhutan,asia).
isin(brunei,asia).
isin(cambodia,asia).
isin(china,asia).
isin(cyprus,asia).
isin(southkorea,asia).
isin(georgia,asia).
isin(india,asia).
isin(indonesia,asia).
isin(iran,asia).
isin(iraq,asia).
isin(israel,asia).
isin(japan,asia).
isin(jordan,asia).
isin(kazakhstan,asia).
isin(kuwait,asia).
isin(kyrgyzstan,asia).
isin(laos,asia).
isin(lebanon,asia).
isin(malaysia,asia).
isin(maldives,asia).
isin(mongolia,asia).
isin(myanmar,asia).
isin(nepal,asia).
isin(oman,asia).
isin(pakistan,asia).
isin(philippines,asia).
isin(qatar,asia).
isin(northkorea,asia).
isin(saudiarabia,asia).
isin(singapore,asia).
isin(srilanka,asia).
isin(palestine,asia).
isin(syrian,asia).
isin(tajikistan,asia).
isin(thailand,asia).
isin(timor-leste,asia).
isin(turkey,asia).
isin(turkmenistan,asia).
isin(unitedarabemirates,asia).
isin(uzbekistan,asia).
isin(vietnam,asia).
isin(yemen,asia).
isin(albania,europe).
isin(andorra,europe).
isin(austria,europe).
isin(belarus,europe).
isin(belgium,europe).
isin(bosnia,europe).
isin(bulgaria,europe).
isin(croatia,europe).
isin(czech,europe).
isin(denmark,europe).
isin(estonia,europe).
isin(finland,europe).
isin(france,europe).
isin(germany,europe).
isin(gibraltar,europe).
isin(greece,europe).
isin(guernsey,europe).
isin(hungary,europe).
isin(iceland,europe).
isin(ireland,europe).
isin(italy,europe).
isin(jersey,europe).
isin(latvia,europe).
isin(liechtenstein,europe).
isin(lithuania,europe).
isin(luxembourg,europe).
isin(malta,europe).
isin(monaco,europe).
isin(montenegro,europe).
isin(netherlands,europe).
isin(norway,europe).
isin(poland,europe).
isin(portugal,europe).
isin(moldova,europe).
isin(romania,europe).
isin(russian,europe).
isin(sanmarino,europe).
isin(sark,europe).
isin(serbia,europe).
isin(slovakia,europe).
isin(slovenia,europe).
isin(spain,europe).
isin(sweden,europe).
isin(switzerland,europe).
isin(macedonia,europe).
isin(ukraine,europe).
isin(unitedkingdom,europe).
isin(belize,northamerica).
isin(bermuda,northamerica).
isin(canada,northamerica).
isin(costarica,northamerica).
isin(elsalvador,northamerica).
isin(greenland,northamerica).
isin(guatemala,northamerica).
isin(honduras,northamerica).
isin(mexico,northamerica).
isin(nicaragua,northamerica).
isin(panama,northamerica).
isin(unitedstatesofamerica,northamerica).
isin(argentina,southamerica).
isin(bolivia,southamerica).
isin(brazil,southamerica).
isin(chile,southamerica).
isin(colombia,southamerica).
isin(ecuador,southamerica).
isin(guyana,southamerica).
isin(paraguay,southamerica).
isin(peru,southamerica).
isin(suriname,southamerica).
isin(uruguay,southamerica).
isin(venezuela,southamerica).
