:- module(islock,[]).
islock(afghanistan).
islock(andorra).
islock(armenia).
islock(austria).
islock(azerbaijan).
islock(belarus).
islock(bhutan).
islock(bolivia).
islock(botswana).
islock(burkinafaso).
islock(burundi).
islock(centralafricanrepublic).
islock(chad).
islock(czech).
islock(ethiopia).
islock(hungary).
islock(kazakhstan).
islock(kyrgyzstan).
islock(laos).
islock(lesotho).
islock(liechtenstein).
islock(luxembourg).
islock(macedonia).
islock(malawi).
islock(mali).
islock(moldova).
islock(mongolia).
islock(nepal).
islock(niger).
islock(paraguay).
islock(rwanda).
islock(sanmarino).
islock(serbia).
islock(slovakia).
islock(southsudan).
islock(swaziland).
islock(switzerland).
islock(tajikistan).
islock(turkmenistan).
islock(uganda).
islock(uzbekistan).
islock(zambia).
islock(zimbabwe).
