sed -i '.original' 's/albania/alb/g'  $1
sed -i '.original' 's/zimbabwe/zwe/g' $1
zambia,africa
westernsahara,africa
unitedrepublicoftanzania,africa
uganda,africa
tunisia,africa
togo,africa
swaziland,africa
sudan,africa
southsudan,africa
southafrica,africa
somalia,africa
sierraleone,africa
seychelles,africa
senegal,africa
saotomeandprincipe,africa
sainthelena,africa
rwanda,africa
nigeria,africa
niger,africa
namibia,africa
mozambique,africa
morocco,africa
mayotte,africa
mauritius,africa
mauritania,africa
mali,africa
malawi,africa
madagascar,africa
libya,africa
liberia,africa
lesotho,africa
kenya,africa
guinea-bissau,africa
guinea,africa
ghana,africa
gambia,africa
gabon,africa
ethiopia,africa
eritrea,africa
equatorialguinea,africa
egypt,africa
djibouti,africa
democraticrepublicofthecongo,africa
cotedivoire,africa
congo,africa
comoros,africa
chad,africa
centralafricanrepublic,africa
cameroon,africa
caboverde,africa
burundi,africa
burkinafaso,africa
botswana,africa
benin,africa
angola,africa
algeria,africa
afghanistan,asia
armenia,asia
azerbaijan,asia
bahrain,asia
bangladesh,asia
bhutan,asia
brunei,asia
cambodia,asia
china,asia
cyprus,asia
southkorea,asia
georgia,asia
india,asia
indonesia,asia
iran,asia
iraq,asia
israel,asia
japan,asia
jordan,asia
kazakhstan,asia
kuwait,asia
kyrgyzstan,asia
laos,asia
lebanon,asia
malaysia,asia
maldives,asia
mongolia,asia
myanmar,asia
nepal,asia
oman,asia
pakistan,asia
philippines,asia
qatar,asia
northkorea,asia
saudiarabia,asia
singapore,asia
srilanka,asia
palestine,asia
syrian,asia
tajikistan,asia
thailand,asia
timor-leste,asia
turkey,asia
turkmenistan,asia
unitedarabemirates,asia
uzbekistan,asia
vietnam,asia
yemen,asia
albania,europe
andorra,europe
austria,europe
belarus,europe
belgium,europe
bosnia,europe
bulgaria,europe
croatia,europe
czech,europe
denmark,europe
estonia,europe
finland,europe
france,europe
germany,europe
gibraltar,europe
greece,europe
guernsey,europe
hungary,europe
iceland,europe
ireland,europe
italy,europe
jersey,europe
latvia,europe
liechtenstein,europe
lithuania,europe
luxembourg,europe
malta,europe
monaco,europe
montenegro,europe
netherlands,europe
norway,europe
poland,europe
portugal,europe
moldova,europe
romania,europe
russian,europe
san marino,europe
sark,europe
serbia,europe
slovakia,europe
slovenia,europe
spain,europe
sweden,europe
switzerland,europe
macedonia,europe
ukraine,europe
unitedkingdom,europe
belize,northamerica
bermuda,northamerica
canada,northamerica
costa rica,northamerica
elsalvador,northamerica
greenland,northamerica
guatemala,northamerica
honduras,northamerica
mexico,northamerica
nicaragua,northamerica
panama,northamerica
unitedstatesofamerica,northamerica
argentina,southamerica
bolivia,southamerica
brazil,southamerica
chile,southamerica
colombia,southamerica
ecuador,southamerica
guyana,southamerica
paraguay,southamerica
peru,southamerica
suriname,southamerica
uruguay,southamerica
venezuela,southamerica
