sed -i '.original' 's/zimbabwe/zwe/g' $1
sed -i '.original' 's/zambia/zmb/g' $1
sed -i '.original' 's/westernsahara/esh/g' $1
sed -i '.original' 's/unitedrepublicoftanzania/tza/g' $1
sed -i '.original' 's/uganda/uga/g' $1
sed -i '.original' 's/tunisia/tun/g' $1
sed -i '.original' 's/togo/tgo/g' $1
sed -i '.original' 's/swaziland/swz/g' $1
sed -i '.original' 's/sudan/sdn/g' $1
sed -i '.original' 's/southsudan/ssd/g' $1
sed -i '.original' 's/southafrica/zaf/g' $1
sed -i '.original' 's/somalia/som/g' $1
sed -i '.original' 's/sierraleone/sle/g' $1
sed -i '.original' 's/seychelles/syc/g' $1
sed -i '.original' 's/senegal/sen/g' $1
sed -i '.original' 's/saotomeandprincipe/wsm/g' $1
sed -i '.original' 's/sainthelena/shn/g' $1
sed -i '.original' 's/rwanda/rwa/g' $1
sed -i '.original' 's/nigeria/nga/g' $1
sed -i '.original' 's/niger/ner/g' $1
sed -i '.original' 's/namibia/nam/g' $1
sed -i '.original' 's/mozambique/moz/g' $1
sed -i '.original' 's/morocco/mar/g' $1
sed -i '.original' 's/mayotte/myt/g' $1
sed -i '.original' 's/mauritius/mus/g' $1
sed -i '.original' 's/mauritania/mrt/g' $1
sed -i '.original' 's/mali/mli/g' $1
sed -i '.original' 's/malawi/mwi/g' $1
sed -i '.original' 's/madagascar/mdg/g' $1
sed -i '.original' 's/libya/lby/g' $1
sed -i '.original' 's/liberia/lbr/g' $1
sed -i '.original' 's/lesotho/lso/g' $1
sed -i '.original' 's/kenya/ken/g' $1
sed -i '.original' 's/guinea-bissau/gnb/g' $1
sed -i '.original' 's/guinea/gin/g' $1
sed -i '.original' 's/ghana/gha/g' $1
sed -i '.original' 's/gambia/gmb/g' $1
sed -i '.original' 's/gabon/gab/g' $1
sed -i '.original' 's/ethiopia/eth/g' $1
sed -i '.original' 's/eritrea/eri/g' $1
sed -i '.original' 's/equatorialguinea/gnq/g' $1
sed -i '.original' 's/egypt/egy/g' $1
sed -i '.original' 's/djibouti/dji/g' $1
sed -i '.original' 's/democraticrepublicofthecongo/cod/g' $1
sed -i '.original' 's/cotedivoire/civ/g' $1
sed -i '.original' 's/congo/cog/g' $1
sed -i '.original' 's/comoros/com/g' $1
sed -i '.original' 's/chad/tcd/g' $1
sed -i '.original' 's/centralafricanrepublic/caf/g' $1
sed -i '.original' 's/cameroon/cmr/g' $1
sed -i '.original' 's/caboverde/cpv/g' $1
sed -i '.original' 's/burundi/bdi/g' $1
sed -i '.original' 's/burkinafaso/bfa/g' $1
sed -i '.original' 's/botswana/bwa/g' $1
sed -i '.original' 's/benin/ben/g' $1
sed -i '.original' 's/angola/ago/g' $1
sed -i '.original' 's/algeria/dza/g' $1
sed -i '.original' 's/afghanistan/afg/g' $1
sed -i '.original' 's/armenia/arm/g' $1
sed -i '.original' 's/azerbaijan/aze/g' $1
sed -i '.original' 's/bahrain/bhr/g' $1
sed -i '.original' 's/bangladesh/bgd/g' $1
sed -i '.original' 's/bhutan/btn/g' $1
sed -i '.original' 's/brunei/brn/g' $1
sed -i '.original' 's/cambodia/khm/g' $1
sed -i '.original' 's/china/chn/g' $1
sed -i '.original' 's/cyprus/cyp/g' $1
sed -i '.original' 's/southkorea/kor/g' $1
sed -i '.original' 's/georgia/geo/g' $1
sed -i '.original' 's/india/ind/g' $1
sed -i '.original' 's/indonesia/idn/g' $1
sed -i '.original' 's/iran/irn/g' $1
sed -i '.original' 's/iraq/irq/g' $1
sed -i '.original' 's/israel/isr/g' $1
sed -i '.original' 's/japan/jpn/g' $1
sed -i '.original' 's/jordan/jor/g' $1
sed -i '.original' 's/kazakhstan/kaz/g' $1
sed -i '.original' 's/kuwait/kwt/g' $1
sed -i '.original' 's/kyrgyzstan/kgz/g' $1
sed -i '.original' 's/laos/lao/g' $1
sed -i '.original' 's/lebanon/lbn/g' $1
sed -i '.original' 's/malaysia/mys/g' $1
sed -i '.original' 's/maldives/mdv/g' $1
sed -i '.original' 's/mongolia/mng/g' $1
sed -i '.original' 's/myanmar/mmr/g' $1
sed -i '.original' 's/nepal/npl/g' $1
sed -i '.original' 's/pakistan/pak/g' $1
sed -i '.original' 's/philippines/phl/g' $1
sed -i '.original' 's/qatar/qat/g' $1
sed -i '.original' 's/northkorea/prk/g' $1
sed -i '.original' 's/saudiarabia/sau/g' $1
sed -i '.original' 's/singapore/sgp/g' $1
sed -i '.original' 's/srilanka/lka/g' $1
sed -i '.original' 's/palestine/pse/g' $1
sed -i '.original' 's/syrian/syr/g' $1
sed -i '.original' 's/tajikistan/tjk/g' $1
sed -i '.original' 's/thailand/tha/g' $1
sed -i '.original' 's/timor-leste/tls/g' $1
sed -i '.original' 's/turkey/tur/g' $1
sed -i '.original' 's/turkmenistan/tkm/g' $1
sed -i '.original' 's/unitedarabemirates/are/g' $1
sed -i '.original' 's/uzbekistan/uzb/g' $1
sed -i '.original' 's/vietnam/vnm/g' $1
sed -i '.original' 's/yemen/yem/g' $1
sed -i '.original' 's/albania/alb/g' $1
sed -i '.original' 's/andorra/and/g' $1
sed -i '.original' 's/austria/aut/g' $1
sed -i '.original' 's/belarus/blr/g' $1
sed -i '.original' 's/belgium/bel/g' $1
sed -i '.original' 's/bosnia/bih/g' $1
sed -i '.original' 's/bulgaria/bgr/g' $1
sed -i '.original' 's/croatia/hrv/g' $1
sed -i '.original' 's/czech/cze/g' $1
sed -i '.original' 's/denmark/dnk/g' $1
sed -i '.original' 's/estonia/est/g' $1
sed -i '.original' 's/finland/fin/g' $1
sed -i '.original' 's/france/fra/g' $1
sed -i '.original' 's/germany/deu/g' $1
sed -i '.original' 's/gibraltar/gib/g' $1
sed -i '.original' 's/greece/grc/g' $1
sed -i '.original' 's/guernsey/ggy/g' $1
sed -i '.original' 's/hungary/hun/g' $1
sed -i '.original' 's/iceland/isl/g' $1
sed -i '.original' 's/ireland/irl/g' $1
sed -i '.original' 's/italy/ita/g' $1
sed -i '.original' 's/jersey/jey/g' $1
sed -i '.original' 's/latvia/lva/g' $1
sed -i '.original' 's/liechtenstein/lie/g' $1
sed -i '.original' 's/lithuania/ltu/g' $1
sed -i '.original' 's/luxembourg/lux/g' $1
sed -i '.original' 's/malta/mlt/g' $1
sed -i '.original' 's/monaco/mco/g' $1
sed -i '.original' 's/montenegro/mne/g' $1
sed -i '.original' 's/netherlands/nld/g' $1
sed -i '.original' 's/norway/nor/g' $1
sed -i '.original' 's/poland/pol/g' $1
sed -i '.original' 's/portugal/prt/g' $1
sed -i '.original' 's/moldova/mda/g' $1
sed -i '.original' 's/romania/rou/g' $1
sed -i '.original' 's/russian/rus/g' $1
sed -i '.original' 's/sanmarino/smr/g' $1
sed -i '.original' 's/sark/stp/g' $1
sed -i '.original' 's/serbia/srb/g' $1
sed -i '.original' 's/slovakia/svk/g' $1
sed -i '.original' 's/slovenia/svn/g' $1
sed -i '.original' 's/spain/esp/g' $1
sed -i '.original' 's/sweden/swe/g' $1
sed -i '.original' 's/switzerland/che/g' $1
sed -i '.original' 's/macedonia/mkd/g' $1
sed -i '.original' 's/ukraine/ukr/g' $1
sed -i '.original' 's/unitedkingdom/gbr/g' $1
sed -i '.original' 's/belize/blz/g' $1
sed -i '.original' 's/bermuda/bmu/g' $1
sed -i '.original' 's/canada/can/g' $1
sed -i '.original' 's/costarica/cri/g' $1
sed -i '.original' 's/elsalvador/slv/g' $1
sed -i '.original' 's/greenland/grl/g' $1
sed -i '.original' 's/guatemala/gtm/g' $1
sed -i '.original' 's/honduras/hnd/g' $1
sed -i '.original' 's/mexico/mex/g' $1
sed -i '.original' 's/nicaragua/nic/g' $1
sed -i '.original' 's/panama/pan/g' $1
sed -i '.original' 's/unitedstatesofamerica/usa/g' $1
sed -i '.original' 's/argentina/arg/g' $1
sed -i '.original' 's/bolivia/bol/g' $1
sed -i '.original' 's/brazil/bra/g' $1
sed -i '.original' 's/chile/chl/g' $1
sed -i '.original' 's/colombia/col/g' $1
sed -i '.original' 's/ecuador/ecu/g' $1
sed -i '.original' 's/guyana/guy/g' $1
sed -i '.original' 's/paraguay/pry/g' $1
sed -i '.original' 's/peru/per/g' $1
sed -i '.original' 's/suriname/sur/g' $1
sed -i '.original' 's/uruguay/ury/g' $1
sed -i '.original' 's/venezuela/ven/g' $1
sed -i '.original' 's/oman/omn/g' $1
