sed -i '.original' 's/zimbabwe/ZWE/g' $1
sed -i '.original' 's/zambia/ZMB/g' $1
sed -i '.original' 's/westernsahara/ESH/g' $1
sed -i '.original' 's/unitedrepublicoftanzania/TZA/g' $1
sed -i '.original' 's/uganda/UGA/g' $1
sed -i '.original' 's/tunisia/TUN/g' $1
sed -i '.original' 's/togo/TGO/g' $1
sed -i '.original' 's/swaziland/SWZ/g' $1
sed -i '.original' 's/sudan/SDN/g' $1
sed -i '.original' 's/southsudan/SSD/g' $1
sed -i '.original' 's/southafrica/ZAF/g' $1
sed -i '.original' 's/somalia/SOM/g' $1
sed -i '.original' 's/sierraleone/SLE/g' $1
sed -i '.original' 's/seychelles/SYC/g' $1
sed -i '.original' 's/senegal/SEN/g' $1
sed -i '.original' 's/saotomeandprincipe/WSM/g' $1
sed -i '.original' 's/sainthelena/SHN/g' $1
sed -i '.original' 's/rwanda/RWA/g' $1
sed -i '.original' 's/nigeria/NGA/g' $1
sed -i '.original' 's/niger/NER/g' $1
sed -i '.original' 's/namibia/NAM/g' $1
sed -i '.original' 's/mozambique/MOZ/g' $1
sed -i '.original' 's/morocco/MAR/g' $1
sed -i '.original' 's/mayotte/MYT/g' $1
sed -i '.original' 's/mauritius/MUS/g' $1
sed -i '.original' 's/mauritania/MRT/g' $1
sed -i '.original' 's/mali/MLI/g' $1
sed -i '.original' 's/malawi/MWI/g' $1
sed -i '.original' 's/madagascar/MDG/g' $1
sed -i '.original' 's/libya/LBY/g' $1
sed -i '.original' 's/liberia/LBR/g' $1
sed -i '.original' 's/lesotho/LSO/g' $1
sed -i '.original' 's/kenya/KEN/g' $1
sed -i '.original' 's/guinea-bissau/GNB/g' $1
sed -i '.original' 's/guinea/GIN/g' $1
sed -i '.original' 's/ghana/GHA/g' $1
sed -i '.original' 's/gambia/GMB/g' $1
sed -i '.original' 's/gabon/GAB/g' $1
sed -i '.original' 's/ethiopia/ETH/g' $1
sed -i '.original' 's/eritrea/ERI/g' $1
sed -i '.original' 's/equatorialguinea/GNQ/g' $1
sed -i '.original' 's/egypt/EGY/g' $1
sed -i '.original' 's/djibouti/DJI/g' $1
sed -i '.original' 's/democraticrepublicofthecongo/COD/g' $1
sed -i '.original' 's/cotedivoire/CIV/g' $1
sed -i '.original' 's/congo/COG/g' $1
sed -i '.original' 's/comoros/COM/g' $1
sed -i '.original' 's/chad/TCD/g' $1
sed -i '.original' 's/centralafricanrepublic/CAF/g' $1
sed -i '.original' 's/cameroon/CMR/g' $1
sed -i '.original' 's/caboverde/CPV/g' $1
sed -i '.original' 's/burundi/BDI/g' $1
sed -i '.original' 's/burkinafaso/BFA/g' $1
sed -i '.original' 's/botswana/BWA/g' $1
sed -i '.original' 's/benin/BEN/g' $1
sed -i '.original' 's/angola/AGO/g' $1
sed -i '.original' 's/algeria/DZA/g' $1
sed -i '.original' 's/afghanistan/AFG/g' $1
sed -i '.original' 's/armenia/ARM/g' $1
sed -i '.original' 's/azerbaijan/AZE/g' $1
sed -i '.original' 's/bahrain/BHR/g' $1
sed -i '.original' 's/bangladesh/BGD/g' $1
sed -i '.original' 's/bhutan/BTN/g' $1
sed -i '.original' 's/brunei/BRN/g' $1
sed -i '.original' 's/cambodia/KHM/g' $1
sed -i '.original' 's/china/CHN/g' $1
sed -i '.original' 's/cyprus/CYP/g' $1
sed -i '.original' 's/southkorea/KOR/g' $1
sed -i '.original' 's/georgia/GEO/g' $1
sed -i '.original' 's/india/IND/g' $1
sed -i '.original' 's/indonesia/IDN/g' $1
sed -i '.original' 's/iran/IRN/g' $1
sed -i '.original' 's/iraq/IRQ/g' $1
sed -i '.original' 's/israel/ISR/g' $1
sed -i '.original' 's/japan/JPN/g' $1
sed -i '.original' 's/jordan/JOR/g' $1
sed -i '.original' 's/kazakhstan/KAZ/g' $1
sed -i '.original' 's/kuwait/KWT/g' $1
sed -i '.original' 's/kyrgyzstan/KGZ/g' $1
sed -i '.original' 's/laos/LAO/g' $1
sed -i '.original' 's/lebanon/LBN/g' $1
sed -i '.original' 's/malaysia/MYS/g' $1
sed -i '.original' 's/maldives/MDV/g' $1
sed -i '.original' 's/mongolia/MNG/g' $1
sed -i '.original' 's/myanmar/MMR/g' $1
sed -i '.original' 's/nepal/NPL/g' $1
sed -i '.original' 's/oman/OMN/g' $1
sed -i '.original' 's/pakistan/PAK/g' $1
sed -i '.original' 's/philippines/PHL/g' $1
sed -i '.original' 's/qatar/QAT/g' $1
sed -i '.original' 's/northkorea/PRK/g' $1
sed -i '.original' 's/saudiarabia/SAU/g' $1
sed -i '.original' 's/singapore/SGP/g' $1
sed -i '.original' 's/srilanka/LKA/g' $1
sed -i '.original' 's/palestine/PSE/g' $1
sed -i '.original' 's/syrian/SYR/g' $1
sed -i '.original' 's/tajikistan/TJK/g' $1
sed -i '.original' 's/thailand/THA/g' $1
sed -i '.original' 's/timor-leste/TLS/g' $1
sed -i '.original' 's/turkey/TUR/g' $1
sed -i '.original' 's/turkmenistan/TKM/g' $1
sed -i '.original' 's/unitedarabemirates/ARE/g' $1
sed -i '.original' 's/uzbekistan/UZB/g' $1
sed -i '.original' 's/vietnam/VNM/g' $1
sed -i '.original' 's/yemen/YEM/g' $1
sed -i '.original' 's/albania/ALB/g' $1
sed -i '.original' 's/andorra/AND/g' $1
sed -i '.original' 's/austria/AUT/g' $1
sed -i '.original' 's/belarus/BLR/g' $1
sed -i '.original' 's/belgium/BEL/g' $1
sed -i '.original' 's/bosnia/BIH/g' $1
sed -i '.original' 's/bulgaria/BGR/g' $1
sed -i '.original' 's/croatia/HRV/g' $1
sed -i '.original' 's/czech/CZE/g' $1
sed -i '.original' 's/denmark/DNK/g' $1
sed -i '.original' 's/estonia/EST/g' $1
sed -i '.original' 's/finland/FIN/g' $1
sed -i '.original' 's/france/FRA/g' $1
sed -i '.original' 's/germany/DEU/g' $1
sed -i '.original' 's/gibraltar/GIB/g' $1
sed -i '.original' 's/greece/GRC/g' $1
sed -i '.original' 's/guernsey/GGY/g' $1
sed -i '.original' 's/hungary/HUN/g' $1
sed -i '.original' 's/iceland/ISL/g' $1
sed -i '.original' 's/ireland/IRL/g' $1
sed -i '.original' 's/italy/ITA/g' $1
sed -i '.original' 's/jersey/JEY/g' $1
sed -i '.original' 's/latvia/LVA/g' $1
sed -i '.original' 's/liechtenstein/LIE/g' $1
sed -i '.original' 's/lithuania/LTU/g' $1
sed -i '.original' 's/luxembourg/LUX/g' $1
sed -i '.original' 's/malta/MLT/g' $1
sed -i '.original' 's/monaco/MCO/g' $1
sed -i '.original' 's/montenegro/MNE/g' $1
sed -i '.original' 's/netherlands/NLD/g' $1
sed -i '.original' 's/norway/NOR/g' $1
sed -i '.original' 's/poland/POL/g' $1
sed -i '.original' 's/portugal/PRT/g' $1
sed -i '.original' 's/moldova/MDA/g' $1
sed -i '.original' 's/romania/ROU/g' $1
sed -i '.original' 's/russian/RUS/g' $1
sed -i '.original' 's/sanmarino/SMR/g' $1
sed -i '.original' 's/sark/STP/g' $1
sed -i '.original' 's/serbia/SRB/g' $1
sed -i '.original' 's/slovakia/SVK/g' $1
sed -i '.original' 's/slovenia/SVN/g' $1
sed -i '.original' 's/spain/ESP/g' $1
sed -i '.original' 's/sweden/SWE/g' $1
sed -i '.original' 's/switzerland/CHE/g' $1
sed -i '.original' 's/macedonia/MKD/g' $1
sed -i '.original' 's/ukraine/UKR/g' $1
sed -i '.original' 's/unitedkingdom/GBR/g' $1
sed -i '.original' 's/belize/BLZ/g' $1
sed -i '.original' 's/bermuda/BMU/g' $1
sed -i '.original' 's/canada/CAN/g' $1
sed -i '.original' 's/costarica/CRI/g' $1
sed -i '.original' 's/elsalvador/SLV/g' $1
sed -i '.original' 's/greenland/GRL/g' $1
sed -i '.original' 's/guatemala/GTM/g' $1
sed -i '.original' 's/honduras/HND/g' $1
sed -i '.original' 's/mexico/MEX/g' $1
sed -i '.original' 's/nicaragua/NIC/g' $1
sed -i '.original' 's/panama/PAN/g' $1
sed -i '.original' 's/unitedstatesofamerica/USA/g' $1
sed -i '.original' 's/argentina/ARG/g' $1
sed -i '.original' 's/bolivia/BOL/g' $1
sed -i '.original' 's/brazil/BRA/g' $1
sed -i '.original' 's/chile/CHL/g' $1
sed -i '.original' 's/colombia/COL/g' $1
sed -i '.original' 's/ecuador/ECU/g' $1
sed -i '.original' 's/guyana/GUY/g' $1
sed -i '.original' 's/paraguay/PRY/g' $1
sed -i '.original' 's/peru/PER/g' $1
sed -i '.original' 's/suriname/SUR/g' $1
sed -i '.original' 's/uruguay/URY/g' $1
sed -i '.original' 's/venezuela/VEN/g' $1
