:- module(country,[]).
country(and).
country(ago).
country(arg).
country(arm).
country(aut).
country(aze).
country(bhr).
country(bgd).
country(blr).
country(bel).
country(blz).
country(ben).
country(bmu).
country(btn).
country(bol).
country(bih).
country(bwa).
country(bra).
country(brn).
country(bgr).
country(bfa).
country(bdi).
country(cpv).
country(khm).
country(cmr).
country(can).
country(caf).
country(tcd).
country(chl).
country(chn).
country(col).
country(com).
country(cog).
country(cri).
country(civ).
country(hrv).
country(cyp).
country(cze).
country(cod).
country(dnk).
country(dji).
country(ecu).
country(egy).
country(slv).
country(gnq).
country(eri).
country(est).
country(eth).
country(fin).
country(fra).
country(gab).
country(gmb).
country(geo).
country(deu).
country(gha).
country(gib).
country(grc).
country(grl).
country(gtm).
country(ggy).
country(gnb).
country(gin).
country(guy).
country(hnd).
country(hun).
country(isl).
country(ind).
country(idn).
country(irn).
country(irq).
country(irl).
country(isr).
country(ita).
country(jpn).
country(jey).
country(jor).
country(kaz).
country(ken).
country(kwt).
country(kgz).
country(lao).
country(lva).
country(lbn).
country(lso).
country(lbr).
country(lby).
country(lie).
country(ltu).
country(lux).
country(mkd).
country(mdg).
country(mwi).
country(mys).
country(mdv).
country(mli).
country(mlt).
country(mrt).
country(mus).
country(myt).
country(mex).
country(mda).
country(mco).
country(mng).
country(mne).
country(mar).
country(moz).
country(mmr).
country(nam).
country(npl).
country(nld).
country(nic).
country(ner).
country(nga).
country(prk).
country(nor).
country(omn).
country(pak).
country(pse).
country(pan).
country(pry).
country(per).
country(phl).
country(pol).
country(prt).
country(qat).
country(rou).
country(rus).
country(rwa).
country(shn).
country(smr).
country(wsm).
country(stp).
country(sau).
country(sen).
country(srb).
country(syc).
country(sle).
country(sgp).
country(svk).
country(svn).
country(som).
country(zaf).
country(kor).
country(ssd).
country(esp).
country(lka).
country(sdn).
country(sur).
country(swz).
country(swe).
country(che).
country(syr).
country(tjk).
country(tha).
country(tls).
country(tgo).
country(tun).
country(tur).
country(tkm).
country(uga).
country(ukr).
country(are).
country(gbr).
country(tza).
country(usa).
country(ury).
country(uzb).
country(ven).
country(vnm).
country(esh).
country(yem).
country(zmb).
country(zwe).
