:- module(facts_is_in, []).

is_in(zwe, africa).
is_in(zmb, africa).
is_in(esh, africa).
is_in(tza, africa).
is_in(uga, africa).
is_in(tun, africa).
is_in(tgo, africa).
is_in(swz, africa).
is_in(sdn, africa).
is_in(ssd, africa).
is_in(zaf, africa).
is_in(som, africa).
is_in(sle, africa).
is_in(syc, africa).
is_in(sen, africa).
is_in(wsm, africa).
is_in(shn, africa).
is_in(rwa, africa).
is_in(nga, africa).
is_in(ner, africa).
is_in(nam, africa).
is_in(moz, africa).
is_in(mar, africa).
is_in(myt, africa).
is_in(mus, africa).
is_in(mrt, africa).
is_in(mli, africa).
is_in(mwi, africa).
is_in(mdg, africa).
is_in(lby, africa).
is_in(lbr, africa).
is_in(lso, africa).
is_in(ken, africa).
is_in(gnb, africa).
is_in(gin, africa).
is_in(gha, africa).
is_in(gmb, africa).
is_in(gab, africa).
is_in(eth, africa).
is_in(eri, africa).
is_in(gnq, africa).
is_in(egy, africa).
is_in(dji, africa).
is_in(cod, africa).
is_in(civ, africa).
is_in(cog, africa).
is_in(com, africa).
is_in(tcd, africa).
is_in(caf, africa).
is_in(cmr, africa).
is_in(cpv, africa).
is_in(bdi, africa).
is_in(bfa, africa).
is_in(bwa, africa).
is_in(ben, africa).
is_in(ago, africa).
is_in(dza, africa).
is_in(afg, asia).
is_in(arm, asia).
is_in(aze, asia).
is_in(bhr, asia).
is_in(bgd, asia).
is_in(btn, asia).
is_in(brn, asia).
is_in(khm, asia).
is_in(chn, asia).
is_in(cyp, asia).
is_in(kor, asia).
is_in(geo, asia).
is_in(ind, asia).
is_in(idn, asia).
is_in(irn, asia).
is_in(irq, asia).
is_in(isr, asia).
is_in(jpn, asia).
is_in(jor, asia).
is_in(kaz, asia).
is_in(kwt, asia).
is_in(kgz, asia).
is_in(lao, asia).
is_in(lbn, asia).
is_in(mys, asia).
is_in(mdv, asia).
is_in(mng, asia).
is_in(mmr, asia).
is_in(npl, asia).
is_in(omn, asia).
is_in(pak, asia).
is_in(phl, asia).
is_in(qat, asia).
is_in(prk, asia).
is_in(sau, asia).
is_in(sgp, asia).
is_in(lka, asia).
is_in(pse, asia).
is_in(syr, asia).
is_in(tjk, asia).
is_in(tha, asia).
is_in(tls, asia).
is_in(tur, asia).
is_in(tkm, asia).
is_in(are, asia).
is_in(uzb, asia).
is_in(vnm, asia).
is_in(yem, asia).
is_in(alb, europe).
is_in(and, europe).
is_in(aut, europe).
is_in(blr, europe).
is_in(bel, europe).
is_in(bih, europe).
is_in(bgr, europe).
is_in(hrv, europe).
is_in(cze, europe).
is_in(dnk, europe).
is_in(est, europe).
is_in(fin, europe).
is_in(fra, europe).
is_in(deu, europe).
is_in(gib, europe).
is_in(grc, europe).
is_in(ggy, europe).
is_in(hun, europe).
is_in(isl, europe).
is_in(irl, europe).
is_in(ita, europe).
is_in(jey, europe).
is_in(lva, europe).
is_in(lie, europe).
is_in(ltu, europe).
is_in(lux, europe).
is_in(mlt, europe).
is_in(mco, europe).
is_in(mne, europe).
is_in(nld, europe).
is_in(nor, europe).
is_in(pol, europe).
is_in(prt, europe).
is_in(mda, europe).
is_in(rou, europe).
is_in(rus, europe).
is_in(smr, europe).
is_in(stp, europe).
is_in(srb, europe).
is_in(svk, europe).
is_in(svn, europe).
is_in(esp, europe).
is_in(swe, europe).
is_in(che, europe).
is_in(mkd, europe).
is_in(ukr, europe).
is_in(gbr, europe).
is_in(blz, northamerica).
is_in(bmu, northamerica).
is_in(can, northamerica).
is_in(cri, northamerica).
is_in(slv, northamerica).
is_in(grl, northamerica).
is_in(gtm, northamerica).
is_in(hnd, northamerica).
is_in(mex, northamerica).
is_in(nic, northamerica).
is_in(pan, northamerica).
is_in(usa, northamerica).
is_in(arg, southamerica).
is_in(bol, southamerica).
is_in(bra, southamerica).
is_in(chl, southamerica).
is_in(col, southamerica).
is_in(ecu, southamerica).
is_in(guy, southamerica).
is_in(pry, southamerica).
is_in(per, southamerica).
is_in(sur, southamerica).
is_in(ury, southamerica).
is_in(ven, southamerica).
