:- module(hasmountain,[]).
hasmountain(alb).
hasmountain(dza).
hasmountain(arg).
hasmountain(bgd).
hasmountain(bel).
hasmountain(blz).
hasmountain(ben).
hasmountain(bih).
hasmountain(bra).
hasmountain(brn).
hasmountain(bgr).
hasmountain(cpv).
hasmountain(khm).
hasmountain(cmr).
hasmountain(can).
hasmountain(chl).
hasmountain(chn).
hasmountain(col).
hasmountain(com).
hasmountain(cog).
hasmountain(cri).
hasmountain(civ).
hasmountain(hrv).
hasmountain(cyp).
hasmountain(cod).
hasmountain(dnk).
hasmountain(dji).
hasmountain(ecu).
hasmountain(egy).
hasmountain(slv).
hasmountain(gnq).
hasmountain(eri).
hasmountain(fin).
hasmountain(fra).
hasmountain(gab).
hasmountain(geo).
hasmountain(deu).
hasmountain(gha).
hasmountain(gib).
hasmountain(grc).
hasmountain(grl).
hasmountain(gtm).
hasmountain(ggy).
hasmountain(gin).
hasmountain(guy).
hasmountain(hnd).
hasmountain(isl).
hasmountain(ind).
hasmountain(idn).
hasmountain(irn).
hasmountain(irq).
hasmountain(irl).
hasmountain(isr).
hasmountain(ita).
hasmountain(jpn).
hasmountain(jey).
hasmountain(jor).
hasmountain(ken).
hasmountain(lbn).
hasmountain(lbr).
hasmountain(lby).
hasmountain(mdg).
hasmountain(mys).
hasmountain(mrt).
hasmountain(mus).
hasmountain(myt).
hasmountain(mex).
hasmountain(mco).
hasmountain(mne).
hasmountain(mar).
hasmountain(moz).
hasmountain(mmr).
hasmountain(nam).
hasmountain(nic).
hasmountain(nga).
hasmountain(prk).
hasmountain(nor).
hasmountain(omn).
hasmountain(pak).
hasmountain(pse).
hasmountain(pan).
hasmountain(per).
hasmountain(phl).
hasmountain(pol).
hasmountain(prt).
hasmountain(rou).
hasmountain(rus).
hasmountain(shn).
hasmountain(wsm).
hasmountain(stp).
hasmountain(sau).
hasmountain(sen).
hasmountain(syc).
hasmountain(sle).
hasmountain(sgp).
hasmountain(svn).
hasmountain(som).
hasmountain(zaf).
hasmountain(kor).
hasmountain(esp).
hasmountain(lka).
hasmountain(sdn).
hasmountain(sur).
hasmountain(swe).
hasmountain(syr).
hasmountain(tha).
hasmountain(tls).
hasmountain(tgo).
hasmountain(tun).
hasmountain(tur).
hasmountain(ukr).
hasmountain(are).
hasmountain(gbr).
hasmountain(tza).
hasmountain(usa).
hasmountain(ury).
hasmountain(ven).
hasmountain(vnm).
hasmountain(esh).
hasmountain(yem).
hasmountain(afg).
hasmountain(and).
hasmountain(arm).
hasmountain(aut).
hasmountain(aze).
hasmountain(btn).
hasmountain(bol).
hasmountain(bwa).
hasmountain(bfa).
hasmountain(bdi).
hasmountain(caf).
hasmountain(tcd).
hasmountain(cze).
hasmountain(eth).
hasmountain(hun).
hasmountain(kaz).
hasmountain(kgz).
hasmountain(lao).
hasmountain(lso).
hasmountain(lie).
hasmountain(lux).
hasmountain(mkd).
hasmountain(mwi).
hasmountain(mli).
hasmountain(mda).
hasmountain(mng).
hasmountain(npl).
hasmountain(ner).
hasmountain(pry).
hasmountain(rwa).
hasmountain(smr).
hasmountain(srb).
hasmountain(svk).
hasmountain(ssd).
hasmountain(swz).
hasmountain(che).
hasmountain(tjk).
hasmountain(tkm).
hasmountain(uga).
hasmountain(uzb).
hasmountain(zmb).
hasmountain(zwe).
