:- use_module(hassea,[]).
:- use_module(isinfact,[]).
:- use_module(islock,[]).
:- use_module(hasmountain,[]).
:- use_module(nomountain,[]).
:- use_module(weather,[]).
:- use_module(country,[]).
:- use_module(continent,[]).
:- use_module(climate,[]).
:- use_module(activity,[]).
:- use_module(actrule,[]).
