:- module(weather,[]).
weather(1,afg,Rain).
weather(1,alb,Rain).
weather(1,dza,Rain).
weather(1,and,Snow).
weather(1,ago,Warm).
weather(1,arg,Warm).
weather(1,arm,Snow).
weather(1,aut,Snow).
weather(1,aze,Rain).
weather(1,bhr,Rain).
weather(1,bgd,Rain).
weather(1,blr,Snow).
weather(1,bel,Rain).
weather(1,blz,Warm).
weather(1,ben,Warm).
weather(1,bmu,Rain).
weather(1,btn,Rain).
weather(1,bol,Rain).
weather(1,bih,Rain).
weather(1,bwa,Warm).
weather(1,bra,Warm).
weather(1,brn,Warm).
weather(1,bgr,Snow).
weather(1,bfa,Warm).
weather(1,bdi,Warm).
weather(1,cpv,Warm).
weather(1,khm,Warm).
weather(1,cmr,Warm).
weather(1,can,Snow).
weather(1,caf,Warm).
weather(1,tcd,Warm).
weather(1,chl,Rain).
weather(1,chn,Snow).
weather(1,col,Warm).
weather(1,com,Warm).
weather(1,cog,Warm).
weather(1,cri,Rain).
weather(1,civ,Warm).
weather(1,hrv,Rain).
weather(1,cyp,Rain).
weather(1,cze,Snow).
weather(1,cod,Warm).
weather(1,dnk,Rain).
weather(1,dji,Warm).
weather(1,ecu,Warm).
weather(1,egy,Rain).
weather(1,slv,Warm).
weather(1,gnq,Warm).
weather(1,eri,Rain).
weather(1,est,Snow).
weather(1,eth,Rain).
weather(1,fin,Snow).
weather(1,fra,Rain).
weather(1,gab,Warm).
weather(1,gmb,Warm).
weather(1,geo,Rain).
weather(1,deu,Snow).
weather(1,gha,Warm).
weather(1,gib,Rain).
weather(1,grc,Rain).
weather(1,grl,Rain).
weather(1,gtm,Rain).
weather(1,ggy,Warm).
weather(1,gnb,Warm).
weather(1,gin,Warm).
weather(1,guy,Warm).
weather(1,hnd,Warm).
weather(1,hun,Snow).
weather(1,isl,Snow).
weather(1,ind,Rain).
weather(1,idn,Warm).
weather(1,irn,Rain).
weather(1,irq,Rain).
weather(1,irl,Rain).
weather(1,isr,Rain).
weather(1,ita,Rain).
weather(1,jpn,Rain).
weather(1,jey,Warm).
weather(1,jor,Rain).
weather(1,kaz,Snow).
weather(1,ken,Warm).
weather(1,kwt,Rain).
weather(1,kgz,Snow).
weather(1,lao,Warm).
weather(1,lva,Snow).
weather(1,lbn,Rain).
weather(1,lso,Rain).
weather(1,lbr,Warm).
weather(1,lby,Rain).
weather(1,lie,Rain).
weather(1,ltu,Snow).
weather(1,lux,Rain).
weather(1,mkd,Rain).
weather(1,mdg,Warm).
weather(1,mwi,Warm).
weather(1,mys,Warm).
weather(1,mdv,Warm).
weather(1,mli,Warm).
weather(1,mlt,Rain).
weather(1,mrt,Warm).
weather(1,mus,Warm).
weather(1,myt,Warm).
weather(1,mex,Rain).
weather(1,mda,Snow).
weather(1,mco,Rain).
weather(1,mng,Snow).
weather(1,mne,Rain).
weather(1,mar,Rain).
weather(1,moz,Warm).
weather(1,mmr,Warm).
weather(1,nam,Warm).
weather(1,npl,Rain).
weather(1,nld,Rain).
weather(1,nic,Warm).
weather(1,ner,Warm).
weather(1,nga,Warm).
weather(1,prk,Snow).
weather(1,nor,Snow).
weather(1,omn,Rain).
weather(1,pak,Rain).
weather(1,pse,Warm).
weather(1,pan,Warm).
weather(1,pry,Warm).
weather(1,per,Rain).
weather(1,phl,Warm).
weather(1,pol,Snow).
weather(1,prt,Rain).
weather(1,qat,Rain).
weather(1,rou,Snow).
weather(1,rus,Snow).
weather(1,rwa,Rain).
weather(1,shn,Rain).
weather(1,smr,Rain).
weather(1,wsm,Warm).
weather(1,stp,Warm).
weather(1,sau,Rain).
weather(1,sen,Warm).
weather(1,srb,Snow).
weather(1,syc,Warm).
weather(1,sle,Warm).
weather(1,sgp,Warm).
weather(1,svk,Snow).
weather(1,svn,Snow).
weather(1,som,Warm).
weather(1,zaf,Warm).
weather(1,kor,Snow).
weather(1,ssd,Warm).
weather(1,esp,Rain).
weather(1,lka,Warm).
weather(1,sdn,Warm).
weather(1,sur,Warm).
weather(1,swz,Warm).
weather(1,swe,Snow).
weather(1,che,Snow).
weather(1,syr,Rain).
weather(1,tjk,Snow).
weather(1,tha,Warm).
weather(1,tls,Warm).
weather(1,tgo,Warm).
weather(1,tun,Rain).
weather(1,tur,Rain).
weather(1,tkm,Rain).
weather(1,uga,Warm).
weather(1,ukr,Snow).
weather(1,are,Rain).
weather(1,gbr,Rain).
weather(1,tza,Warm).
weather(1,usa,Rain).
weather(1,ury,Warm).
weather(1,uzb,Snow).
weather(1,ven,Warm).
weather(1,vnm,Warm).
weather(1,esh,Rain).
weather(1,yem,Warm).
weather(1,zmb,Warm).
weather(1,zwe,Warm).
weather(2,afg,Rain).
weather(2,alb,Rain).
weather(2,dza,Rain).
weather(2,and,Snow).
weather(2,ago,Warm).
weather(2,arg,Warm).
weather(2,arm,Snow).
weather(2,aut,Snow).
weather(2,aze,Rain).
weather(2,bhr,Rain).
weather(2,bgd,Warm).
weather(2,blr,Snow).
weather(2,bel,Rain).
weather(2,blz,Warm).
weather(2,ben,Warm).
weather(2,bmu,Rain).
weather(2,btn,Rain).
weather(2,bol,Rain).
weather(2,bih,Rain).
weather(2,bwa,Warm).
weather(2,bra,Warm).
weather(2,brn,Warm).
weather(2,bgr,Rain).
weather(2,bfa,Warm).
weather(2,bdi,Warm).
weather(2,cpv,Warm).
weather(2,khm,Warm).
weather(2,cmr,Warm).
weather(2,can,Snow).
weather(2,caf,Warm).
weather(2,tcd,Warm).
weather(2,chl,Rain).
weather(2,chn,Rain).
weather(2,col,Warm).
weather(2,com,Warm).
weather(2,cog,Warm).
weather(2,cri,Rain).
weather(2,civ,Warm).
weather(2,hrv,Rain).
weather(2,cyp,Rain).
weather(2,cze,Snow).
weather(2,cod,Warm).
weather(2,dnk,Rain).
weather(2,dji,Warm).
weather(2,ecu,Warm).
weather(2,egy,Rain).
weather(2,slv,Warm).
weather(2,gnq,Warm).
weather(2,eri,Warm).
weather(2,est,Snow).
weather(2,eth,Rain).
weather(2,fin,Snow).
weather(2,fra,Rain).
weather(2,gab,Warm).
weather(2,gmb,Warm).
weather(2,geo,Rain).
weather(2,deu,Rain).
weather(2,gha,Warm).
weather(2,gib,Rain).
weather(2,grc,Rain).
weather(2,grl,Rain).
weather(2,gtm,Rain).
weather(2,ggy,Warm).
weather(2,gnb,Warm).
weather(2,gin,Warm).
weather(2,guy,Warm).
weather(2,hnd,Warm).
weather(2,hun,Rain).
weather(2,isl,Snow).
weather(2,ind,Rain).
weather(2,idn,Warm).
weather(2,irn,Rain).
weather(2,irq,Rain).
weather(2,irl,Rain).
weather(2,isr,Rain).
weather(2,ita,Rain).
weather(2,jpn,Rain).
weather(2,jey,Warm).
weather(2,jor,Rain).
weather(2,kaz,Snow).
weather(2,ken,Warm).
weather(2,kwt,Rain).
weather(2,kgz,Snow).
weather(2,lao,Warm).
weather(2,lva,Snow).
weather(2,lbn,Rain).
weather(2,lso,Rain).
weather(2,lbr,Warm).
weather(2,lby,Rain).
weather(2,lie,Rain).
weather(2,ltu,Snow).
weather(2,lux,Rain).
weather(2,mkd,Rain).
weather(2,mdg,Warm).
weather(2,mwi,Warm).
weather(2,mys,Warm).
weather(2,mdv,Warm).
weather(2,mli,Warm).
weather(2,mlt,Rain).
weather(2,mrt,Warm).
weather(2,mus,Warm).
weather(2,myt,Warm).
weather(2,mex,Rain).
weather(2,mda,Snow).
weather(2,mco,Rain).
weather(2,mng,Snow).
weather(2,mne,Rain).
weather(2,mar,Rain).
weather(2,moz,Warm).
weather(2,mmr,Warm).
weather(2,nam,Warm).
weather(2,npl,Rain).
weather(2,nld,Rain).
weather(2,nic,Warm).
weather(2,ner,Warm).
weather(2,nga,Warm).
weather(2,prk,Snow).
weather(2,nor,Snow).
weather(2,omn,Warm).
weather(2,pak,Rain).
weather(2,pse,Warm).
weather(2,pan,Warm).
weather(2,pry,Warm).
weather(2,per,Rain).
weather(2,phl,Warm).
weather(2,pol,Snow).
weather(2,prt,Rain).
weather(2,qat,Rain).
weather(2,rou,Snow).
weather(2,rus,Snow).
weather(2,rwa,Rain).
weather(2,shn,Rain).
weather(2,smr,Rain).
weather(2,wsm,Warm).
weather(2,stp,Warm).
weather(2,sau,Rain).
weather(2,sen,Warm).
weather(2,srb,Rain).
weather(2,syc,Warm).
weather(2,sle,Warm).
weather(2,sgp,Warm).
weather(2,svk,Snow).
weather(2,svn,Snow).
weather(2,som,Warm).
weather(2,zaf,Warm).
weather(2,kor,Rain).
weather(2,ssd,Warm).
weather(2,esp,Rain).
weather(2,lka,Warm).
weather(2,sdn,Warm).
weather(2,sur,Warm).
weather(2,swz,Warm).
weather(2,swe,Snow).
weather(2,che,Snow).
weather(2,syr,Rain).
weather(2,tjk,Snow).
weather(2,tha,Warm).
weather(2,tls,Warm).
weather(2,tgo,Warm).
weather(2,tun,Rain).
weather(2,tur,Rain).
weather(2,tkm,Rain).
weather(2,uga,Warm).
weather(2,ukr,Snow).
weather(2,are,Rain).
weather(2,gbr,Rain).
weather(2,tza,Warm).
weather(2,usa,Rain).
weather(2,ury,Warm).
weather(2,uzb,Rain).
weather(2,ven,Warm).
weather(2,vnm,Warm).
weather(2,esh,Rain).
weather(2,yem,Warm).
weather(2,zmb,Warm).
weather(2,zwe,Warm).
weather(3,afg,Rain).
weather(3,alb,Rain).
weather(3,dza,Rain).
weather(3,and,Rain).
weather(3,ago,Warm).
weather(3,arg,Warm).
weather(3,arm,Rain).
weather(3,aut,Rain).
weather(3,aze,Rain).
weather(3,bhr,Warm).
weather(3,bgd,Warm).
weather(3,blr,Snow).
weather(3,bel,Rain).
weather(3,blz,Warm).
weather(3,ben,Warm).
weather(3,bmu,Rain).
weather(3,btn,Rain).
weather(3,bol,Rain).
weather(3,bih,Rain).
weather(3,bwa,Warm).
weather(3,bra,Warm).
weather(3,brn,Warm).
weather(3,bgr,Rain).
weather(3,bfa,Warm).
weather(3,bdi,Warm).
weather(3,cpv,Warm).
weather(3,khm,Warm).
weather(3,cmr,Warm).
weather(3,can,Snow).
weather(3,caf,Warm).
weather(3,tcd,Warm).
weather(3,chl,Rain).
weather(3,chn,Rain).
weather(3,col,Warm).
weather(3,com,Warm).
weather(3,cog,Warm).
weather(3,cri,Rain).
weather(3,civ,Warm).
weather(3,hrv,Rain).
weather(3,cyp,Rain).
weather(3,cze,Rain).
weather(3,cod,Warm).
weather(3,dnk,Rain).
weather(3,dji,Warm).
weather(3,ecu,Warm).
weather(3,egy,Rain).
weather(3,slv,Warm).
weather(3,gnq,Warm).
weather(3,eri,Warm).
weather(3,est,Snow).
weather(3,eth,Warm).
weather(3,fin,Snow).
weather(3,fra,Rain).
weather(3,gab,Warm).
weather(3,gmb,Warm).
weather(3,geo,Rain).
weather(3,deu,Rain).
weather(3,gha,Warm).
weather(3,gib,Rain).
weather(3,grc,Rain).
weather(3,grl,Warm).
weather(3,gtm,Warm).
weather(3,ggy,Warm).
weather(3,gnb,Warm).
weather(3,gin,Warm).
weather(3,guy,Warm).
weather(3,hnd,Warm).
weather(3,hun,Rain).
weather(3,isl,Snow).
weather(3,ind,Warm).
weather(3,idn,Warm).
weather(3,irn,Rain).
weather(3,irq,Rain).
weather(3,irl,Rain).
weather(3,isr,Rain).
weather(3,ita,Rain).
weather(3,jpn,Rain).
weather(3,jey,Warm).
weather(3,jor,Rain).
weather(3,kaz,Snow).
weather(3,ken,Warm).
weather(3,kwt,Rain).
weather(3,kgz,Rain).
weather(3,lao,Warm).
weather(3,lva,Snow).
weather(3,lbn,Rain).
weather(3,lso,Rain).
weather(3,lbr,Warm).
weather(3,lby,Rain).
weather(3,lie,Rain).
weather(3,ltu,Snow).
weather(3,lux,Rain).
weather(3,mkd,Rain).
weather(3,mdg,Warm).
weather(3,mwi,Warm).
weather(3,mys,Warm).
weather(3,mdv,Warm).
weather(3,mli,Warm).
weather(3,mlt,Rain).
weather(3,mrt,Warm).
weather(3,mus,Warm).
weather(3,myt,Warm).
weather(3,mex,Rain).
weather(3,mda,Rain).
weather(3,mco,Rain).
weather(3,mng,Snow).
weather(3,mne,Rain).
weather(3,mar,Rain).
weather(3,moz,Warm).
weather(3,mmr,Warm).
weather(3,nam,Warm).
weather(3,npl,Rain).
weather(3,nld,Rain).
weather(3,nic,Warm).
weather(3,ner,Warm).
weather(3,nga,Warm).
weather(3,prk,Rain).
weather(3,nor,Snow).
weather(3,omn,Warm).
weather(3,pak,Rain).
weather(3,pse,Warm).
weather(3,pan,Warm).
weather(3,pry,Warm).
weather(3,per,Rain).
weather(3,phl,Warm).
weather(3,pol,Rain).
weather(3,prt,Rain).
weather(3,qat,Warm).
weather(3,rou,Rain).
weather(3,rus,Snow).
weather(3,rwa,Rain).
weather(3,shn,Rain).
weather(3,smr,Rain).
weather(3,wsm,Warm).
weather(3,stp,Warm).
weather(3,sau,Warm).
weather(3,sen,Warm).
weather(3,srb,Rain).
weather(3,syc,Warm).
weather(3,sle,Warm).
weather(3,sgp,Warm).
weather(3,svk,Rain).
weather(3,svn,Rain).
weather(3,som,Warm).
weather(3,zaf,Warm).
weather(3,kor,Rain).
weather(3,ssd,Warm).
weather(3,esp,Rain).
weather(3,lka,Warm).
weather(3,sdn,Warm).
weather(3,sur,Warm).
weather(3,swz,Warm).
weather(3,swe,Snow).
weather(3,che,Rain).
weather(3,syr,Rain).
weather(3,tjk,Rain).
weather(3,tha,Warm).
weather(3,tls,Warm).
weather(3,tgo,Warm).
weather(3,tun,Rain).
weather(3,tur,Rain).
weather(3,tkm,Rain).
weather(3,uga,Warm).
weather(3,ukr,Rain).
weather(3,are,Warm).
weather(3,gbr,Rain).
weather(3,tza,Warm).
weather(3,usa,Rain).
weather(3,ury,Warm).
weather(3,uzb,Rain).
weather(3,ven,Warm).
weather(3,vnm,Warm).
weather(3,esh,Rain).
weather(3,yem,Warm).
weather(3,zmb,Warm).
weather(3,zwe,Warm).
weather(4,afg,Rain).
weather(4,alb,Rain).
weather(4,dza,Rain).
weather(4,and,Rain).
weather(4,ago,Warm).
weather(4,arg,Rain).
weather(4,arm,Rain).
weather(4,aut,Rain).
weather(4,aze,Rain).
weather(4,bhr,Warm).
weather(4,bgd,Warm).
weather(4,blr,Rain).
weather(4,bel,Rain).
weather(4,blz,Warm).
weather(4,ben,Warm).
weather(4,bmu,Rain).
weather(4,btn,Rain).
weather(4,bol,Rain).
weather(4,bih,Rain).
weather(4,bwa,Warm).
weather(4,bra,Warm).
weather(4,brn,Warm).
weather(4,bgr,Rain).
weather(4,bfa,Warm).
weather(4,bdi,Warm).
weather(4,cpv,Warm).
weather(4,khm,Warm).
weather(4,cmr,Warm).
weather(4,can,Rain).
weather(4,caf,Warm).
weather(4,tcd,Warm).
weather(4,chl,Rain).
weather(4,chn,Rain).
weather(4,col,Warm).
weather(4,com,Warm).
weather(4,cog,Warm).
weather(4,cri,Rain).
weather(4,civ,Warm).
weather(4,hrv,Rain).
weather(4,cyp,Rain).
weather(4,cze,Rain).
weather(4,cod,Warm).
weather(4,dnk,Rain).
weather(4,dji,Warm).
weather(4,ecu,Warm).
weather(4,egy,Warm).
weather(4,slv,Warm).
weather(4,gnq,Warm).
weather(4,eri,Warm).
weather(4,est,Rain).
weather(4,eth,Warm).
weather(4,fin,Rain).
weather(4,fra,Rain).
weather(4,gab,Warm).
weather(4,gmb,Warm).
weather(4,geo,Rain).
weather(4,deu,Rain).
weather(4,gha,Warm).
weather(4,gib,Rain).
weather(4,grc,Rain).
weather(4,grl,Warm).
weather(4,gtm,Warm).
weather(4,ggy,Warm).
weather(4,gnb,Warm).
weather(4,gin,Warm).
weather(4,guy,Warm).
weather(4,hnd,Warm).
weather(4,hun,Rain).
weather(4,isl,Rain).
weather(4,ind,Warm).
weather(4,idn,Warm).
weather(4,irn,Rain).
weather(4,irq,Warm).
weather(4,irl,Rain).
weather(4,isr,Rain).
weather(4,ita,Rain).
weather(4,jpn,Rain).
weather(4,jey,Warm).
weather(4,jor,Rain).
weather(4,kaz,Rain).
weather(4,ken,Warm).
weather(4,kwt,Warm).
weather(4,kgz,Rain).
weather(4,lao,Warm).
weather(4,lva,Rain).
weather(4,lbn,Rain).
weather(4,lso,Rain).
weather(4,lbr,Warm).
weather(4,lby,Rain).
weather(4,lie,Rain).
weather(4,ltu,Rain).
weather(4,lux,Rain).
weather(4,mkd,Rain).
weather(4,mdg,Warm).
weather(4,mwi,Warm).
weather(4,mys,Warm).
weather(4,mdv,Warm).
weather(4,mli,Warm).
weather(4,mlt,Rain).
weather(4,mrt,Warm).
weather(4,mus,Warm).
weather(4,myt,Warm).
weather(4,mex,Warm).
weather(4,mda,Rain).
weather(4,mco,Rain).
weather(4,mng,Rain).
weather(4,mne,Rain).
weather(4,mar,Rain).
weather(4,moz,Warm).
weather(4,mmr,Warm).
weather(4,nam,Warm).
weather(4,npl,Warm).
weather(4,nld,Rain).
weather(4,nic,Warm).
weather(4,ner,Warm).
weather(4,nga,Warm).
weather(4,prk,Rain).
weather(4,nor,Rain).
weather(4,omn,Warm).
weather(4,pak,Warm).
weather(4,pse,Warm).
weather(4,pan,Warm).
weather(4,pry,Warm).
weather(4,per,Rain).
weather(4,phl,Warm).
weather(4,pol,Rain).
weather(4,prt,Rain).
weather(4,qat,Warm).
weather(4,rou,Rain).
weather(4,rus,Snow).
weather(4,rwa,Rain).
weather(4,shn,Rain).
weather(4,smr,Rain).
weather(4,wsm,Warm).
weather(4,stp,Warm).
weather(4,sau,Warm).
weather(4,sen,Warm).
weather(4,srb,Rain).
weather(4,syc,Warm).
weather(4,sle,Warm).
weather(4,sgp,Warm).
weather(4,svk,Rain).
weather(4,svn,Rain).
weather(4,som,Warm).
weather(4,zaf,Rain).
weather(4,kor,Rain).
weather(4,ssd,Warm).
weather(4,esp,Rain).
weather(4,lka,Warm).
weather(4,sdn,Warm).
weather(4,sur,Warm).
weather(4,swz,Rain).
weather(4,swe,Rain).
weather(4,che,Rain).
weather(4,syr,Rain).
weather(4,tjk,Rain).
weather(4,tha,Warm).
weather(4,tls,Warm).
weather(4,tgo,Warm).
weather(4,tun,Rain).
weather(4,tur,Rain).
weather(4,tkm,Rain).
weather(4,uga,Warm).
weather(4,ukr,Rain).
weather(4,are,Warm).
weather(4,gbr,Rain).
weather(4,tza,Rain).
weather(4,usa,Rain).
weather(4,ury,Rain).
weather(4,uzb,Rain).
weather(4,ven,Warm).
weather(4,vnm,Warm).
weather(4,esh,Rain).
weather(4,yem,Warm).
weather(4,zmb,Warm).
weather(4,zwe,Rain).
weather(5,afg,Rain).
weather(5,alb,Rain).
weather(5,dza,Rain).
weather(5,and,Rain).
weather(5,ago,Warm).
weather(5,arg,Rain).
weather(5,arm,Rain).
weather(5,aut,Rain).
weather(5,aze,Rain).
weather(5,bhr,Warm).
weather(5,bgd,Warm).
weather(5,blr,Rain).
weather(5,bel,Rain).
weather(5,blz,Warm).
weather(5,ben,Warm).
weather(5,bmu,Warm).
weather(5,btn,Rain).
weather(5,bol,Rain).
weather(5,bih,Rain).
weather(5,bwa,Rain).
weather(5,bra,Warm).
weather(5,brn,Warm).
weather(5,bgr,Rain).
weather(5,bfa,Warm).
weather(5,bdi,Rain).
weather(5,cpv,Warm).
weather(5,khm,Warm).
weather(5,cmr,Warm).
weather(5,can,Rain).
weather(5,caf,Warm).
weather(5,tcd,Warm).
weather(5,chl,Rain).
weather(5,chn,Rain).
weather(5,col,Warm).
weather(5,com,Warm).
weather(5,cog,Warm).
weather(5,cri,Rain).
weather(5,civ,Warm).
weather(5,hrv,Rain).
weather(5,cyp,Warm).
weather(5,cze,Rain).
weather(5,cod,Warm).
weather(5,dnk,Rain).
weather(5,dji,Warm).
weather(5,ecu,Warm).
weather(5,egy,Warm).
weather(5,slv,Warm).
weather(5,gnq,Warm).
weather(5,eri,Warm).
weather(5,est,Rain).
weather(5,eth,Warm).
weather(5,fin,Rain).
weather(5,fra,Rain).
weather(5,gab,Warm).
weather(5,gmb,Warm).
weather(5,geo,Rain).
weather(5,deu,Rain).
weather(5,gha,Warm).
weather(5,gib,Rain).
weather(5,grc,Rain).
weather(5,grl,Warm).
weather(5,gtm,Warm).
weather(5,ggy,Warm).
weather(5,gnb,Warm).
weather(5,gin,Warm).
weather(5,guy,Warm).
weather(5,hnd,Warm).
weather(5,hun,Rain).
weather(5,isl,Rain).
weather(5,ind,Warm).
weather(5,idn,Warm).
weather(5,irn,Warm).
weather(5,irq,Warm).
weather(5,irl,Rain).
weather(5,isr,Warm).
weather(5,ita,Rain).
weather(5,jpn,Rain).
weather(5,jey,Warm).
weather(5,jor,Warm).
weather(5,kaz,Rain).
weather(5,ken,Warm).
weather(5,kwt,Warm).
weather(5,kgz,Rain).
weather(5,lao,Warm).
weather(5,lva,Rain).
weather(5,lbn,Rain).
weather(5,lso,Rain).
weather(5,lbr,Warm).
weather(5,lby,Warm).
weather(5,lie,Rain).
weather(5,ltu,Rain).
weather(5,lux,Rain).
weather(5,mkd,Rain).
weather(5,mdg,Warm).
weather(5,mwi,Rain).
weather(5,mys,Warm).
weather(5,mdv,Warm).
weather(5,mli,Warm).
weather(5,mlt,Rain).
weather(5,mrt,Warm).
weather(5,mus,Warm).
weather(5,myt,Warm).
weather(5,mex,Warm).
weather(5,mda,Rain).
weather(5,mco,Rain).
weather(5,mng,Rain).
weather(5,mne,Rain).
weather(5,mar,Rain).
weather(5,moz,Warm).
weather(5,mmr,Warm).
weather(5,nam,Rain).
weather(5,npl,Warm).
weather(5,nld,Rain).
weather(5,nic,Warm).
weather(5,ner,Warm).
weather(5,nga,Warm).
weather(5,prk,Rain).
weather(5,nor,Rain).
weather(5,omn,Warm).
weather(5,pak,Warm).
weather(5,pse,Warm).
weather(5,pan,Warm).
weather(5,pry,Rain).
weather(5,per,Rain).
weather(5,phl,Warm).
weather(5,pol,Rain).
weather(5,prt,Rain).
weather(5,qat,Warm).
weather(5,rou,Rain).
weather(5,rus,Rain).
weather(5,rwa,Rain).
weather(5,shn,Rain).
weather(5,smr,Rain).
weather(5,wsm,Warm).
weather(5,stp,Warm).
weather(5,sau,Warm).
weather(5,sen,Warm).
weather(5,srb,Rain).
weather(5,syc,Warm).
weather(5,sle,Warm).
weather(5,sgp,Warm).
weather(5,svk,Rain).
weather(5,svn,Rain).
weather(5,som,Warm).
weather(5,zaf,Rain).
weather(5,kor,Rain).
weather(5,ssd,Warm).
weather(5,esp,Rain).
weather(5,lka,Warm).
weather(5,sdn,Warm).
weather(5,sur,Warm).
weather(5,swz,Rain).
weather(5,swe,Rain).
weather(5,che,Rain).
weather(5,syr,Warm).
weather(5,tjk,Rain).
weather(5,tha,Warm).
weather(5,tls,Warm).
weather(5,tgo,Warm).
weather(5,tun,Rain).
weather(5,tur,Rain).
weather(5,tkm,Warm).
weather(5,uga,Warm).
weather(5,ukr,Rain).
weather(5,are,Warm).
weather(5,gbr,Rain).
weather(5,tza,Rain).
weather(5,usa,Rain).
weather(5,ury,Rain).
weather(5,uzb,Warm).
weather(5,ven,Warm).
weather(5,vnm,Warm).
weather(5,esh,Warm).
weather(5,yem,Warm).
weather(5,zmb,Rain).
weather(5,zwe,Rain).
weather(6,afg,Warm).
weather(6,alb,Warm).
weather(6,dza,Warm).
weather(6,and,Rain).
weather(6,ago,Rain).
weather(6,arg,Rain).
weather(6,arm,Rain).
weather(6,aut,Rain).
weather(6,aze,Warm).
weather(6,bhr,Warm).
weather(6,bgd,Warm).
weather(6,blr,Rain).
weather(6,bel,Rain).
weather(6,blz,Warm).
weather(6,ben,Warm).
weather(6,bmu,Warm).
weather(6,btn,Warm).
weather(6,bol,Rain).
weather(6,bih,Rain).
weather(6,bwa,Rain).
weather(6,bra,Warm).
weather(6,brn,Warm).
weather(6,bgr,Rain).
weather(6,bfa,Warm).
weather(6,bdi,Rain).
weather(6,cpv,Warm).
weather(6,khm,Warm).
weather(6,cmr,Warm).
weather(6,can,Rain).
weather(6,caf,Warm).
weather(6,tcd,Warm).
weather(6,chl,Rain).
weather(6,chn,Warm).
weather(6,col,Warm).
weather(6,com,Warm).
weather(6,cog,Warm).
weather(6,cri,Rain).
weather(6,civ,Warm).
weather(6,hrv,Rain).
weather(6,cyp,Warm).
weather(6,cze,Rain).
weather(6,cod,Warm).
weather(6,dnk,Rain).
weather(6,dji,Warm).
weather(6,ecu,Rain).
weather(6,egy,Warm).
weather(6,slv,Warm).
weather(6,gnq,Warm).
weather(6,eri,Warm).
weather(6,est,Rain).
weather(6,eth,Warm).
weather(6,fin,Rain).
weather(6,fra,Rain).
weather(6,gab,Warm).
weather(6,gmb,Warm).
weather(6,geo,Warm).
weather(6,deu,Rain).
weather(6,gha,Warm).
weather(6,gib,Warm).
weather(6,grc,Warm).
weather(6,grl,Warm).
weather(6,gtm,Warm).
weather(6,ggy,Warm).
weather(6,gnb,Warm).
weather(6,gin,Warm).
weather(6,guy,Warm).
weather(6,hnd,Warm).
weather(6,hun,Rain).
weather(6,isl,Rain).
weather(6,ind,Warm).
weather(6,idn,Warm).
weather(6,irn,Warm).
weather(6,irq,Warm).
weather(6,irl,Rain).
weather(6,isr,Warm).
weather(6,ita,Rain).
weather(6,jpn,Warm).
weather(6,jey,Warm).
weather(6,jor,Warm).
weather(6,kaz,Warm).
weather(6,ken,Rain).
weather(6,kwt,Warm).
weather(6,kgz,Rain).
weather(6,lao,Warm).
weather(6,lva,Rain).
weather(6,lbn,Warm).
weather(6,lso,Rain).
weather(6,lbr,Warm).
weather(6,lby,Warm).
weather(6,lie,Rain).
weather(6,ltu,Rain).
weather(6,lux,Rain).
weather(6,mkd,Rain).
weather(6,mdg,Rain).
weather(6,mwi,Rain).
weather(6,mys,Warm).
weather(6,mdv,Warm).
weather(6,mli,Warm).
weather(6,mlt,Warm).
weather(6,mrt,Warm).
weather(6,mus,Warm).
weather(6,myt,Warm).
weather(6,mex,Warm).
weather(6,mda,Rain).
weather(6,mco,Rain).
weather(6,mng,Rain).
weather(6,mne,Rain).
weather(6,mar,Warm).
weather(6,moz,Warm).
weather(6,mmr,Warm).
weather(6,nam,Rain).
weather(6,npl,Warm).
weather(6,nld,Rain).
weather(6,nic,Warm).
weather(6,ner,Warm).
weather(6,nga,Warm).
weather(6,prk,Rain).
weather(6,nor,Rain).
weather(6,omn,Warm).
weather(6,pak,Warm).
weather(6,pse,Warm).
weather(6,pan,Warm).
weather(6,pry,Rain).
weather(6,per,Rain).
weather(6,phl,Warm).
weather(6,pol,Rain).
weather(6,prt,Rain).
weather(6,qat,Warm).
weather(6,rou,Rain).
weather(6,rus,Rain).
weather(6,rwa,Rain).
weather(6,shn,Rain).
weather(6,smr,Rain).
weather(6,wsm,Warm).
weather(6,stp,Warm).
weather(6,sau,Warm).
weather(6,sen,Warm).
weather(6,srb,Rain).
weather(6,syc,Warm).
weather(6,sle,Warm).
weather(6,sgp,Warm).
weather(6,svk,Rain).
weather(6,svn,Rain).
weather(6,som,Warm).
weather(6,zaf,Rain).
weather(6,kor,Warm).
weather(6,ssd,Warm).
weather(6,esp,Rain).
weather(6,lka,Warm).
weather(6,sdn,Warm).
weather(6,sur,Warm).
weather(6,swz,Rain).
weather(6,swe,Rain).
weather(6,che,Rain).
weather(6,syr,Warm).
weather(6,tjk,Warm).
weather(6,tha,Warm).
weather(6,tls,Warm).
weather(6,tgo,Warm).
weather(6,tun,Warm).
weather(6,tur,Rain).
weather(6,tkm,Warm).
weather(6,uga,Warm).
weather(6,ukr,Rain).
weather(6,are,Warm).
weather(6,gbr,Rain).
weather(6,tza,Rain).
weather(6,usa,Warm).
weather(6,ury,Rain).
weather(6,uzb,Warm).
weather(6,ven,Warm).
weather(6,vnm,Warm).
weather(6,esh,Warm).
weather(6,yem,Warm).
weather(6,zmb,Rain).
weather(6,zwe,Rain).
weather(7,afg,Warm).
weather(7,alb,Warm).
weather(7,dza,Warm).
weather(7,and,Rain).
weather(7,ago,Rain).
weather(7,arg,Rain).
weather(7,arm,Rain).
weather(7,aut,Rain).
weather(7,aze,Warm).
weather(7,bhr,Warm).
weather(7,bgd,Warm).
weather(7,blr,Rain).
weather(7,bel,Rain).
weather(7,blz,Warm).
weather(7,ben,Warm).
weather(7,bmu,Warm).
weather(7,btn,Rain).
weather(7,bol,Rain).
weather(7,bih,Rain).
weather(7,bwa,Rain).
weather(7,bra,Warm).
weather(7,brn,Warm).
weather(7,bgr,Rain).
weather(7,bfa,Warm).
weather(7,bdi,Rain).
weather(7,cpv,Warm).
weather(7,khm,Warm).
weather(7,cmr,Warm).
weather(7,can,Rain).
weather(7,caf,Warm).
weather(7,tcd,Warm).
weather(7,chl,Rain).
weather(7,chn,Warm).
weather(7,col,Warm).
weather(7,com,Warm).
weather(7,cog,Warm).
weather(7,cri,Warm).
weather(7,civ,Warm).
weather(7,hrv,Warm).
weather(7,cyp,Warm).
weather(7,cze,Rain).
weather(7,cod,Warm).
weather(7,dnk,Rain).
weather(7,dji,Warm).
weather(7,ecu,Rain).
weather(7,egy,Warm).
weather(7,slv,Warm).
weather(7,gnq,Warm).
weather(7,eri,Warm).
weather(7,est,Rain).
weather(7,eth,Rain).
weather(7,fin,Rain).
weather(7,fra,Rain).
weather(7,gab,Warm).
weather(7,gmb,Warm).
weather(7,geo,Warm).
weather(7,deu,Rain).
weather(7,gha,Warm).
weather(7,gib,Warm).
weather(7,grc,Warm).
weather(7,grl,Warm).
weather(7,gtm,Warm).
weather(7,ggy,Warm).
weather(7,gnb,Warm).
weather(7,gin,Warm).
weather(7,guy,Warm).
weather(7,hnd,Warm).
weather(7,hun,Warm).
weather(7,isl,Rain).
weather(7,ind,Warm).
weather(7,idn,Warm).
weather(7,irn,Warm).
weather(7,irq,Warm).
weather(7,irl,Rain).
weather(7,isr,Warm).
weather(7,ita,Warm).
weather(7,jpn,Warm).
weather(7,jey,Warm).
weather(7,jor,Warm).
weather(7,kaz,Warm).
weather(7,ken,Rain).
weather(7,kwt,Warm).
weather(7,kgz,Warm).
weather(7,lao,Warm).
weather(7,lva,Rain).
weather(7,lbn,Warm).
weather(7,lso,Rain).
weather(7,lbr,Warm).
weather(7,lby,Warm).
weather(7,lie,Rain).
weather(7,ltu,Rain).
weather(7,lux,Rain).
weather(7,mkd,Warm).
weather(7,mdg,Rain).
weather(7,mwi,Rain).
weather(7,mys,Warm).
weather(7,mdv,Warm).
weather(7,mli,Warm).
weather(7,mlt,Warm).
weather(7,mrt,Warm).
weather(7,mus,Warm).
weather(7,myt,Warm).
weather(7,mex,Warm).
weather(7,mda,Warm).
weather(7,mco,Rain).
weather(7,mng,Rain).
weather(7,mne,Warm).
weather(7,mar,Warm).
weather(7,moz,Rain).
weather(7,mmr,Warm).
weather(7,nam,Rain).
weather(7,npl,Warm).
weather(7,nld,Rain).
weather(7,nic,Warm).
weather(7,ner,Warm).
weather(7,nga,Warm).
weather(7,prk,Warm).
weather(7,nor,Rain).
weather(7,omn,Warm).
weather(7,pak,Warm).
weather(7,pse,Warm).
weather(7,pan,Warm).
weather(7,pry,Rain).
weather(7,per,Rain).
weather(7,phl,Warm).
weather(7,pol,Rain).
weather(7,prt,Warm).
weather(7,qat,Warm).
weather(7,rou,Rain).
weather(7,rus,Rain).
weather(7,rwa,Rain).
weather(7,shn,Rain).
weather(7,smr,Rain).
weather(7,wsm,Warm).
weather(7,stp,Warm).
weather(7,sau,Warm).
weather(7,sen,Warm).
weather(7,srb,Warm).
weather(7,syc,Warm).
weather(7,sle,Warm).
weather(7,sgp,Warm).
weather(7,svk,Rain).
weather(7,svn,Rain).
weather(7,som,Warm).
weather(7,zaf,Rain).
weather(7,kor,Warm).
weather(7,ssd,Warm).
weather(7,esp,Warm).
weather(7,lka,Warm).
weather(7,sdn,Warm).
weather(7,sur,Warm).
weather(7,swz,Rain).
weather(7,swe,Rain).
weather(7,che,Rain).
weather(7,syr,Warm).
weather(7,tjk,Warm).
weather(7,tha,Warm).
weather(7,tls,Warm).
weather(7,tgo,Warm).
weather(7,tun,Warm).
weather(7,tur,Warm).
weather(7,tkm,Warm).
weather(7,uga,Warm).
weather(7,ukr,Warm).
weather(7,are,Warm).
weather(7,gbr,Rain).
weather(7,tza,Rain).
weather(7,usa,Warm).
weather(7,ury,Rain).
weather(7,uzb,Warm).
weather(7,ven,Warm).
weather(7,vnm,Warm).
weather(7,esh,Warm).
weather(7,yem,Warm).
weather(7,zmb,Rain).
weather(7,zwe,Rain).
weather(8,afg,Warm).
weather(8,alb,Warm).
weather(8,dza,Warm).
weather(8,and,Rain).
weather(8,ago,Rain).
weather(8,arg,Rain).
weather(8,arm,Rain).
weather(8,aut,Rain).
weather(8,aze,Warm).
weather(8,bhr,Warm).
weather(8,bgd,Warm).
weather(8,blr,Rain).
weather(8,bel,Rain).
weather(8,blz,Warm).
weather(8,ben,Warm).
weather(8,bmu,Warm).
weather(8,btn,Warm).
weather(8,bol,Rain).
weather(8,bih,Rain).
weather(8,bwa,Rain).
weather(8,bra,Warm).
weather(8,brn,Warm).
weather(8,bgr,Rain).
weather(8,bfa,Warm).
weather(8,bdi,Warm).
weather(8,cpv,Warm).
weather(8,khm,Warm).
weather(8,cmr,Warm).
weather(8,can,Rain).
weather(8,caf,Warm).
weather(8,tcd,Warm).
weather(8,chl,Rain).
weather(8,chn,Warm).
weather(8,col,Warm).
weather(8,com,Warm).
weather(8,cog,Warm).
weather(8,cri,Warm).
weather(8,civ,Warm).
weather(8,hrv,Warm).
weather(8,cyp,Warm).
weather(8,cze,Rain).
weather(8,cod,Warm).
weather(8,dnk,Rain).
weather(8,dji,Warm).
weather(8,ecu,Rain).
weather(8,egy,Warm).
weather(8,slv,Warm).
weather(8,gnq,Warm).
weather(8,eri,Warm).
weather(8,est,Rain).
weather(8,eth,Rain).
weather(8,fin,Rain).
weather(8,fra,Rain).
weather(8,gab,Warm).
weather(8,gmb,Warm).
weather(8,geo,Warm).
weather(8,deu,Rain).
weather(8,gha,Warm).
weather(8,gib,Warm).
weather(8,grc,Warm).
weather(8,grl,Warm).
weather(8,gtm,Warm).
weather(8,ggy,Warm).
weather(8,gnb,Warm).
weather(8,gin,Warm).
weather(8,guy,Warm).
weather(8,hnd,Warm).
weather(8,hun,Rain).
weather(8,isl,Rain).
weather(8,ind,Warm).
weather(8,idn,Warm).
weather(8,irn,Warm).
weather(8,irq,Warm).
weather(8,irl,Rain).
weather(8,isr,Warm).
weather(8,ita,Warm).
weather(8,jpn,Warm).
weather(8,jey,Warm).
weather(8,jor,Warm).
weather(8,kaz,Warm).
weather(8,ken,Rain).
weather(8,kwt,Warm).
weather(8,kgz,Warm).
weather(8,lao,Warm).
weather(8,lva,Rain).
weather(8,lbn,Warm).
weather(8,lso,Rain).
weather(8,lbr,Warm).
weather(8,lby,Warm).
weather(8,lie,Rain).
weather(8,ltu,Rain).
weather(8,lux,Rain).
weather(8,mkd,Warm).
weather(8,mdg,Rain).
weather(8,mwi,Rain).
weather(8,mys,Warm).
weather(8,mdv,Warm).
weather(8,mli,Warm).
weather(8,mlt,Warm).
weather(8,mrt,Warm).
weather(8,mus,Warm).
weather(8,myt,Warm).
weather(8,mex,Warm).
weather(8,mda,Warm).
weather(8,mco,Warm).
weather(8,mng,Rain).
weather(8,mne,Warm).
weather(8,mar,Warm).
weather(8,moz,Warm).
weather(8,mmr,Warm).
weather(8,nam,Rain).
weather(8,npl,Warm).
weather(8,nld,Rain).
weather(8,nic,Warm).
weather(8,ner,Warm).
weather(8,nga,Warm).
weather(8,prk,Warm).
weather(8,nor,Rain).
weather(8,omn,Warm).
weather(8,pak,Warm).
weather(8,pse,Warm).
weather(8,pan,Warm).
weather(8,pry,Rain).
weather(8,per,Rain).
weather(8,phl,Warm).
weather(8,pol,Rain).
weather(8,prt,Warm).
weather(8,qat,Warm).
weather(8,rou,Rain).
weather(8,rus,Rain).
weather(8,rwa,Rain).
weather(8,shn,Rain).
weather(8,smr,Warm).
weather(8,wsm,Warm).
weather(8,stp,Warm).
weather(8,sau,Warm).
weather(8,sen,Warm).
weather(8,srb,Warm).
weather(8,syc,Warm).
weather(8,sle,Warm).
weather(8,sgp,Warm).
weather(8,svk,Rain).
weather(8,svn,Rain).
weather(8,som,Warm).
weather(8,zaf,Rain).
weather(8,kor,Warm).
weather(8,ssd,Warm).
weather(8,esp,Warm).
weather(8,lka,Warm).
weather(8,sdn,Warm).
weather(8,sur,Warm).
weather(8,swz,Rain).
weather(8,swe,Rain).
weather(8,che,Rain).
weather(8,syr,Warm).
weather(8,tjk,Warm).
weather(8,tha,Warm).
weather(8,tls,Warm).
weather(8,tgo,Warm).
weather(8,tun,Warm).
weather(8,tur,Warm).
weather(8,tkm,Warm).
weather(8,uga,Warm).
weather(8,ukr,Rain).
weather(8,are,Warm).
weather(8,gbr,Rain).
weather(8,tza,Rain).
weather(8,usa,Warm).
weather(8,ury,Rain).
weather(8,uzb,Warm).
weather(8,ven,Warm).
weather(8,vnm,Warm).
weather(8,esh,Warm).
weather(8,yem,Warm).
weather(8,zmb,Rain).
weather(8,zwe,Rain).
weather(9,afg,Warm).
weather(9,alb,Rain).
weather(9,dza,Warm).
weather(9,and,Rain).
weather(9,ago,Warm).
weather(9,arg,Rain).
weather(9,arm,Rain).
weather(9,aut,Rain).
weather(9,aze,Warm).
weather(9,bhr,Warm).
weather(9,bgd,Warm).
weather(9,blr,Rain).
weather(9,bel,Rain).
weather(9,blz,Warm).
weather(9,ben,Warm).
weather(9,bmu,Warm).
weather(9,btn,Warm).
weather(9,bol,Rain).
weather(9,bih,Rain).
weather(9,bwa,Warm).
weather(9,bra,Warm).
weather(9,brn,Warm).
weather(9,bgr,Rain).
weather(9,bfa,Warm).
weather(9,bdi,Warm).
weather(9,cpv,Warm).
weather(9,khm,Warm).
weather(9,cmr,Warm).
weather(9,can,Rain).
weather(9,caf,Warm).
weather(9,tcd,Warm).
weather(9,chl,Rain).
weather(9,chn,Warm).
weather(9,col,Warm).
weather(9,com,Warm).
weather(9,cog,Warm).
weather(9,cri,Rain).
weather(9,civ,Warm).
weather(9,hrv,Rain).
weather(9,cyp,Warm).
weather(9,cze,Rain).
weather(9,cod,Warm).
weather(9,dnk,Rain).
weather(9,dji,Warm).
weather(9,ecu,Rain).
weather(9,egy,Warm).
weather(9,slv,Warm).
weather(9,gnq,Warm).
weather(9,eri,Warm).
weather(9,est,Rain).
weather(9,eth,Rain).
weather(9,fin,Rain).
weather(9,fra,Rain).
weather(9,gab,Warm).
weather(9,gmb,Warm).
weather(9,geo,Rain).
weather(9,deu,Rain).
weather(9,gha,Warm).
weather(9,gib,Warm).
weather(9,grc,Warm).
weather(9,grl,Warm).
weather(9,gtm,Warm).
weather(9,ggy,Warm).
weather(9,gnb,Warm).
weather(9,gin,Warm).
weather(9,guy,Warm).
weather(9,hnd,Warm).
weather(9,hun,Rain).
weather(9,isl,Rain).
weather(9,ind,Warm).
weather(9,idn,Warm).
weather(9,irn,Warm).
weather(9,irq,Warm).
weather(9,irl,Rain).
weather(9,isr,Warm).
weather(9,ita,Rain).
weather(9,jpn,Warm).
weather(9,jey,Warm).
weather(9,jor,Warm).
weather(9,kaz,Rain).
weather(9,ken,Warm).
weather(9,kwt,Warm).
weather(9,kgz,Rain).
weather(9,lao,Warm).
weather(9,lva,Rain).
weather(9,lbn,Warm).
weather(9,lso,Rain).
weather(9,lbr,Warm).
weather(9,lby,Warm).
weather(9,lie,Rain).
weather(9,ltu,Rain).
weather(9,lux,Rain).
weather(9,mkd,Rain).
weather(9,mdg,Warm).
weather(9,mwi,Warm).
weather(9,mys,Warm).
weather(9,mdv,Warm).
weather(9,mli,Warm).
weather(9,mlt,Warm).
weather(9,mrt,Warm).
weather(9,mus,Warm).
weather(9,myt,Warm).
weather(9,mex,Warm).
weather(9,mda,Rain).
weather(9,mco,Warm).
weather(9,mng,Rain).
weather(9,mne,Rain).
weather(9,mar,Warm).
weather(9,moz,Warm).
weather(9,mmr,Warm).
weather(9,nam,Rain).
weather(9,npl,Warm).
weather(9,nld,Rain).
weather(9,nic,Warm).
weather(9,ner,Warm).
weather(9,nga,Warm).
weather(9,prk,Rain).
weather(9,nor,Rain).
weather(9,omn,Warm).
weather(9,pak,Warm).
weather(9,pse,Warm).
weather(9,pan,Warm).
weather(9,pry,Warm).
weather(9,per,Rain).
weather(9,phl,Warm).
weather(9,pol,Rain).
weather(9,prt,Warm).
weather(9,qat,Warm).
weather(9,rou,Rain).
weather(9,rus,Rain).
weather(9,rwa,Rain).
weather(9,shn,Rain).
weather(9,smr,Warm).
weather(9,wsm,Warm).
weather(9,stp,Warm).
weather(9,sau,Warm).
weather(9,sen,Warm).
weather(9,srb,Rain).
weather(9,syc,Warm).
weather(9,sle,Warm).
weather(9,sgp,Warm).
weather(9,svk,Rain).
weather(9,svn,Rain).
weather(9,som,Warm).
weather(9,zaf,Rain).
weather(9,kor,Warm).
weather(9,ssd,Warm).
weather(9,esp,Warm).
weather(9,lka,Warm).
weather(9,sdn,Warm).
weather(9,sur,Warm).
weather(9,swz,Rain).
weather(9,swe,Rain).
weather(9,che,Rain).
weather(9,syr,Warm).
weather(9,tjk,Rain).
weather(9,tha,Warm).
weather(9,tls,Warm).
weather(9,tgo,Warm).
weather(9,tun,Warm).
weather(9,tur,Rain).
weather(9,tkm,Warm).
weather(9,uga,Warm).
weather(9,ukr,Rain).
weather(9,are,Warm).
weather(9,gbr,Rain).
weather(9,tza,Rain).
weather(9,usa,Rain).
weather(9,ury,Rain).
weather(9,uzb,Warm).
weather(9,ven,Warm).
weather(9,vnm,Warm).
weather(9,esh,Warm).
weather(9,yem,Warm).
weather(9,zmb,Warm).
weather(9,zwe,Warm).
weather(10,afg,Rain).
weather(10,alb,Rain).
weather(10,dza,Rain).
weather(10,and,Rain).
weather(10,ago,Warm).
weather(10,arg,Rain).
weather(10,arm,Rain).
weather(10,aut,Rain).
weather(10,aze,Rain).
weather(10,bhr,Warm).
weather(10,bgd,Warm).
weather(10,blr,Rain).
weather(10,bel,Rain).
weather(10,blz,Warm).
weather(10,ben,Warm).
weather(10,bmu,Warm).
weather(10,btn,Rain).
weather(10,bol,Rain).
weather(10,bih,Rain).
weather(10,bwa,Warm).
weather(10,bra,Warm).
weather(10,brn,Warm).
weather(10,bgr,Rain).
weather(10,bfa,Warm).
weather(10,bdi,Warm).
weather(10,cpv,Warm).
weather(10,khm,Warm).
weather(10,cmr,Warm).
weather(10,can,Rain).
weather(10,caf,Warm).
weather(10,tcd,Warm).
weather(10,chl,Rain).
weather(10,chn,Rain).
weather(10,col,Warm).
weather(10,com,Warm).
weather(10,cog,Warm).
weather(10,cri,Rain).
weather(10,civ,Warm).
weather(10,hrv,Rain).
weather(10,cyp,Warm).
weather(10,cze,Rain).
weather(10,cod,Warm).
weather(10,dnk,Rain).
weather(10,dji,Warm).
weather(10,ecu,Rain).
weather(10,egy,Warm).
weather(10,slv,Warm).
weather(10,gnq,Warm).
weather(10,eri,Warm).
weather(10,est,Rain).
weather(10,eth,Rain).
weather(10,fin,Rain).
weather(10,fra,Rain).
weather(10,gab,Warm).
weather(10,gmb,Warm).
weather(10,geo,Rain).
weather(10,deu,Rain).
weather(10,gha,Warm).
weather(10,gib,Rain).
weather(10,grc,Rain).
weather(10,grl,Warm).
weather(10,gtm,Warm).
weather(10,ggy,Warm).
weather(10,gnb,Warm).
weather(10,gin,Warm).
weather(10,guy,Warm).
weather(10,hnd,Warm).
weather(10,hun,Rain).
weather(10,isl,Rain).
weather(10,ind,Warm).
weather(10,idn,Warm).
weather(10,irn,Rain).
weather(10,irq,Warm).
weather(10,irl,Rain).
weather(10,isr,Warm).
weather(10,ita,Rain).
weather(10,jpn,Rain).
weather(10,jey,Warm).
weather(10,jor,Warm).
weather(10,kaz,Rain).
weather(10,ken,Warm).
weather(10,kwt,Warm).
weather(10,kgz,Rain).
weather(10,lao,Warm).
weather(10,lva,Rain).
weather(10,lbn,Rain).
weather(10,lso,Rain).
weather(10,lbr,Warm).
weather(10,lby,Warm).
weather(10,lie,Rain).
weather(10,ltu,Rain).
weather(10,lux,Rain).
weather(10,mkd,Rain).
weather(10,mdg,Warm).
weather(10,mwi,Warm).
weather(10,mys,Warm).
weather(10,mdv,Warm).
weather(10,mli,Warm).
weather(10,mlt,Warm).
weather(10,mrt,Warm).
weather(10,mus,Warm).
weather(10,myt,Warm).
weather(10,mex,Warm).
weather(10,mda,Rain).
weather(10,mco,Warm).
weather(10,mng,Rain).
weather(10,mne,Rain).
weather(10,mar,Rain).
weather(10,moz,Warm).
weather(10,mmr,Warm).
weather(10,nam,Warm).
weather(10,npl,Rain).
weather(10,nld,Rain).
weather(10,nic,Warm).
weather(10,ner,Warm).
weather(10,nga,Warm).
weather(10,prk,Rain).
weather(10,nor,Rain).
weather(10,omn,Warm).
weather(10,pak,Warm).
weather(10,pse,Warm).
weather(10,pan,Warm).
weather(10,pry,Warm).
weather(10,per,Rain).
weather(10,phl,Warm).
weather(10,pol,Rain).
weather(10,prt,Rain).
weather(10,qat,Warm).
weather(10,rou,Rain).
weather(10,rus,Rain).
weather(10,rwa,Rain).
weather(10,shn,Rain).
weather(10,smr,Rain).
weather(10,wsm,Warm).
weather(10,stp,Warm).
weather(10,sau,Warm).
weather(10,sen,Warm).
weather(10,srb,Rain).
weather(10,syc,Warm).
weather(10,sle,Warm).
weather(10,sgp,Warm).
weather(10,svk,Rain).
weather(10,svn,Rain).
weather(10,som,Warm).
weather(10,zaf,Rain).
weather(10,kor,Rain).
weather(10,ssd,Warm).
weather(10,esp,Rain).
weather(10,lka,Warm).
weather(10,sdn,Warm).
weather(10,sur,Warm).
weather(10,swz,Rain).
weather(10,swe,Rain).
weather(10,che,Rain).
weather(10,syr,Warm).
weather(10,tjk,Rain).
weather(10,tha,Warm).
weather(10,tls,Warm).
weather(10,tgo,Warm).
weather(10,tun,Warm).
weather(10,tur,Rain).
weather(10,tkm,Rain).
weather(10,uga,Warm).
weather(10,ukr,Rain).
weather(10,are,Warm).
weather(10,gbr,Rain).
weather(10,tza,Rain).
weather(10,usa,Rain).
weather(10,ury,Rain).
weather(10,uzb,Rain).
weather(10,ven,Warm).
weather(10,vnm,Warm).
weather(10,esh,Warm).
weather(10,yem,Warm).
weather(10,zmb,Warm).
weather(10,zwe,Warm).
weather(11,afg,Rain).
weather(11,alb,Rain).
weather(11,dza,Rain).
weather(11,and,Rain).
weather(11,ago,Warm).
weather(11,arg,Warm).
weather(11,arm,Rain).
weather(11,aut,Rain).
weather(11,aze,Rain).
weather(11,bhr,Warm).
weather(11,bgd,Warm).
weather(11,blr,Rain).
weather(11,bel,Rain).
weather(11,blz,Warm).
weather(11,ben,Warm).
weather(11,bmu,Warm).
weather(11,btn,Rain).
weather(11,bol,Rain).
weather(11,bih,Rain).
weather(11,bwa,Warm).
weather(11,bra,Warm).
weather(11,brn,Warm).
weather(11,bgr,Rain).
weather(11,bfa,Warm).
weather(11,bdi,Rain).
weather(11,cpv,Warm).
weather(11,khm,Warm).
weather(11,cmr,Warm).
weather(11,can,Snow).
weather(11,caf,Warm).
weather(11,tcd,Warm).
weather(11,chl,Rain).
weather(11,chn,Rain).
weather(11,col,Warm).
weather(11,com,Warm).
weather(11,cog,Warm).
weather(11,cri,Rain).
weather(11,civ,Warm).
weather(11,hrv,Rain).
weather(11,cyp,Rain).
weather(11,cze,Rain).
weather(11,cod,Warm).
weather(11,dnk,Rain).
weather(11,dji,Warm).
weather(11,ecu,Rain).
weather(11,egy,Rain).
weather(11,slv,Warm).
weather(11,gnq,Warm).
weather(11,eri,Warm).
weather(11,est,Rain).
weather(11,eth,Rain).
weather(11,fin,Snow).
weather(11,fra,Rain).
weather(11,gab,Warm).
weather(11,gmb,Warm).
weather(11,geo,Rain).
weather(11,deu,Rain).
weather(11,gha,Warm).
weather(11,gib,Rain).
weather(11,grc,Rain).
weather(11,grl,Warm).
weather(11,gtm,Warm).
weather(11,ggy,Warm).
weather(11,gnb,Warm).
weather(11,gin,Warm).
weather(11,guy,Warm).
weather(11,hnd,Warm).
weather(11,hun,Rain).
weather(11,isl,Rain).
weather(11,ind,Warm).
weather(11,idn,Warm).
weather(11,irn,Rain).
weather(11,irq,Rain).
weather(11,irl,Rain).
weather(11,isr,Rain).
weather(11,ita,Rain).
weather(11,jpn,Rain).
weather(11,jey,Warm).
weather(11,jor,Rain).
weather(11,kaz,Snow).
weather(11,ken,Warm).
weather(11,kwt,Warm).
weather(11,kgz,Rain).
weather(11,lao,Warm).
weather(11,lva,Rain).
weather(11,lbn,Rain).
weather(11,lso,Rain).
weather(11,lbr,Warm).
weather(11,lby,Rain).
weather(11,lie,Rain).
weather(11,ltu,Rain).
weather(11,lux,Rain).
weather(11,mkd,Rain).
weather(11,mdg,Warm).
weather(11,mwi,Warm).
weather(11,mys,Warm).
weather(11,mdv,Warm).
weather(11,mli,Warm).
weather(11,mlt,Rain).
weather(11,mrt,Warm).
weather(11,mus,Warm).
weather(11,myt,Warm).
weather(11,mex,Rain).
weather(11,mda,Rain).
weather(11,mco,Rain).
weather(11,mng,Snow).
weather(11,mne,Rain).
weather(11,mar,Rain).
weather(11,moz,Warm).
weather(11,mmr,Warm).
weather(11,nam,Warm).
weather(11,npl,Rain).
weather(11,nld,Rain).
weather(11,nic,Warm).
weather(11,ner,Warm).
weather(11,nga,Warm).
weather(11,prk,Rain).
weather(11,nor,Rain).
weather(11,omn,Warm).
weather(11,pak,Rain).
weather(11,pse,Warm).
weather(11,pan,Warm).
weather(11,pry,Warm).
weather(11,per,Rain).
weather(11,phl,Warm).
weather(11,pol,Rain).
weather(11,prt,Rain).
weather(11,qat,Warm).
weather(11,rou,Rain).
weather(11,rus,Snow).
weather(11,rwa,Rain).
weather(11,shn,Rain).
weather(11,smr,Rain).
weather(11,wsm,Warm).
weather(11,stp,Warm).
weather(11,sau,Warm).
weather(11,sen,Warm).
weather(11,srb,Rain).
weather(11,syc,Warm).
weather(11,sle,Warm).
weather(11,sgp,Warm).
weather(11,svk,Rain).
weather(11,svn,Rain).
weather(11,som,Warm).
weather(11,zaf,Rain).
weather(11,kor,Rain).
weather(11,ssd,Warm).
weather(11,esp,Rain).
weather(11,lka,Warm).
weather(11,sdn,Warm).
weather(11,sur,Warm).
weather(11,swz,Warm).
weather(11,swe,Rain).
weather(11,che,Rain).
weather(11,syr,Rain).
weather(11,tjk,Rain).
weather(11,tha,Warm).
weather(11,tls,Warm).
weather(11,tgo,Warm).
weather(11,tun,Rain).
weather(11,tur,Rain).
weather(11,tkm,Rain).
weather(11,uga,Warm).
weather(11,ukr,Rain).
weather(11,are,Warm).
weather(11,gbr,Rain).
weather(11,tza,Rain).
weather(11,usa,Rain).
weather(11,ury,Rain).
weather(11,uzb,Rain).
weather(11,ven,Warm).
weather(11,vnm,Warm).
weather(11,esh,Warm).
weather(11,yem,Warm).
weather(11,zmb,Warm).
weather(11,zwe,Warm).
weather(12,afg,Rain).
weather(12,alb,Rain).
weather(12,dza,Rain).
weather(12,and,Snow).
weather(12,ago,Warm).
weather(12,arg,Warm).
weather(12,arm,Snow).
weather(12,aut,Snow).
weather(12,aze,Rain).
weather(12,bhr,Rain).
weather(12,bgd,Rain).
weather(12,blr,Snow).
weather(12,bel,Rain).
weather(12,blz,Warm).
weather(12,ben,Warm).
weather(12,bmu,Rain).
weather(12,btn,Rain).
weather(12,bol,Rain).
weather(12,bih,Rain).
weather(12,bwa,Warm).
weather(12,bra,Warm).
weather(12,brn,Warm).
weather(12,bgr,Rain).
weather(12,bfa,Warm).
weather(12,bdi,Rain).
weather(12,cpv,Warm).
weather(12,khm,Warm).
weather(12,cmr,Warm).
weather(12,can,Snow).
weather(12,caf,Warm).
weather(12,tcd,Warm).
weather(12,chl,Rain).
weather(12,chn,Rain).
weather(12,col,Warm).
weather(12,com,Warm).
weather(12,cog,Warm).
weather(12,cri,Rain).
weather(12,civ,Warm).
weather(12,hrv,Rain).
weather(12,cyp,Rain).
weather(12,cze,Snow).
weather(12,cod,Warm).
weather(12,dnk,Rain).
weather(12,dji,Warm).
weather(12,ecu,Warm).
weather(12,egy,Rain).
weather(12,slv,Warm).
weather(12,gnq,Warm).
weather(12,eri,Warm).
weather(12,est,Snow).
weather(12,eth,Rain).
weather(12,fin,Snow).
weather(12,fra,Rain).
weather(12,gab,Warm).
weather(12,gmb,Warm).
weather(12,geo,Rain).
weather(12,deu,Rain).
weather(12,gha,Warm).
weather(12,gib,Rain).
weather(12,grc,Rain).
weather(12,grl,Rain).
weather(12,gtm,Rain).
weather(12,ggy,Warm).
weather(12,gnb,Warm).
weather(12,gin,Warm).
weather(12,guy,Warm).
weather(12,hnd,Warm).
weather(12,hun,Rain).
weather(12,isl,Snow).
weather(12,ind,Rain).
weather(12,idn,Warm).
weather(12,irn,Rain).
weather(12,irq,Rain).
weather(12,irl,Rain).
weather(12,isr,Rain).
weather(12,ita,Rain).
weather(12,jpn,Rain).
weather(12,jey,Warm).
weather(12,jor,Rain).
weather(12,kaz,Snow).
weather(12,ken,Warm).
weather(12,kwt,Rain).
weather(12,kgz,Snow).
weather(12,lao,Warm).
weather(12,lva,Snow).
weather(12,lbn,Rain).
weather(12,lso,Rain).
weather(12,lbr,Warm).
weather(12,lby,Rain).
weather(12,lie,Rain).
weather(12,ltu,Snow).
weather(12,lux,Rain).
weather(12,mkd,Rain).
weather(12,mdg,Warm).
weather(12,mwi,Warm).
weather(12,mys,Warm).
weather(12,mdv,Warm).
weather(12,mli,Warm).
weather(12,mlt,Rain).
weather(12,mrt,Warm).
weather(12,mus,Warm).
weather(12,myt,Warm).
weather(12,mex,Rain).
weather(12,mda,Snow).
weather(12,mco,Rain).
weather(12,mng,Snow).
weather(12,mne,Rain).
weather(12,mar,Rain).
weather(12,moz,Warm).
weather(12,mmr,Warm).
weather(12,nam,Warm).
weather(12,npl,Rain).
weather(12,nld,Rain).
weather(12,nic,Warm).
weather(12,ner,Warm).
weather(12,nga,Warm).
weather(12,prk,Snow).
weather(12,nor,Snow).
weather(12,omn,Warm).
weather(12,pak,Rain).
weather(12,pse,Warm).
weather(12,pan,Warm).
weather(12,pry,Warm).
weather(12,per,Rain).
weather(12,phl,Warm).
weather(12,pol,Snow).
weather(12,prt,Rain).
weather(12,qat,Rain).
weather(12,rou,Snow).
weather(12,rus,Snow).
weather(12,rwa,Rain).
weather(12,shn,Rain).
weather(12,smr,Rain).
weather(12,wsm,Warm).
weather(12,stp,Warm).
weather(12,sau,Rain).
weather(12,sen,Warm).
weather(12,srb,Rain).
weather(12,syc,Warm).
weather(12,sle,Warm).
weather(12,sgp,Warm).
weather(12,svk,Snow).
weather(12,svn,Snow).
weather(12,som,Warm).
weather(12,zaf,Warm).
weather(12,kor,Rain).
weather(12,ssd,Warm).
weather(12,esp,Rain).
weather(12,lka,Warm).
weather(12,sdn,Warm).
weather(12,sur,Warm).
weather(12,swz,Warm).
weather(12,swe,Snow).
weather(12,che,Snow).
weather(12,syr,Rain).
weather(12,tjk,Rain).
weather(12,tha,Warm).
weather(12,tls,Warm).
weather(12,tgo,Warm).
weather(12,tun,Rain).
weather(12,tur,Rain).
weather(12,tkm,Rain).
weather(12,uga,Warm).
weather(12,ukr,Snow).
weather(12,are,Warm).
weather(12,gbr,Rain).
weather(12,tza,Warm).
weather(12,usa,Rain).
weather(12,ury,Warm).
weather(12,uzb,Rain).
weather(12,ven,Warm).
weather(12,vnm,Warm).
weather(12,esh,Rain).
weather(12,yem,Warm).
weather(12,zmb,Warm).
weather(12,zwe,Warm).
