:- module(weather,[]).
weather(1,afg,rain).
weather(1,alb,rain).
weather(1,dza,rain).
weather(1,and,snow).
weather(1,ago,warm).
weather(1,arg,warm).
weather(1,arm,snow).
weather(1,aut,snow).
weather(1,aze,rain).
weather(1,bhr,rain).
weather(1,bgd,rain).
weather(1,blr,snow).
weather(1,bel,rain).
weather(1,blz,warm).
weather(1,ben,warm).
weather(1,bmu,rain).
weather(1,btn,rain).
weather(1,bol,rain).
weather(1,bih,rain).
weather(1,bwa,warm).
weather(1,bra,warm).
weather(1,brn,warm).
weather(1,bgr,snow).
weather(1,bfa,warm).
weather(1,bdi,warm).
weather(1,cpv,warm).
weather(1,khm,warm).
weather(1,cmr,warm).
weather(1,can,snow).
weather(1,caf,warm).
weather(1,tcd,warm).
weather(1,chl,rain).
weather(1,chn,snow).
weather(1,col,warm).
weather(1,com,warm).
weather(1,cog,warm).
weather(1,cri,rain).
weather(1,civ,warm).
weather(1,hrv,rain).
weather(1,cyp,rain).
weather(1,cze,snow).
weather(1,cod,warm).
weather(1,dnk,rain).
weather(1,dji,warm).
weather(1,ecu,warm).
weather(1,egy,rain).
weather(1,slv,warm).
weather(1,gnq,warm).
weather(1,eri,rain).
weather(1,est,snow).
weather(1,eth,rain).
weather(1,fin,snow).
weather(1,fra,rain).
weather(1,gab,warm).
weather(1,gmb,warm).
weather(1,geo,rain).
weather(1,deu,snow).
weather(1,gha,warm).
weather(1,gib,rain).
weather(1,grc,rain).
weather(1,grl,rain).
weather(1,gtm,rain).
weather(1,ggy,warm).
weather(1,gnb,warm).
weather(1,gin,warm).
weather(1,guy,warm).
weather(1,hnd,warm).
weather(1,hun,snow).
weather(1,isl,snow).
weather(1,ind,rain).
weather(1,idn,warm).
weather(1,irn,rain).
weather(1,irq,rain).
weather(1,irl,rain).
weather(1,isr,rain).
weather(1,ita,rain).
weather(1,jpn,rain).
weather(1,jey,warm).
weather(1,jor,rain).
weather(1,kaz,snow).
weather(1,ken,warm).
weather(1,kwt,rain).
weather(1,kgz,snow).
weather(1,lao,warm).
weather(1,lva,snow).
weather(1,lbn,rain).
weather(1,lso,rain).
weather(1,lbr,warm).
weather(1,lby,rain).
weather(1,lie,rain).
weather(1,ltu,snow).
weather(1,lux,rain).
weather(1,mkd,rain).
weather(1,mdg,warm).
weather(1,mwi,warm).
weather(1,mys,warm).
weather(1,mdv,warm).
weather(1,mli,warm).
weather(1,mlt,rain).
weather(1,mrt,warm).
weather(1,mus,warm).
weather(1,myt,warm).
weather(1,mex,rain).
weather(1,mda,snow).
weather(1,mco,rain).
weather(1,mng,snow).
weather(1,mne,rain).
weather(1,mar,rain).
weather(1,moz,warm).
weather(1,mmr,warm).
weather(1,nam,warm).
weather(1,npl,rain).
weather(1,nld,rain).
weather(1,nic,warm).
weather(1,ner,warm).
weather(1,nga,warm).
weather(1,prk,snow).
weather(1,nor,snow).
weather(1,omn,rain).
weather(1,pak,rain).
weather(1,pse,warm).
weather(1,pan,warm).
weather(1,pry,warm).
weather(1,per,rain).
weather(1,phl,warm).
weather(1,pol,snow).
weather(1,prt,rain).
weather(1,qat,rain).
weather(1,rou,snow).
weather(1,rus,snow).
weather(1,rwa,rain).
weather(1,shn,rain).
weather(1,smr,rain).
weather(1,wsm,warm).
weather(1,stp,warm).
weather(1,sau,rain).
weather(1,sen,warm).
weather(1,srb,snow).
weather(1,syc,warm).
weather(1,sle,warm).
weather(1,sgp,warm).
weather(1,svk,snow).
weather(1,svn,snow).
weather(1,som,warm).
weather(1,zaf,warm).
weather(1,kor,snow).
weather(1,ssd,warm).
weather(1,esp,rain).
weather(1,lka,warm).
weather(1,sdn,warm).
weather(1,sur,warm).
weather(1,swz,warm).
weather(1,swe,snow).
weather(1,che,snow).
weather(1,syr,rain).
weather(1,tjk,snow).
weather(1,tha,warm).
weather(1,tls,warm).
weather(1,tgo,warm).
weather(1,tun,rain).
weather(1,tur,rain).
weather(1,tkm,rain).
weather(1,uga,warm).
weather(1,ukr,snow).
weather(1,are,rain).
weather(1,gbr,rain).
weather(1,tza,warm).
weather(1,usa,rain).
weather(1,ury,warm).
weather(1,uzb,snow).
weather(1,ven,warm).
weather(1,vnm,warm).
weather(1,esh,rain).
weather(1,yem,warm).
weather(1,zmb,warm).
weather(1,zwe,warm).
weather(2,afg,rain).
weather(2,alb,rain).
weather(2,dza,rain).
weather(2,and,snow).
weather(2,ago,warm).
weather(2,arg,warm).
weather(2,arm,snow).
weather(2,aut,snow).
weather(2,aze,rain).
weather(2,bhr,rain).
weather(2,bgd,warm).
weather(2,blr,snow).
weather(2,bel,rain).
weather(2,blz,warm).
weather(2,ben,warm).
weather(2,bmu,rain).
weather(2,btn,rain).
weather(2,bol,rain).
weather(2,bih,rain).
weather(2,bwa,warm).
weather(2,bra,warm).
weather(2,brn,warm).
weather(2,bgr,rain).
weather(2,bfa,warm).
weather(2,bdi,warm).
weather(2,cpv,warm).
weather(2,khm,warm).
weather(2,cmr,warm).
weather(2,can,snow).
weather(2,caf,warm).
weather(2,tcd,warm).
weather(2,chl,rain).
weather(2,chn,rain).
weather(2,col,warm).
weather(2,com,warm).
weather(2,cog,warm).
weather(2,cri,rain).
weather(2,civ,warm).
weather(2,hrv,rain).
weather(2,cyp,rain).
weather(2,cze,snow).
weather(2,cod,warm).
weather(2,dnk,rain).
weather(2,dji,warm).
weather(2,ecu,warm).
weather(2,egy,rain).
weather(2,slv,warm).
weather(2,gnq,warm).
weather(2,eri,warm).
weather(2,est,snow).
weather(2,eth,rain).
weather(2,fin,snow).
weather(2,fra,rain).
weather(2,gab,warm).
weather(2,gmb,warm).
weather(2,geo,rain).
weather(2,deu,rain).
weather(2,gha,warm).
weather(2,gib,rain).
weather(2,grc,rain).
weather(2,grl,rain).
weather(2,gtm,rain).
weather(2,ggy,warm).
weather(2,gnb,warm).
weather(2,gin,warm).
weather(2,guy,warm).
weather(2,hnd,warm).
weather(2,hun,rain).
weather(2,isl,snow).
weather(2,ind,rain).
weather(2,idn,warm).
weather(2,irn,rain).
weather(2,irq,rain).
weather(2,irl,rain).
weather(2,isr,rain).
weather(2,ita,rain).
weather(2,jpn,rain).
weather(2,jey,warm).
weather(2,jor,rain).
weather(2,kaz,snow).
weather(2,ken,warm).
weather(2,kwt,rain).
weather(2,kgz,snow).
weather(2,lao,warm).
weather(2,lva,snow).
weather(2,lbn,rain).
weather(2,lso,rain).
weather(2,lbr,warm).
weather(2,lby,rain).
weather(2,lie,rain).
weather(2,ltu,snow).
weather(2,lux,rain).
weather(2,mkd,rain).
weather(2,mdg,warm).
weather(2,mwi,warm).
weather(2,mys,warm).
weather(2,mdv,warm).
weather(2,mli,warm).
weather(2,mlt,rain).
weather(2,mrt,warm).
weather(2,mus,warm).
weather(2,myt,warm).
weather(2,mex,rain).
weather(2,mda,snow).
weather(2,mco,rain).
weather(2,mng,snow).
weather(2,mne,rain).
weather(2,mar,rain).
weather(2,moz,warm).
weather(2,mmr,warm).
weather(2,nam,warm).
weather(2,npl,rain).
weather(2,nld,rain).
weather(2,nic,warm).
weather(2,ner,warm).
weather(2,nga,warm).
weather(2,prk,snow).
weather(2,nor,snow).
weather(2,omn,warm).
weather(2,pak,rain).
weather(2,pse,warm).
weather(2,pan,warm).
weather(2,pry,warm).
weather(2,per,rain).
weather(2,phl,warm).
weather(2,pol,snow).
weather(2,prt,rain).
weather(2,qat,rain).
weather(2,rou,snow).
weather(2,rus,snow).
weather(2,rwa,rain).
weather(2,shn,rain).
weather(2,smr,rain).
weather(2,wsm,warm).
weather(2,stp,warm).
weather(2,sau,rain).
weather(2,sen,warm).
weather(2,srb,rain).
weather(2,syc,warm).
weather(2,sle,warm).
weather(2,sgp,warm).
weather(2,svk,snow).
weather(2,svn,snow).
weather(2,som,warm).
weather(2,zaf,warm).
weather(2,kor,rain).
weather(2,ssd,warm).
weather(2,esp,rain).
weather(2,lka,warm).
weather(2,sdn,warm).
weather(2,sur,warm).
weather(2,swz,warm).
weather(2,swe,snow).
weather(2,che,snow).
weather(2,syr,rain).
weather(2,tjk,snow).
weather(2,tha,warm).
weather(2,tls,warm).
weather(2,tgo,warm).
weather(2,tun,rain).
weather(2,tur,rain).
weather(2,tkm,rain).
weather(2,uga,warm).
weather(2,ukr,snow).
weather(2,are,rain).
weather(2,gbr,rain).
weather(2,tza,warm).
weather(2,usa,rain).
weather(2,ury,warm).
weather(2,uzb,rain).
weather(2,ven,warm).
weather(2,vnm,warm).
weather(2,esh,rain).
weather(2,yem,warm).
weather(2,zmb,warm).
weather(2,zwe,warm).
weather(3,afg,rain).
weather(3,alb,rain).
weather(3,dza,rain).
weather(3,and,rain).
weather(3,ago,warm).
weather(3,arg,warm).
weather(3,arm,rain).
weather(3,aut,rain).
weather(3,aze,rain).
weather(3,bhr,warm).
weather(3,bgd,warm).
weather(3,blr,snow).
weather(3,bel,rain).
weather(3,blz,warm).
weather(3,ben,warm).
weather(3,bmu,rain).
weather(3,btn,rain).
weather(3,bol,rain).
weather(3,bih,rain).
weather(3,bwa,warm).
weather(3,bra,warm).
weather(3,brn,warm).
weather(3,bgr,rain).
weather(3,bfa,warm).
weather(3,bdi,warm).
weather(3,cpv,warm).
weather(3,khm,warm).
weather(3,cmr,warm).
weather(3,can,snow).
weather(3,caf,warm).
weather(3,tcd,warm).
weather(3,chl,rain).
weather(3,chn,rain).
weather(3,col,warm).
weather(3,com,warm).
weather(3,cog,warm).
weather(3,cri,rain).
weather(3,civ,warm).
weather(3,hrv,rain).
weather(3,cyp,rain).
weather(3,cze,rain).
weather(3,cod,warm).
weather(3,dnk,rain).
weather(3,dji,warm).
weather(3,ecu,warm).
weather(3,egy,rain).
weather(3,slv,warm).
weather(3,gnq,warm).
weather(3,eri,warm).
weather(3,est,snow).
weather(3,eth,warm).
weather(3,fin,snow).
weather(3,fra,rain).
weather(3,gab,warm).
weather(3,gmb,warm).
weather(3,geo,rain).
weather(3,deu,rain).
weather(3,gha,warm).
weather(3,gib,rain).
weather(3,grc,rain).
weather(3,grl,warm).
weather(3,gtm,warm).
weather(3,ggy,warm).
weather(3,gnb,warm).
weather(3,gin,warm).
weather(3,guy,warm).
weather(3,hnd,warm).
weather(3,hun,rain).
weather(3,isl,snow).
weather(3,ind,warm).
weather(3,idn,warm).
weather(3,irn,rain).
weather(3,irq,rain).
weather(3,irl,rain).
weather(3,isr,rain).
weather(3,ita,rain).
weather(3,jpn,rain).
weather(3,jey,warm).
weather(3,jor,rain).
weather(3,kaz,snow).
weather(3,ken,warm).
weather(3,kwt,rain).
weather(3,kgz,rain).
weather(3,lao,warm).
weather(3,lva,snow).
weather(3,lbn,rain).
weather(3,lso,rain).
weather(3,lbr,warm).
weather(3,lby,rain).
weather(3,lie,rain).
weather(3,ltu,snow).
weather(3,lux,rain).
weather(3,mkd,rain).
weather(3,mdg,warm).
weather(3,mwi,warm).
weather(3,mys,warm).
weather(3,mdv,warm).
weather(3,mli,warm).
weather(3,mlt,rain).
weather(3,mrt,warm).
weather(3,mus,warm).
weather(3,myt,warm).
weather(3,mex,rain).
weather(3,mda,rain).
weather(3,mco,rain).
weather(3,mng,snow).
weather(3,mne,rain).
weather(3,mar,rain).
weather(3,moz,warm).
weather(3,mmr,warm).
weather(3,nam,warm).
weather(3,npl,rain).
weather(3,nld,rain).
weather(3,nic,warm).
weather(3,ner,warm).
weather(3,nga,warm).
weather(3,prk,rain).
weather(3,nor,snow).
weather(3,omn,warm).
weather(3,pak,rain).
weather(3,pse,warm).
weather(3,pan,warm).
weather(3,pry,warm).
weather(3,per,rain).
weather(3,phl,warm).
weather(3,pol,rain).
weather(3,prt,rain).
weather(3,qat,warm).
weather(3,rou,rain).
weather(3,rus,snow).
weather(3,rwa,rain).
weather(3,shn,rain).
weather(3,smr,rain).
weather(3,wsm,warm).
weather(3,stp,warm).
weather(3,sau,warm).
weather(3,sen,warm).
weather(3,srb,rain).
weather(3,syc,warm).
weather(3,sle,warm).
weather(3,sgp,warm).
weather(3,svk,rain).
weather(3,svn,rain).
weather(3,som,warm).
weather(3,zaf,warm).
weather(3,kor,rain).
weather(3,ssd,warm).
weather(3,esp,rain).
weather(3,lka,warm).
weather(3,sdn,warm).
weather(3,sur,warm).
weather(3,swz,warm).
weather(3,swe,snow).
weather(3,che,rain).
weather(3,syr,rain).
weather(3,tjk,rain).
weather(3,tha,warm).
weather(3,tls,warm).
weather(3,tgo,warm).
weather(3,tun,rain).
weather(3,tur,rain).
weather(3,tkm,rain).
weather(3,uga,warm).
weather(3,ukr,rain).
weather(3,are,warm).
weather(3,gbr,rain).
weather(3,tza,warm).
weather(3,usa,rain).
weather(3,ury,warm).
weather(3,uzb,rain).
weather(3,ven,warm).
weather(3,vnm,warm).
weather(3,esh,rain).
weather(3,yem,warm).
weather(3,zmb,warm).
weather(3,zwe,warm).
weather(4,afg,rain).
weather(4,alb,rain).
weather(4,dza,rain).
weather(4,and,rain).
weather(4,ago,warm).
weather(4,arg,rain).
weather(4,arm,rain).
weather(4,aut,rain).
weather(4,aze,rain).
weather(4,bhr,warm).
weather(4,bgd,warm).
weather(4,blr,rain).
weather(4,bel,rain).
weather(4,blz,warm).
weather(4,ben,warm).
weather(4,bmu,rain).
weather(4,btn,rain).
weather(4,bol,rain).
weather(4,bih,rain).
weather(4,bwa,warm).
weather(4,bra,warm).
weather(4,brn,warm).
weather(4,bgr,rain).
weather(4,bfa,warm).
weather(4,bdi,warm).
weather(4,cpv,warm).
weather(4,khm,warm).
weather(4,cmr,warm).
weather(4,can,rain).
weather(4,caf,warm).
weather(4,tcd,warm).
weather(4,chl,rain).
weather(4,chn,rain).
weather(4,col,warm).
weather(4,com,warm).
weather(4,cog,warm).
weather(4,cri,rain).
weather(4,civ,warm).
weather(4,hrv,rain).
weather(4,cyp,rain).
weather(4,cze,rain).
weather(4,cod,warm).
weather(4,dnk,rain).
weather(4,dji,warm).
weather(4,ecu,warm).
weather(4,egy,warm).
weather(4,slv,warm).
weather(4,gnq,warm).
weather(4,eri,warm).
weather(4,est,rain).
weather(4,eth,warm).
weather(4,fin,rain).
weather(4,fra,rain).
weather(4,gab,warm).
weather(4,gmb,warm).
weather(4,geo,rain).
weather(4,deu,rain).
weather(4,gha,warm).
weather(4,gib,rain).
weather(4,grc,rain).
weather(4,grl,warm).
weather(4,gtm,warm).
weather(4,ggy,warm).
weather(4,gnb,warm).
weather(4,gin,warm).
weather(4,guy,warm).
weather(4,hnd,warm).
weather(4,hun,rain).
weather(4,isl,rain).
weather(4,ind,warm).
weather(4,idn,warm).
weather(4,irn,rain).
weather(4,irq,warm).
weather(4,irl,rain).
weather(4,isr,rain).
weather(4,ita,rain).
weather(4,jpn,rain).
weather(4,jey,warm).
weather(4,jor,rain).
weather(4,kaz,rain).
weather(4,ken,warm).
weather(4,kwt,warm).
weather(4,kgz,rain).
weather(4,lao,warm).
weather(4,lva,rain).
weather(4,lbn,rain).
weather(4,lso,rain).
weather(4,lbr,warm).
weather(4,lby,rain).
weather(4,lie,rain).
weather(4,ltu,rain).
weather(4,lux,rain).
weather(4,mkd,rain).
weather(4,mdg,warm).
weather(4,mwi,warm).
weather(4,mys,warm).
weather(4,mdv,warm).
weather(4,mli,warm).
weather(4,mlt,rain).
weather(4,mrt,warm).
weather(4,mus,warm).
weather(4,myt,warm).
weather(4,mex,warm).
weather(4,mda,rain).
weather(4,mco,rain).
weather(4,mng,rain).
weather(4,mne,rain).
weather(4,mar,rain).
weather(4,moz,warm).
weather(4,mmr,warm).
weather(4,nam,warm).
weather(4,npl,warm).
weather(4,nld,rain).
weather(4,nic,warm).
weather(4,ner,warm).
weather(4,nga,warm).
weather(4,prk,rain).
weather(4,nor,rain).
weather(4,omn,warm).
weather(4,pak,warm).
weather(4,pse,warm).
weather(4,pan,warm).
weather(4,pry,warm).
weather(4,per,rain).
weather(4,phl,warm).
weather(4,pol,rain).
weather(4,prt,rain).
weather(4,qat,warm).
weather(4,rou,rain).
weather(4,rus,snow).
weather(4,rwa,rain).
weather(4,shn,rain).
weather(4,smr,rain).
weather(4,wsm,warm).
weather(4,stp,warm).
weather(4,sau,warm).
weather(4,sen,warm).
weather(4,srb,rain).
weather(4,syc,warm).
weather(4,sle,warm).
weather(4,sgp,warm).
weather(4,svk,rain).
weather(4,svn,rain).
weather(4,som,warm).
weather(4,zaf,rain).
weather(4,kor,rain).
weather(4,ssd,warm).
weather(4,esp,rain).
weather(4,lka,warm).
weather(4,sdn,warm).
weather(4,sur,warm).
weather(4,swz,rain).
weather(4,swe,rain).
weather(4,che,rain).
weather(4,syr,rain).
weather(4,tjk,rain).
weather(4,tha,warm).
weather(4,tls,warm).
weather(4,tgo,warm).
weather(4,tun,rain).
weather(4,tur,rain).
weather(4,tkm,rain).
weather(4,uga,warm).
weather(4,ukr,rain).
weather(4,are,warm).
weather(4,gbr,rain).
weather(4,tza,rain).
weather(4,usa,rain).
weather(4,ury,rain).
weather(4,uzb,rain).
weather(4,ven,warm).
weather(4,vnm,warm).
weather(4,esh,rain).
weather(4,yem,warm).
weather(4,zmb,warm).
weather(4,zwe,rain).
weather(5,afg,rain).
weather(5,alb,rain).
weather(5,dza,rain).
weather(5,and,rain).
weather(5,ago,warm).
weather(5,arg,rain).
weather(5,arm,rain).
weather(5,aut,rain).
weather(5,aze,rain).
weather(5,bhr,warm).
weather(5,bgd,warm).
weather(5,blr,rain).
weather(5,bel,rain).
weather(5,blz,warm).
weather(5,ben,warm).
weather(5,bmu,warm).
weather(5,btn,rain).
weather(5,bol,rain).
weather(5,bih,rain).
weather(5,bwa,rain).
weather(5,bra,warm).
weather(5,brn,warm).
weather(5,bgr,rain).
weather(5,bfa,warm).
weather(5,bdi,rain).
weather(5,cpv,warm).
weather(5,khm,warm).
weather(5,cmr,warm).
weather(5,can,rain).
weather(5,caf,warm).
weather(5,tcd,warm).
weather(5,chl,rain).
weather(5,chn,rain).
weather(5,col,warm).
weather(5,com,warm).
weather(5,cog,warm).
weather(5,cri,rain).
weather(5,civ,warm).
weather(5,hrv,rain).
weather(5,cyp,warm).
weather(5,cze,rain).
weather(5,cod,warm).
weather(5,dnk,rain).
weather(5,dji,warm).
weather(5,ecu,warm).
weather(5,egy,warm).
weather(5,slv,warm).
weather(5,gnq,warm).
weather(5,eri,warm).
weather(5,est,rain).
weather(5,eth,warm).
weather(5,fin,rain).
weather(5,fra,rain).
weather(5,gab,warm).
weather(5,gmb,warm).
weather(5,geo,rain).
weather(5,deu,rain).
weather(5,gha,warm).
weather(5,gib,rain).
weather(5,grc,rain).
weather(5,grl,warm).
weather(5,gtm,warm).
weather(5,ggy,warm).
weather(5,gnb,warm).
weather(5,gin,warm).
weather(5,guy,warm).
weather(5,hnd,warm).
weather(5,hun,rain).
weather(5,isl,rain).
weather(5,ind,warm).
weather(5,idn,warm).
weather(5,irn,warm).
weather(5,irq,warm).
weather(5,irl,rain).
weather(5,isr,warm).
weather(5,ita,rain).
weather(5,jpn,rain).
weather(5,jey,warm).
weather(5,jor,warm).
weather(5,kaz,rain).
weather(5,ken,warm).
weather(5,kwt,warm).
weather(5,kgz,rain).
weather(5,lao,warm).
weather(5,lva,rain).
weather(5,lbn,rain).
weather(5,lso,rain).
weather(5,lbr,warm).
weather(5,lby,warm).
weather(5,lie,rain).
weather(5,ltu,rain).
weather(5,lux,rain).
weather(5,mkd,rain).
weather(5,mdg,warm).
weather(5,mwi,rain).
weather(5,mys,warm).
weather(5,mdv,warm).
weather(5,mli,warm).
weather(5,mlt,rain).
weather(5,mrt,warm).
weather(5,mus,warm).
weather(5,myt,warm).
weather(5,mex,warm).
weather(5,mda,rain).
weather(5,mco,rain).
weather(5,mng,rain).
weather(5,mne,rain).
weather(5,mar,rain).
weather(5,moz,warm).
weather(5,mmr,warm).
weather(5,nam,rain).
weather(5,npl,warm).
weather(5,nld,rain).
weather(5,nic,warm).
weather(5,ner,warm).
weather(5,nga,warm).
weather(5,prk,rain).
weather(5,nor,rain).
weather(5,omn,warm).
weather(5,pak,warm).
weather(5,pse,warm).
weather(5,pan,warm).
weather(5,pry,rain).
weather(5,per,rain).
weather(5,phl,warm).
weather(5,pol,rain).
weather(5,prt,rain).
weather(5,qat,warm).
weather(5,rou,rain).
weather(5,rus,rain).
weather(5,rwa,rain).
weather(5,shn,rain).
weather(5,smr,rain).
weather(5,wsm,warm).
weather(5,stp,warm).
weather(5,sau,warm).
weather(5,sen,warm).
weather(5,srb,rain).
weather(5,syc,warm).
weather(5,sle,warm).
weather(5,sgp,warm).
weather(5,svk,rain).
weather(5,svn,rain).
weather(5,som,warm).
weather(5,zaf,rain).
weather(5,kor,rain).
weather(5,ssd,warm).
weather(5,esp,rain).
weather(5,lka,warm).
weather(5,sdn,warm).
weather(5,sur,warm).
weather(5,swz,rain).
weather(5,swe,rain).
weather(5,che,rain).
weather(5,syr,warm).
weather(5,tjk,rain).
weather(5,tha,warm).
weather(5,tls,warm).
weather(5,tgo,warm).
weather(5,tun,rain).
weather(5,tur,rain).
weather(5,tkm,warm).
weather(5,uga,warm).
weather(5,ukr,rain).
weather(5,are,warm).
weather(5,gbr,rain).
weather(5,tza,rain).
weather(5,usa,rain).
weather(5,ury,rain).
weather(5,uzb,warm).
weather(5,ven,warm).
weather(5,vnm,warm).
weather(5,esh,warm).
weather(5,yem,warm).
weather(5,zmb,rain).
weather(5,zwe,rain).
weather(6,afg,warm).
weather(6,alb,warm).
weather(6,dza,warm).
weather(6,and,rain).
weather(6,ago,rain).
weather(6,arg,rain).
weather(6,arm,rain).
weather(6,aut,rain).
weather(6,aze,warm).
weather(6,bhr,warm).
weather(6,bgd,warm).
weather(6,blr,rain).
weather(6,bel,rain).
weather(6,blz,warm).
weather(6,ben,warm).
weather(6,bmu,warm).
weather(6,btn,warm).
weather(6,bol,rain).
weather(6,bih,rain).
weather(6,bwa,rain).
weather(6,bra,warm).
weather(6,brn,warm).
weather(6,bgr,rain).
weather(6,bfa,warm).
weather(6,bdi,rain).
weather(6,cpv,warm).
weather(6,khm,warm).
weather(6,cmr,warm).
weather(6,can,rain).
weather(6,caf,warm).
weather(6,tcd,warm).
weather(6,chl,rain).
weather(6,chn,warm).
weather(6,col,warm).
weather(6,com,warm).
weather(6,cog,warm).
weather(6,cri,rain).
weather(6,civ,warm).
weather(6,hrv,rain).
weather(6,cyp,warm).
weather(6,cze,rain).
weather(6,cod,warm).
weather(6,dnk,rain).
weather(6,dji,warm).
weather(6,ecu,rain).
weather(6,egy,warm).
weather(6,slv,warm).
weather(6,gnq,warm).
weather(6,eri,warm).
weather(6,est,rain).
weather(6,eth,warm).
weather(6,fin,rain).
weather(6,fra,rain).
weather(6,gab,warm).
weather(6,gmb,warm).
weather(6,geo,warm).
weather(6,deu,rain).
weather(6,gha,warm).
weather(6,gib,warm).
weather(6,grc,warm).
weather(6,grl,warm).
weather(6,gtm,warm).
weather(6,ggy,warm).
weather(6,gnb,warm).
weather(6,gin,warm).
weather(6,guy,warm).
weather(6,hnd,warm).
weather(6,hun,rain).
weather(6,isl,rain).
weather(6,ind,warm).
weather(6,idn,warm).
weather(6,irn,warm).
weather(6,irq,warm).
weather(6,irl,rain).
weather(6,isr,warm).
weather(6,ita,rain).
weather(6,jpn,warm).
weather(6,jey,warm).
weather(6,jor,warm).
weather(6,kaz,warm).
weather(6,ken,rain).
weather(6,kwt,warm).
weather(6,kgz,rain).
weather(6,lao,warm).
weather(6,lva,rain).
weather(6,lbn,warm).
weather(6,lso,rain).
weather(6,lbr,warm).
weather(6,lby,warm).
weather(6,lie,rain).
weather(6,ltu,rain).
weather(6,lux,rain).
weather(6,mkd,rain).
weather(6,mdg,rain).
weather(6,mwi,rain).
weather(6,mys,warm).
weather(6,mdv,warm).
weather(6,mli,warm).
weather(6,mlt,warm).
weather(6,mrt,warm).
weather(6,mus,warm).
weather(6,myt,warm).
weather(6,mex,warm).
weather(6,mda,rain).
weather(6,mco,rain).
weather(6,mng,rain).
weather(6,mne,rain).
weather(6,mar,warm).
weather(6,moz,warm).
weather(6,mmr,warm).
weather(6,nam,rain).
weather(6,npl,warm).
weather(6,nld,rain).
weather(6,nic,warm).
weather(6,ner,warm).
weather(6,nga,warm).
weather(6,prk,rain).
weather(6,nor,rain).
weather(6,omn,warm).
weather(6,pak,warm).
weather(6,pse,warm).
weather(6,pan,warm).
weather(6,pry,rain).
weather(6,per,rain).
weather(6,phl,warm).
weather(6,pol,rain).
weather(6,prt,rain).
weather(6,qat,warm).
weather(6,rou,rain).
weather(6,rus,rain).
weather(6,rwa,rain).
weather(6,shn,rain).
weather(6,smr,rain).
weather(6,wsm,warm).
weather(6,stp,warm).
weather(6,sau,warm).
weather(6,sen,warm).
weather(6,srb,rain).
weather(6,syc,warm).
weather(6,sle,warm).
weather(6,sgp,warm).
weather(6,svk,rain).
weather(6,svn,rain).
weather(6,som,warm).
weather(6,zaf,rain).
weather(6,kor,warm).
weather(6,ssd,warm).
weather(6,esp,rain).
weather(6,lka,warm).
weather(6,sdn,warm).
weather(6,sur,warm).
weather(6,swz,rain).
weather(6,swe,rain).
weather(6,che,rain).
weather(6,syr,warm).
weather(6,tjk,warm).
weather(6,tha,warm).
weather(6,tls,warm).
weather(6,tgo,warm).
weather(6,tun,warm).
weather(6,tur,rain).
weather(6,tkm,warm).
weather(6,uga,warm).
weather(6,ukr,rain).
weather(6,are,warm).
weather(6,gbr,rain).
weather(6,tza,rain).
weather(6,usa,warm).
weather(6,ury,rain).
weather(6,uzb,warm).
weather(6,ven,warm).
weather(6,vnm,warm).
weather(6,esh,warm).
weather(6,yem,warm).
weather(6,zmb,rain).
weather(6,zwe,rain).
weather(7,afg,warm).
weather(7,alb,warm).
weather(7,dza,warm).
weather(7,and,rain).
weather(7,ago,rain).
weather(7,arg,rain).
weather(7,arm,rain).
weather(7,aut,rain).
weather(7,aze,warm).
weather(7,bhr,warm).
weather(7,bgd,warm).
weather(7,blr,rain).
weather(7,bel,rain).
weather(7,blz,warm).
weather(7,ben,warm).
weather(7,bmu,warm).
weather(7,btn,rain).
weather(7,bol,rain).
weather(7,bih,rain).
weather(7,bwa,rain).
weather(7,bra,warm).
weather(7,brn,warm).
weather(7,bgr,rain).
weather(7,bfa,warm).
weather(7,bdi,rain).
weather(7,cpv,warm).
weather(7,khm,warm).
weather(7,cmr,warm).
weather(7,can,rain).
weather(7,caf,warm).
weather(7,tcd,warm).
weather(7,chl,rain).
weather(7,chn,warm).
weather(7,col,warm).
weather(7,com,warm).
weather(7,cog,warm).
weather(7,cri,warm).
weather(7,civ,warm).
weather(7,hrv,warm).
weather(7,cyp,warm).
weather(7,cze,rain).
weather(7,cod,warm).
weather(7,dnk,rain).
weather(7,dji,warm).
weather(7,ecu,rain).
weather(7,egy,warm).
weather(7,slv,warm).
weather(7,gnq,warm).
weather(7,eri,warm).
weather(7,est,rain).
weather(7,eth,rain).
weather(7,fin,rain).
weather(7,fra,rain).
weather(7,gab,warm).
weather(7,gmb,warm).
weather(7,geo,warm).
weather(7,deu,rain).
weather(7,gha,warm).
weather(7,gib,warm).
weather(7,grc,warm).
weather(7,grl,warm).
weather(7,gtm,warm).
weather(7,ggy,warm).
weather(7,gnb,warm).
weather(7,gin,warm).
weather(7,guy,warm).
weather(7,hnd,warm).
weather(7,hun,warm).
weather(7,isl,rain).
weather(7,ind,warm).
weather(7,idn,warm).
weather(7,irn,warm).
weather(7,irq,warm).
weather(7,irl,rain).
weather(7,isr,warm).
weather(7,ita,warm).
weather(7,jpn,warm).
weather(7,jey,warm).
weather(7,jor,warm).
weather(7,kaz,warm).
weather(7,ken,rain).
weather(7,kwt,warm).
weather(7,kgz,warm).
weather(7,lao,warm).
weather(7,lva,rain).
weather(7,lbn,warm).
weather(7,lso,rain).
weather(7,lbr,warm).
weather(7,lby,warm).
weather(7,lie,rain).
weather(7,ltu,rain).
weather(7,lux,rain).
weather(7,mkd,warm).
weather(7,mdg,rain).
weather(7,mwi,rain).
weather(7,mys,warm).
weather(7,mdv,warm).
weather(7,mli,warm).
weather(7,mlt,warm).
weather(7,mrt,warm).
weather(7,mus,warm).
weather(7,myt,warm).
weather(7,mex,warm).
weather(7,mda,warm).
weather(7,mco,rain).
weather(7,mng,rain).
weather(7,mne,warm).
weather(7,mar,warm).
weather(7,moz,rain).
weather(7,mmr,warm).
weather(7,nam,rain).
weather(7,npl,warm).
weather(7,nld,rain).
weather(7,nic,warm).
weather(7,ner,warm).
weather(7,nga,warm).
weather(7,prk,warm).
weather(7,nor,rain).
weather(7,omn,warm).
weather(7,pak,warm).
weather(7,pse,warm).
weather(7,pan,warm).
weather(7,pry,rain).
weather(7,per,rain).
weather(7,phl,warm).
weather(7,pol,rain).
weather(7,prt,warm).
weather(7,qat,warm).
weather(7,rou,rain).
weather(7,rus,rain).
weather(7,rwa,rain).
weather(7,shn,rain).
weather(7,smr,rain).
weather(7,wsm,warm).
weather(7,stp,warm).
weather(7,sau,warm).
weather(7,sen,warm).
weather(7,srb,warm).
weather(7,syc,warm).
weather(7,sle,warm).
weather(7,sgp,warm).
weather(7,svk,rain).
weather(7,svn,rain).
weather(7,som,warm).
weather(7,zaf,rain).
weather(7,kor,warm).
weather(7,ssd,warm).
weather(7,esp,warm).
weather(7,lka,warm).
weather(7,sdn,warm).
weather(7,sur,warm).
weather(7,swz,rain).
weather(7,swe,rain).
weather(7,che,rain).
weather(7,syr,warm).
weather(7,tjk,warm).
weather(7,tha,warm).
weather(7,tls,warm).
weather(7,tgo,warm).
weather(7,tun,warm).
weather(7,tur,warm).
weather(7,tkm,warm).
weather(7,uga,warm).
weather(7,ukr,warm).
weather(7,are,warm).
weather(7,gbr,rain).
weather(7,tza,rain).
weather(7,usa,warm).
weather(7,ury,rain).
weather(7,uzb,warm).
weather(7,ven,warm).
weather(7,vnm,warm).
weather(7,esh,warm).
weather(7,yem,warm).
weather(7,zmb,rain).
weather(7,zwe,rain).
weather(8,afg,warm).
weather(8,alb,warm).
weather(8,dza,warm).
weather(8,and,rain).
weather(8,ago,rain).
weather(8,arg,rain).
weather(8,arm,rain).
weather(8,aut,rain).
weather(8,aze,warm).
weather(8,bhr,warm).
weather(8,bgd,warm).
weather(8,blr,rain).
weather(8,bel,rain).
weather(8,blz,warm).
weather(8,ben,warm).
weather(8,bmu,warm).
weather(8,btn,warm).
weather(8,bol,rain).
weather(8,bih,rain).
weather(8,bwa,rain).
weather(8,bra,warm).
weather(8,brn,warm).
weather(8,bgr,rain).
weather(8,bfa,warm).
weather(8,bdi,warm).
weather(8,cpv,warm).
weather(8,khm,warm).
weather(8,cmr,warm).
weather(8,can,rain).
weather(8,caf,warm).
weather(8,tcd,warm).
weather(8,chl,rain).
weather(8,chn,warm).
weather(8,col,warm).
weather(8,com,warm).
weather(8,cog,warm).
weather(8,cri,warm).
weather(8,civ,warm).
weather(8,hrv,warm).
weather(8,cyp,warm).
weather(8,cze,rain).
weather(8,cod,warm).
weather(8,dnk,rain).
weather(8,dji,warm).
weather(8,ecu,rain).
weather(8,egy,warm).
weather(8,slv,warm).
weather(8,gnq,warm).
weather(8,eri,warm).
weather(8,est,rain).
weather(8,eth,rain).
weather(8,fin,rain).
weather(8,fra,rain).
weather(8,gab,warm).
weather(8,gmb,warm).
weather(8,geo,warm).
weather(8,deu,rain).
weather(8,gha,warm).
weather(8,gib,warm).
weather(8,grc,warm).
weather(8,grl,warm).
weather(8,gtm,warm).
weather(8,ggy,warm).
weather(8,gnb,warm).
weather(8,gin,warm).
weather(8,guy,warm).
weather(8,hnd,warm).
weather(8,hun,rain).
weather(8,isl,rain).
weather(8,ind,warm).
weather(8,idn,warm).
weather(8,irn,warm).
weather(8,irq,warm).
weather(8,irl,rain).
weather(8,isr,warm).
weather(8,ita,warm).
weather(8,jpn,warm).
weather(8,jey,warm).
weather(8,jor,warm).
weather(8,kaz,warm).
weather(8,ken,rain).
weather(8,kwt,warm).
weather(8,kgz,warm).
weather(8,lao,warm).
weather(8,lva,rain).
weather(8,lbn,warm).
weather(8,lso,rain).
weather(8,lbr,warm).
weather(8,lby,warm).
weather(8,lie,rain).
weather(8,ltu,rain).
weather(8,lux,rain).
weather(8,mkd,warm).
weather(8,mdg,rain).
weather(8,mwi,rain).
weather(8,mys,warm).
weather(8,mdv,warm).
weather(8,mli,warm).
weather(8,mlt,warm).
weather(8,mrt,warm).
weather(8,mus,warm).
weather(8,myt,warm).
weather(8,mex,warm).
weather(8,mda,warm).
weather(8,mco,warm).
weather(8,mng,rain).
weather(8,mne,warm).
weather(8,mar,warm).
weather(8,moz,warm).
weather(8,mmr,warm).
weather(8,nam,rain).
weather(8,npl,warm).
weather(8,nld,rain).
weather(8,nic,warm).
weather(8,ner,warm).
weather(8,nga,warm).
weather(8,prk,warm).
weather(8,nor,rain).
weather(8,omn,warm).
weather(8,pak,warm).
weather(8,pse,warm).
weather(8,pan,warm).
weather(8,pry,rain).
weather(8,per,rain).
weather(8,phl,warm).
weather(8,pol,rain).
weather(8,prt,warm).
weather(8,qat,warm).
weather(8,rou,rain).
weather(8,rus,rain).
weather(8,rwa,rain).
weather(8,shn,rain).
weather(8,smr,warm).
weather(8,wsm,warm).
weather(8,stp,warm).
weather(8,sau,warm).
weather(8,sen,warm).
weather(8,srb,warm).
weather(8,syc,warm).
weather(8,sle,warm).
weather(8,sgp,warm).
weather(8,svk,rain).
weather(8,svn,rain).
weather(8,som,warm).
weather(8,zaf,rain).
weather(8,kor,warm).
weather(8,ssd,warm).
weather(8,esp,warm).
weather(8,lka,warm).
weather(8,sdn,warm).
weather(8,sur,warm).
weather(8,swz,rain).
weather(8,swe,rain).
weather(8,che,rain).
weather(8,syr,warm).
weather(8,tjk,warm).
weather(8,tha,warm).
weather(8,tls,warm).
weather(8,tgo,warm).
weather(8,tun,warm).
weather(8,tur,warm).
weather(8,tkm,warm).
weather(8,uga,warm).
weather(8,ukr,rain).
weather(8,are,warm).
weather(8,gbr,rain).
weather(8,tza,rain).
weather(8,usa,warm).
weather(8,ury,rain).
weather(8,uzb,warm).
weather(8,ven,warm).
weather(8,vnm,warm).
weather(8,esh,warm).
weather(8,yem,warm).
weather(8,zmb,rain).
weather(8,zwe,rain).
weather(9,afg,warm).
weather(9,alb,rain).
weather(9,dza,warm).
weather(9,and,rain).
weather(9,ago,warm).
weather(9,arg,rain).
weather(9,arm,rain).
weather(9,aut,rain).
weather(9,aze,warm).
weather(9,bhr,warm).
weather(9,bgd,warm).
weather(9,blr,rain).
weather(9,bel,rain).
weather(9,blz,warm).
weather(9,ben,warm).
weather(9,bmu,warm).
weather(9,btn,warm).
weather(9,bol,rain).
weather(9,bih,rain).
weather(9,bwa,warm).
weather(9,bra,warm).
weather(9,brn,warm).
weather(9,bgr,rain).
weather(9,bfa,warm).
weather(9,bdi,warm).
weather(9,cpv,warm).
weather(9,khm,warm).
weather(9,cmr,warm).
weather(9,can,rain).
weather(9,caf,warm).
weather(9,tcd,warm).
weather(9,chl,rain).
weather(9,chn,warm).
weather(9,col,warm).
weather(9,com,warm).
weather(9,cog,warm).
weather(9,cri,rain).
weather(9,civ,warm).
weather(9,hrv,rain).
weather(9,cyp,warm).
weather(9,cze,rain).
weather(9,cod,warm).
weather(9,dnk,rain).
weather(9,dji,warm).
weather(9,ecu,rain).
weather(9,egy,warm).
weather(9,slv,warm).
weather(9,gnq,warm).
weather(9,eri,warm).
weather(9,est,rain).
weather(9,eth,rain).
weather(9,fin,rain).
weather(9,fra,rain).
weather(9,gab,warm).
weather(9,gmb,warm).
weather(9,geo,rain).
weather(9,deu,rain).
weather(9,gha,warm).
weather(9,gib,warm).
weather(9,grc,warm).
weather(9,grl,warm).
weather(9,gtm,warm).
weather(9,ggy,warm).
weather(9,gnb,warm).
weather(9,gin,warm).
weather(9,guy,warm).
weather(9,hnd,warm).
weather(9,hun,rain).
weather(9,isl,rain).
weather(9,ind,warm).
weather(9,idn,warm).
weather(9,irn,warm).
weather(9,irq,warm).
weather(9,irl,rain).
weather(9,isr,warm).
weather(9,ita,rain).
weather(9,jpn,warm).
weather(9,jey,warm).
weather(9,jor,warm).
weather(9,kaz,rain).
weather(9,ken,warm).
weather(9,kwt,warm).
weather(9,kgz,rain).
weather(9,lao,warm).
weather(9,lva,rain).
weather(9,lbn,warm).
weather(9,lso,rain).
weather(9,lbr,warm).
weather(9,lby,warm).
weather(9,lie,rain).
weather(9,ltu,rain).
weather(9,lux,rain).
weather(9,mkd,rain).
weather(9,mdg,warm).
weather(9,mwi,warm).
weather(9,mys,warm).
weather(9,mdv,warm).
weather(9,mli,warm).
weather(9,mlt,warm).
weather(9,mrt,warm).
weather(9,mus,warm).
weather(9,myt,warm).
weather(9,mex,warm).
weather(9,mda,rain).
weather(9,mco,warm).
weather(9,mng,rain).
weather(9,mne,rain).
weather(9,mar,warm).
weather(9,moz,warm).
weather(9,mmr,warm).
weather(9,nam,rain).
weather(9,npl,warm).
weather(9,nld,rain).
weather(9,nic,warm).
weather(9,ner,warm).
weather(9,nga,warm).
weather(9,prk,rain).
weather(9,nor,rain).
weather(9,omn,warm).
weather(9,pak,warm).
weather(9,pse,warm).
weather(9,pan,warm).
weather(9,pry,warm).
weather(9,per,rain).
weather(9,phl,warm).
weather(9,pol,rain).
weather(9,prt,warm).
weather(9,qat,warm).
weather(9,rou,rain).
weather(9,rus,rain).
weather(9,rwa,rain).
weather(9,shn,rain).
weather(9,smr,warm).
weather(9,wsm,warm).
weather(9,stp,warm).
weather(9,sau,warm).
weather(9,sen,warm).
weather(9,srb,rain).
weather(9,syc,warm).
weather(9,sle,warm).
weather(9,sgp,warm).
weather(9,svk,rain).
weather(9,svn,rain).
weather(9,som,warm).
weather(9,zaf,rain).
weather(9,kor,warm).
weather(9,ssd,warm).
weather(9,esp,warm).
weather(9,lka,warm).
weather(9,sdn,warm).
weather(9,sur,warm).
weather(9,swz,rain).
weather(9,swe,rain).
weather(9,che,rain).
weather(9,syr,warm).
weather(9,tjk,rain).
weather(9,tha,warm).
weather(9,tls,warm).
weather(9,tgo,warm).
weather(9,tun,warm).
weather(9,tur,rain).
weather(9,tkm,warm).
weather(9,uga,warm).
weather(9,ukr,rain).
weather(9,are,warm).
weather(9,gbr,rain).
weather(9,tza,rain).
weather(9,usa,rain).
weather(9,ury,rain).
weather(9,uzb,warm).
weather(9,ven,warm).
weather(9,vnm,warm).
weather(9,esh,warm).
weather(9,yem,warm).
weather(9,zmb,warm).
weather(9,zwe,warm).
weather(10,afg,rain).
weather(10,alb,rain).
weather(10,dza,rain).
weather(10,and,rain).
weather(10,ago,warm).
weather(10,arg,rain).
weather(10,arm,rain).
weather(10,aut,rain).
weather(10,aze,rain).
weather(10,bhr,warm).
weather(10,bgd,warm).
weather(10,blr,rain).
weather(10,bel,rain).
weather(10,blz,warm).
weather(10,ben,warm).
weather(10,bmu,warm).
weather(10,btn,rain).
weather(10,bol,rain).
weather(10,bih,rain).
weather(10,bwa,warm).
weather(10,bra,warm).
weather(10,brn,warm).
weather(10,bgr,rain).
weather(10,bfa,warm).
weather(10,bdi,warm).
weather(10,cpv,warm).
weather(10,khm,warm).
weather(10,cmr,warm).
weather(10,can,rain).
weather(10,caf,warm).
weather(10,tcd,warm).
weather(10,chl,rain).
weather(10,chn,rain).
weather(10,col,warm).
weather(10,com,warm).
weather(10,cog,warm).
weather(10,cri,rain).
weather(10,civ,warm).
weather(10,hrv,rain).
weather(10,cyp,warm).
weather(10,cze,rain).
weather(10,cod,warm).
weather(10,dnk,rain).
weather(10,dji,warm).
weather(10,ecu,rain).
weather(10,egy,warm).
weather(10,slv,warm).
weather(10,gnq,warm).
weather(10,eri,warm).
weather(10,est,rain).
weather(10,eth,rain).
weather(10,fin,rain).
weather(10,fra,rain).
weather(10,gab,warm).
weather(10,gmb,warm).
weather(10,geo,rain).
weather(10,deu,rain).
weather(10,gha,warm).
weather(10,gib,rain).
weather(10,grc,rain).
weather(10,grl,warm).
weather(10,gtm,warm).
weather(10,ggy,warm).
weather(10,gnb,warm).
weather(10,gin,warm).
weather(10,guy,warm).
weather(10,hnd,warm).
weather(10,hun,rain).
weather(10,isl,rain).
weather(10,ind,warm).
weather(10,idn,warm).
weather(10,irn,rain).
weather(10,irq,warm).
weather(10,irl,rain).
weather(10,isr,warm).
weather(10,ita,rain).
weather(10,jpn,rain).
weather(10,jey,warm).
weather(10,jor,warm).
weather(10,kaz,rain).
weather(10,ken,warm).
weather(10,kwt,warm).
weather(10,kgz,rain).
weather(10,lao,warm).
weather(10,lva,rain).
weather(10,lbn,rain).
weather(10,lso,rain).
weather(10,lbr,warm).
weather(10,lby,warm).
weather(10,lie,rain).
weather(10,ltu,rain).
weather(10,lux,rain).
weather(10,mkd,rain).
weather(10,mdg,warm).
weather(10,mwi,warm).
weather(10,mys,warm).
weather(10,mdv,warm).
weather(10,mli,warm).
weather(10,mlt,warm).
weather(10,mrt,warm).
weather(10,mus,warm).
weather(10,myt,warm).
weather(10,mex,warm).
weather(10,mda,rain).
weather(10,mco,warm).
weather(10,mng,rain).
weather(10,mne,rain).
weather(10,mar,rain).
weather(10,moz,warm).
weather(10,mmr,warm).
weather(10,nam,warm).
weather(10,npl,rain).
weather(10,nld,rain).
weather(10,nic,warm).
weather(10,ner,warm).
weather(10,nga,warm).
weather(10,prk,rain).
weather(10,nor,rain).
weather(10,omn,warm).
weather(10,pak,warm).
weather(10,pse,warm).
weather(10,pan,warm).
weather(10,pry,warm).
weather(10,per,rain).
weather(10,phl,warm).
weather(10,pol,rain).
weather(10,prt,rain).
weather(10,qat,warm).
weather(10,rou,rain).
weather(10,rus,rain).
weather(10,rwa,rain).
weather(10,shn,rain).
weather(10,smr,rain).
weather(10,wsm,warm).
weather(10,stp,warm).
weather(10,sau,warm).
weather(10,sen,warm).
weather(10,srb,rain).
weather(10,syc,warm).
weather(10,sle,warm).
weather(10,sgp,warm).
weather(10,svk,rain).
weather(10,svn,rain).
weather(10,som,warm).
weather(10,zaf,rain).
weather(10,kor,rain).
weather(10,ssd,warm).
weather(10,esp,rain).
weather(10,lka,warm).
weather(10,sdn,warm).
weather(10,sur,warm).
weather(10,swz,rain).
weather(10,swe,rain).
weather(10,che,rain).
weather(10,syr,warm).
weather(10,tjk,rain).
weather(10,tha,warm).
weather(10,tls,warm).
weather(10,tgo,warm).
weather(10,tun,warm).
weather(10,tur,rain).
weather(10,tkm,rain).
weather(10,uga,warm).
weather(10,ukr,rain).
weather(10,are,warm).
weather(10,gbr,rain).
weather(10,tza,rain).
weather(10,usa,rain).
weather(10,ury,rain).
weather(10,uzb,rain).
weather(10,ven,warm).
weather(10,vnm,warm).
weather(10,esh,warm).
weather(10,yem,warm).
weather(10,zmb,warm).
weather(10,zwe,warm).
weather(11,afg,rain).
weather(11,alb,rain).
weather(11,dza,rain).
weather(11,and,rain).
weather(11,ago,warm).
weather(11,arg,warm).
weather(11,arm,rain).
weather(11,aut,rain).
weather(11,aze,rain).
weather(11,bhr,warm).
weather(11,bgd,warm).
weather(11,blr,rain).
weather(11,bel,rain).
weather(11,blz,warm).
weather(11,ben,warm).
weather(11,bmu,warm).
weather(11,btn,rain).
weather(11,bol,rain).
weather(11,bih,rain).
weather(11,bwa,warm).
weather(11,bra,warm).
weather(11,brn,warm).
weather(11,bgr,rain).
weather(11,bfa,warm).
weather(11,bdi,rain).
weather(11,cpv,warm).
weather(11,khm,warm).
weather(11,cmr,warm).
weather(11,can,snow).
weather(11,caf,warm).
weather(11,tcd,warm).
weather(11,chl,rain).
weather(11,chn,rain).
weather(11,col,warm).
weather(11,com,warm).
weather(11,cog,warm).
weather(11,cri,rain).
weather(11,civ,warm).
weather(11,hrv,rain).
weather(11,cyp,rain).
weather(11,cze,rain).
weather(11,cod,warm).
weather(11,dnk,rain).
weather(11,dji,warm).
weather(11,ecu,rain).
weather(11,egy,rain).
weather(11,slv,warm).
weather(11,gnq,warm).
weather(11,eri,warm).
weather(11,est,rain).
weather(11,eth,rain).
weather(11,fin,snow).
weather(11,fra,rain).
weather(11,gab,warm).
weather(11,gmb,warm).
weather(11,geo,rain).
weather(11,deu,rain).
weather(11,gha,warm).
weather(11,gib,rain).
weather(11,grc,rain).
weather(11,grl,warm).
weather(11,gtm,warm).
weather(11,ggy,warm).
weather(11,gnb,warm).
weather(11,gin,warm).
weather(11,guy,warm).
weather(11,hnd,warm).
weather(11,hun,rain).
weather(11,isl,rain).
weather(11,ind,warm).
weather(11,idn,warm).
weather(11,irn,rain).
weather(11,irq,rain).
weather(11,irl,rain).
weather(11,isr,rain).
weather(11,ita,rain).
weather(11,jpn,rain).
weather(11,jey,warm).
weather(11,jor,rain).
weather(11,kaz,snow).
weather(11,ken,warm).
weather(11,kwt,warm).
weather(11,kgz,rain).
weather(11,lao,warm).
weather(11,lva,rain).
weather(11,lbn,rain).
weather(11,lso,rain).
weather(11,lbr,warm).
weather(11,lby,rain).
weather(11,lie,rain).
weather(11,ltu,rain).
weather(11,lux,rain).
weather(11,mkd,rain).
weather(11,mdg,warm).
weather(11,mwi,warm).
weather(11,mys,warm).
weather(11,mdv,warm).
weather(11,mli,warm).
weather(11,mlt,rain).
weather(11,mrt,warm).
weather(11,mus,warm).
weather(11,myt,warm).
weather(11,mex,rain).
weather(11,mda,rain).
weather(11,mco,rain).
weather(11,mng,snow).
weather(11,mne,rain).
weather(11,mar,rain).
weather(11,moz,warm).
weather(11,mmr,warm).
weather(11,nam,warm).
weather(11,npl,rain).
weather(11,nld,rain).
weather(11,nic,warm).
weather(11,ner,warm).
weather(11,nga,warm).
weather(11,prk,rain).
weather(11,nor,rain).
weather(11,omn,warm).
weather(11,pak,rain).
weather(11,pse,warm).
weather(11,pan,warm).
weather(11,pry,warm).
weather(11,per,rain).
weather(11,phl,warm).
weather(11,pol,rain).
weather(11,prt,rain).
weather(11,qat,warm).
weather(11,rou,rain).
weather(11,rus,snow).
weather(11,rwa,rain).
weather(11,shn,rain).
weather(11,smr,rain).
weather(11,wsm,warm).
weather(11,stp,warm).
weather(11,sau,warm).
weather(11,sen,warm).
weather(11,srb,rain).
weather(11,syc,warm).
weather(11,sle,warm).
weather(11,sgp,warm).
weather(11,svk,rain).
weather(11,svn,rain).
weather(11,som,warm).
weather(11,zaf,rain).
weather(11,kor,rain).
weather(11,ssd,warm).
weather(11,esp,rain).
weather(11,lka,warm).
weather(11,sdn,warm).
weather(11,sur,warm).
weather(11,swz,warm).
weather(11,swe,rain).
weather(11,che,rain).
weather(11,syr,rain).
weather(11,tjk,rain).
weather(11,tha,warm).
weather(11,tls,warm).
weather(11,tgo,warm).
weather(11,tun,rain).
weather(11,tur,rain).
weather(11,tkm,rain).
weather(11,uga,warm).
weather(11,ukr,rain).
weather(11,are,warm).
weather(11,gbr,rain).
weather(11,tza,rain).
weather(11,usa,rain).
weather(11,ury,rain).
weather(11,uzb,rain).
weather(11,ven,warm).
weather(11,vnm,warm).
weather(11,esh,warm).
weather(11,yem,warm).
weather(11,zmb,warm).
weather(11,zwe,warm).
weather(12,afg,rain).
weather(12,alb,rain).
weather(12,dza,rain).
weather(12,and,snow).
weather(12,ago,warm).
weather(12,arg,warm).
weather(12,arm,snow).
weather(12,aut,snow).
weather(12,aze,rain).
weather(12,bhr,rain).
weather(12,bgd,rain).
weather(12,blr,snow).
weather(12,bel,rain).
weather(12,blz,warm).
weather(12,ben,warm).
weather(12,bmu,rain).
weather(12,btn,rain).
weather(12,bol,rain).
weather(12,bih,rain).
weather(12,bwa,warm).
weather(12,bra,warm).
weather(12,brn,warm).
weather(12,bgr,rain).
weather(12,bfa,warm).
weather(12,bdi,rain).
weather(12,cpv,warm).
weather(12,khm,warm).
weather(12,cmr,warm).
weather(12,can,snow).
weather(12,caf,warm).
weather(12,tcd,warm).
weather(12,chl,rain).
weather(12,chn,rain).
weather(12,col,warm).
weather(12,com,warm).
weather(12,cog,warm).
weather(12,cri,rain).
weather(12,civ,warm).
weather(12,hrv,rain).
weather(12,cyp,rain).
weather(12,cze,snow).
weather(12,cod,warm).
weather(12,dnk,rain).
weather(12,dji,warm).
weather(12,ecu,warm).
weather(12,egy,rain).
weather(12,slv,warm).
weather(12,gnq,warm).
weather(12,eri,warm).
weather(12,est,snow).
weather(12,eth,rain).
weather(12,fin,snow).
weather(12,fra,rain).
weather(12,gab,warm).
weather(12,gmb,warm).
weather(12,geo,rain).
weather(12,deu,rain).
weather(12,gha,warm).
weather(12,gib,rain).
weather(12,grc,rain).
weather(12,grl,rain).
weather(12,gtm,rain).
weather(12,ggy,warm).
weather(12,gnb,warm).
weather(12,gin,warm).
weather(12,guy,warm).
weather(12,hnd,warm).
weather(12,hun,rain).
weather(12,isl,snow).
weather(12,ind,rain).
weather(12,idn,warm).
weather(12,irn,rain).
weather(12,irq,rain).
weather(12,irl,rain).
weather(12,isr,rain).
weather(12,ita,rain).
weather(12,jpn,rain).
weather(12,jey,warm).
weather(12,jor,rain).
weather(12,kaz,snow).
weather(12,ken,warm).
weather(12,kwt,rain).
weather(12,kgz,snow).
weather(12,lao,warm).
weather(12,lva,snow).
weather(12,lbn,rain).
weather(12,lso,rain).
weather(12,lbr,warm).
weather(12,lby,rain).
weather(12,lie,rain).
weather(12,ltu,snow).
weather(12,lux,rain).
weather(12,mkd,rain).
weather(12,mdg,warm).
weather(12,mwi,warm).
weather(12,mys,warm).
weather(12,mdv,warm).
weather(12,mli,warm).
weather(12,mlt,rain).
weather(12,mrt,warm).
weather(12,mus,warm).
weather(12,myt,warm).
weather(12,mex,rain).
weather(12,mda,snow).
weather(12,mco,rain).
weather(12,mng,snow).
weather(12,mne,rain).
weather(12,mar,rain).
weather(12,moz,warm).
weather(12,mmr,warm).
weather(12,nam,warm).
weather(12,npl,rain).
weather(12,nld,rain).
weather(12,nic,warm).
weather(12,ner,warm).
weather(12,nga,warm).
weather(12,prk,snow).
weather(12,nor,snow).
weather(12,omn,warm).
weather(12,pak,rain).
weather(12,pse,warm).
weather(12,pan,warm).
weather(12,pry,warm).
weather(12,per,rain).
weather(12,phl,warm).
weather(12,pol,snow).
weather(12,prt,rain).
weather(12,qat,rain).
weather(12,rou,snow).
weather(12,rus,snow).
weather(12,rwa,rain).
weather(12,shn,rain).
weather(12,smr,rain).
weather(12,wsm,warm).
weather(12,stp,warm).
weather(12,sau,rain).
weather(12,sen,warm).
weather(12,srb,rain).
weather(12,syc,warm).
weather(12,sle,warm).
weather(12,sgp,warm).
weather(12,svk,snow).
weather(12,svn,snow).
weather(12,som,warm).
weather(12,zaf,warm).
weather(12,kor,rain).
weather(12,ssd,warm).
weather(12,esp,rain).
weather(12,lka,warm).
weather(12,sdn,warm).
weather(12,sur,warm).
weather(12,swz,warm).
weather(12,swe,snow).
weather(12,che,snow).
weather(12,syr,rain).
weather(12,tjk,rain).
weather(12,tha,warm).
weather(12,tls,warm).
weather(12,tgo,warm).
weather(12,tun,rain).
weather(12,tur,rain).
weather(12,tkm,rain).
weather(12,uga,warm).
weather(12,ukr,snow).
weather(12,are,warm).
weather(12,gbr,rain).
weather(12,tza,warm).
weather(12,usa,rain).
weather(12,ury,warm).
weather(12,uzb,rain).
weather(12,ven,warm).
weather(12,vnm,warm).
weather(12,esh,rain).
weather(12,yem,warm).
weather(12,zmb,warm).
weather(12,zwe,warm).
